# Browsing database with Vespa
---
description: Migrate Postgres data into Vespa
output-file: template.html
title: Polars -> Vespa
---

# | default_exp Testing Polars for EDA, migrating cleaned data to Vespa

In [ ]:
# | hide
# import adbc_driver_postgresql.dbapi
# from datetime import datetime
# from enum import Enum
import json
import polars as pl
# import requests
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import vespa
from vespa.deployment import VespaDocker
from vespa.io import VespaResponse, VespaQueryResponse

In [ ]:
# make sure postgres is running!
# load postgres credentials
postgres_key_path = "../secrets/postgres_login.json"
with open(postgres_key_path, "r") as fo:
    postgres_key = json.loads(fo.read())
    user = postgres_key["user"]
    password = postgres_key["password"]
    host = postgres_key["host"]

In [ ]:
# send dataframe back into Postgres
cleaned_data_uri = f"postgresql://{user}:{password}@{host}/mealeon"

query = """
    SELECT
        *
    FROM cleaned_recipes
"""

df = pl.read_database_uri(query, cleaned_data_uri, engine="adbc")

In [ ]:
print(df)

shape: (128_736, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mealeon_i ┆ language ┆ source_id ┆ title     ┆ … ┆ photo_url ┆ descripti ┆ steps     ┆ cuisines  │
│ d         ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ on        ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ list[str] ┆ list[str] │
│ str       ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AfricanBi ┆ English  ┆ 629883    ┆ Smoked    ┆ … ┆ https://w ┆ Enjoy fal ┆ ["Remove  ┆ ["US Sout │
│ tes-3f1a4 ┆          ┆           ┆ Spatchcoc ┆   ┆ ww.africa ┆ l-off-the ┆ the       ┆ hern"]    │
│ fc7e09937 ┆          ┆           ┆ k Turkey  ┆   ┆ nbites.co ┆ -bone     ┆ giblet    ┆           │
│ 5ad…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ goodne…   ┆ package." ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ ,…        ┆           │
│ AfricanBi ┆ English  ┆ 607758    ┆ How to    ┆ … ┆ https://w ┆ It's time ┆ ["Discard ┆ ["America │
│ tes-ad987 ┆          ┆           ┆ Brine a   ┆   ┆ ww.africa ┆ to learn  ┆ any       ┆ n"]       │
│ 0f6689604 ┆          ┆           ┆ Turkey    ┆   ┆ nbites.co ┆ how to    ┆ wrappings ┆           │
│ 624…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ prop…     ┆ from t…   ┆           │
│ AfricanBi ┆ English  ┆ 582922    ┆ Refried   ┆ … ┆ https://w ┆ Refried   ┆ ["Rinse   ┆ ["Mexican │
│ tes-9b119 ┆          ┆           ┆ Beans     ┆   ┆ ww.africa ┆ Beans -   ┆ dry pinto ┆ "]        │
│ ba4403faa ┆          ┆           ┆           ┆   ┆ nbites.co ┆ chunky,   ┆ beans and ┆           │
│ 097…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ smooth…   ┆ pi…       ┆           │
│ AfricanBi ┆ English  ┆ 612196    ┆ Lemon     ┆ … ┆ https://w ┆ These     ┆ ["Preheat ┆ ["America │
│ tes-378e4 ┆          ┆           ┆ Blueberry ┆   ┆ ww.africa ┆ Lemon     ┆ the oven  ┆ n", "Brit │
│ cd9d94699 ┆          ┆           ┆ Scones    ┆   ┆ nbites.co ┆ Blueberry ┆ to        ┆ ish"]     │
│ 19c…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ Scones p… ┆ 400°F/20… ┆           │
│ AfricanBi ┆ English  ┆ 597746    ┆ Chocolate ┆ … ┆ https://w ┆ Take your ┆ ["Preheat ┆ ["US Sout │
│ tes-b81cc ┆          ┆           ┆ Pecan Pie ┆   ┆ ww.africa ┆ classic   ┆ oven to   ┆ hern"]    │
│ 0ca56e2dc ┆          ┆           ┆           ┆   ┆ nbites.co ┆ Pecan Pie ┆ 350℉      ┆           │
│ 4ea…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ to…       ┆ (175℃).…  ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ AllRecipe ┆ English  ┆ 212758    ┆ Seared    ┆ … ┆ https://w ┆ I'm still ┆ ["Heat 1  ┆ ["Missing │
│ s-0367413 ┆          ┆           ┆ Scallops  ┆   ┆ ww.allrec ┆ on my     ┆ teaspoon  ┆ Cuisine"] │
│ 0873d5db1 ┆          ┆           ┆ with Pine ┆   ┆ ipes.com/ ┆ healthy   ┆ olive oil ┆           │
│ 657…      ┆          ┆           ┆ apple…    ┆   ┆ thm…      ┆ eating…   ┆ in…       ┆           │
│ AllRecipe ┆ English  ┆ 11535     ┆ Double    ┆ … ┆ https://w ┆ Absolutel ┆ ["In a    ┆ ["Missing │
│ s-78da662 ┆          ┆           ┆ Batch     ┆   ┆ ww.allrec ┆ y sinful  ┆ double    ┆ Cuisine"] │
│ 7346b728a ┆          ┆           ┆ Caramel   ┆   ┆ ipes.com/ ┆ home-made ┆ boiler,   ┆           │
│ 325…      ┆          ┆           ┆ Brownies  ┆   ┆ thm…      ┆ br…       ┆ melt tog… ┆           │
│ AllRecipe ┆ English  ┆ 245227    ┆ Beet and  ┆ … ┆ https://w ┆ Delicious ┆ ["Preheat ┆ ["Missing │
│ s-1ed148b ┆          ┆           ┆ Fennel    ┆   ┆ ww.allrec ┆ doesn't   ┆ the oven  ┆ Cuisine"] │
│ f72e4ba56 ┆          ┆           ┆ Salad     ┆   ┆ ipes.com/ ┆ have to   ┆ to 400    ┆           │
│ cdb…      ┆          ┆           ┆ with Goa… ┆   ┆ thm…      ┆ be h…     ┆ degr…     ┆           │
│ AllRecipe ┆ English  ┆ 146933    ┆ Beach     ┆ … ┆ https://w ┆ Fresh can ┆ ["Combine ┆ ["Missing │
│ s-ea19acf ┆          ┆           ┆ Body      ┆   ┆ ww.allrec ┆ taloupe,  ┆ the       ┆ Cuisine"] │
│ 9d27b3c5b ┆          ┆           ┆ Fruit     ┆   ┆ ipes.com/ ┆ honeydew, ┆ peach,    ┆           │
│ 04f…      ┆          ┆           ┆ Soup      ┆   ┆ thm…      ┆ pe…       ┆ strawberr ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ …         ┆           │
│ AllRecipe ┆ English  ┆ 144529    ┆ Beets on  ┆ … ┆ https://w ┆ These     ┆ ["Gather  ┆ ["Missing │
│ s-f3d014b ┆          ┆           ┆ the Grill ┆   ┆ ww.allrec ┆ grilled   ┆ all ingre ┆ Cuisine"] │
│ eb4ddf274 ┆          ┆           ┆           ┆   ┆ ipes.com/ ┆ beets are ┆ dients.   ┆           │
│ 9d5…      ┆          ┆           ┆           ┆   ┆ thm…      ┆ easy t…   ┆ Preh…     ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Try mixing in PyVespa
Following documentation [here](https://pyvespa.readthedocs.io/en/latest/getting-started-pyvespa.html)

In [ ]:
from vespa.package import (
    ApplicationPackage,
    Field,
    Schema,
    Document,
    HNSW,
    RankProfile,
    Component,
    Parameter,
    FieldSet,
    GlobalPhaseRanking,
    Function,
    DocumentSummary,
    Summary
)

package = ApplicationPackage(
    name="mealeon3",
    schema=[
        Schema(
            name="mealeon3",
            document=Document(
                fields=[
                    Field(
                        name="language", 
                        type="string", 
                        indexing=["set_language"],
                        # match=["word"]
                    ),
                    Field(
                        name="id",
                        type="string",
                        indexing=["attribute", "summary"],
                        match=["word"],
                        bolding=True,
                    ),
                    Field(
                        name="title",
                        type="string",
                        indexing=["index", "summary"],
                        index="enable-bm25",
                        match=["word"]
                    ), 
                    Field(
                        name="description",
                        type="string",
                        indexing=["index"],
                        index="enable-bm25",
                        match=["word"],
                    ),                 
                    Field(
                        name="ingredients",
                        type="array<string>",
                        indexing=["index", "attribute"],
                        # attribute="fast-search",
                        index="enable-bm25",
                        # match=["word"],
                    ),
                    Field(
                        name="steps",
                        type="array<string>",
                        indexing=["index", "attribute"],
                        index="enable-bm25"
                    ),
                    Field(
                        name="cuisines",
                        type="array<string>",
                        indexing=["attribute", "summary"],
                        # index="enable-bm25",
                        match=["word"],
                        rank="filter"
                    ),
                    # Field(
                    #     name="embedding",
                    #     type="tensor<float>(x[384])",
                    #     indexing=[
                    #         'input title . " " . input body',
                    #         "embed",
                    #         "index",
                    #         "attribute",
                    #     ],
                    #     ann=HNSW(distance_metric="angular"),
                    #     is_document_field=False,
                    # ),
                ]
            ),
            fieldsets=[
                FieldSet(
                    name="default", 
                    fields=["title", "ingredients"]
                )
            ],
            document_summaries=[
                    DocumentSummary(
                    name="document-summary",
                    summary_fields=[
                        Summary("id")
                    ]
                ),
            ],
            rank_profiles=[
                RankProfile(
                    name="default",
                    first_phase="nativeRank(title, ingredients)"
                ),
                RankProfile(
                    name="bm25",
                    inherits="default",
                    first_phase="bm25(title) + bm25(ingredients)",
                    # inputs=[("query(q)", "tensor<float>(x[384])")],
                    functions=[
                        Function(name="bm25sum", expression="bm25(title) + bm25(ingredients)")
                    ],
                ),
                RankProfile(
                    name="combined", 
                    inherits="default",
                    first_phase="bm25(title) + bm25(ingredients) + nativeRank(title) + nativeRank(ingredients)",
                    functions=[
                        Function(name="bm25nativeRank",
                                 expression="bm25(title) + bm25(ingredients) + nativeRank(title) + nativeRank(ingredients)")
                    ]
                )
                # RankProfile(
                #     name="semantic",
                #     inputs=[("query(q)", "tensor<float>(x[384])")],
                #     first_phase="closeness(field, embedding)",
                # ),
                # RankProfile(
                #     name="fusion",
                #     inherits="bm25",
                #     inputs=[("query(q)", "tensor<float>(x[384])")],
                #     first_phase="closeness(field, embedding)",
                #     global_phase=GlobalPhaseRanking(
                #         expression="reciprocal_rank_fusion(bm25sum, closeness(field, embedding))",
                #         rerank_count=1000,
                #     ),
                # ),
            ],
        )
    ],
    # components=[
    #     Component(
    #         id="e5",
    #         type="hugging-face-embedder",
    #         parameters=[
    #             Parameter(
    #                 "transformer-model",
    #                 {
    #                     "url": "https://github.com/vespa-engine/sample-apps/raw/master/simple-semantic-search/model/e5-small-v2-int8.onnx"
    #                 },
    #             ),
    #             Parameter(
    #                 "tokenizer-model",
    #                 {
    #                     "url": "https://raw.githubusercontent.com/vespa-engine/sample-apps/master/simple-semantic-search/model/tokenizer.json"
    #                 },
    #             ),
    #         ],
    #     )
    # ],
)

In [ ]:
# try mixing in PyVespa
vespa_docker = VespaDocker(port=8183,
                           cfgsrv_port=19092)
app = vespa_docker.deploy(application_package=package)

Waiting for configuration server, 0/300 seconds...
Waiting for configuration server, 5/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Waiting for application status, 0/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Waiting for application status, 5/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Waiting for application status, 10/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Waiting for application status, 15/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Waiting for application status, 20/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Waiting for application status, 25/300 seconds...
Using plain http against endpoint http://localhost:8183/ApplicationStatus
Application is up!
Finished deployment.

In [ ]:
# query should be recipe name?
    # WHERE title !contains {query}
# cuisine name should be in the WHERE filter clause of YQL
    # AND WHERE cuisine NOT IN {cuisines}
# how to penalize similar title?

# start with plain keyword search

with app.syncio(connections=1) as session:
    query = "Buffalo Wings"
    response: VespaQueryResponse = session.query(
        yql=f"select * from sources mealeon3 where (title contains '{query}') limit 10",
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
print(response.hits)

[]

In [ ]:
import pprint

pprint.pp(response.hits)

[]

In [ ]:
# list of recipe IDs
baseline_to_search = [
    'BBCFood-11015de4db20e53dcda0035673dfdbeca355d2a1d37d71f13d5fe5ea7ccca02d',
    'Epicurious-32b7b2040aba4e44b0f5e34b094aafc6b1b7168e689ba6c92428fa8c9e235c5a',
    'Epicurious-9e24d01c507b4ee64ee484fc4efafb5f3d44709abb8fc36f1b34a91f7b69b678',
    'AllRecipes-fddb273d401ac45b568695daeb1abe0b632696dd867992fd401e31dc794d66f9',
    'AllRecipes-715d84d02e183deaaf2400f7526c80a2b01a25032c1abb125c28fe4d879cc672', 
    'AfricanBites-6f62a39913dd8029cd399d4ae47b0551f94a16865a3143b5dd28664c0880596e', 
    'Epicurious-85d1faf0a617f34521543d7c64122288b8ba65ae55b7a37a9abeb22d8845ff11',
    'AllRecipes-867b4f3b539b381fb9f35252402fc14efc9d6fcc64353089959ac159372a8199', 
    'BBCFood-c6b9581aa49ee6b0cc3f686f58cfd124c395284cc46dfcde5bc931982975ee15',
    'BBCFood-d59ab715a7f6f0022155b1149e4e059b0497fd790993fb11f1795b901cae8f97',
    'AllRecipes-d431cefd9f595be8a8fcd7ff9e05a82ca1b79220c72edde1aa2a0b6574060c04',
    'BBCFood-056f016b0b0d8c383c1a6bf47077a46a64529c04ab043c14dce3b23d3980e0ed',
    'AllRecipes-d4bb95742a7fd71eb848a7d4b2a4dc13220e5bb378e1b6805d5ea493e0e1166d',
    'Epicurious-0293b95bfc74cf90dc07e2ee399312e40e03d14dd99e5db84e678a1393b131cc',
    'Panlasang_Pinoy-1d186c4a4c274e42580488e652e3448aa9942642fa9e990d89d3e1894056ce78',
    'AllRecipes-9bfd691bb0521c3bba0275d1ef18ac30ea15c2aeb0a48f2b9df1d5defd962bed',
    'Epicurious-e7efaeb37ea032d7faaad76c1e0675f987aa5eb162e5447927ae510c0301807e',
    'Epicurious-ca2d5e56121ae04e8b7bdcd07648796b2d95afed017fc56200535ad43ca8e51d',
    'Epicurious-7761b0f03aaf56b52b1de417213b66fddf1d49c554dabaacb23c9c7a260982ba',
    'Epicurious-e367b68ed6df8b0bccbeb73f9d82897294ef267fa3a74d30505ce7470b2384dc',
    'AllRecipes-a0ae2dfd0ca25ae3146df101d1dc0e7c54e39eec69617ff634f42d80d7b70be4',
    'AfricanBites-8e8956de6dd17820c4e5146820972193f2587d97e80ee1a754c92dce048e4f9e',
    'BBCFood-3aa9507e04707431ec512662444ef602910c6c0ecc997de7ea206729985c5c08',
    'AllRecipes-6914cfedf5d3af52ea66433959c958821b8940ee1948fbe29f841d48ad1de4a4',
    'AfricanBites-2f35554786f85a304f1f5e86313f5d35730777a4f0861edf3474a914e9b7ec23',
    'Epicurious-0a033ff3220eae4b638fd08de58646ba84ed5f184b89d792afe2ed90a8c4a859',
    'BBCFood-adcbfceaa8636f83ff8866d44bc7a44385c71250d73d427c08dbe345e4127143',
    'AllRecipes-81a545cc3eac6e8b89274a6a9f4a6574232e40c3917f499a431d9fa6ebc540bf',
    'BBCFood-0a7c810d7b7c99ae728f9a2deff14340edb099949f20fed75a8083c29ca83aab',
    'Epicurious-a0ab4c8e25f1fe8e65f400f93db23cf55e1e46cb4361cd65426f908f3013f33d',
    'AllRecipes-bb6dd1b85cfd3cbfeb68160c187862ec6de84739123733ceeaae2976141f8936',
    'Epicurious-3b409b8e753718bdb272130405491c4dcb4c26e73412b54cea408319dc932c6e',
    'AllRecipes-92c5c30f5c0b1655a1e1900fcdaa603917f2abf62529c130713412a844046e33',
    'AfricanBites-fc015a5953d8811734f652ad17ba50d73f98d783350df0a95a6e2015007263f0',
    'AllRecipes-384fd2f67b06a5bfdf532f94d5e89df99e08b91c5d9dace20fd29bba7b8fdad3',
    'Epicurious-aa7806301b6fc904134d692a2a425d0a0fd5a1f6f95cb431e8c31173db7d99fa',
    'AllRecipes-d9b8ecb976729402694fa448a53b741404ef3e10f6dd9fe2219fc6fb3fb7b038',
    'BBCFood-ee117ce84728c9b2e90654f59895a89dc7c10599b61bed83f55e9bdf723e6890',
    'BBCFood-53dc7bd8da3ef8a7dedfef0b2be1880f71585752d8113313c6d9e49bd5cba6fa',
    'BBCFood-2ab22cd0a3889f38cf740040d33aae5a4baa8568b70cde5233d6f8a673958140',
    'Epicurious-1c0fe6496b26a8b7bdf549e9ed70bc9802d7df404b89f1d3de6d01a1a44d31f8',
    'BBCFood-47410dc7097b2609d5c0a80e4ce6f938b00be18b52907e5a5322e33d6edee335',
    'AfricanBites-587700762275fbf6a6e2a343b27cc689317725ae2d1724cd33c6c841583afc3e',
    'Epicurious-ca99be627e88806d8357a5cbfdd314b3643028f275e6ae1c90adfcf3ae9e30d4',
    'Epicurious-7e9ff3fc13b040941ed9f7a4bbfd809e17a9ce7d5b569f1f6c4ba96e9a9ae140',
    'Epicurious-4b6f818877199d375e801cec974c6f6b037b4c0b2aa2bbec0238dd77f797264d',
    'AllRecipes-c6d0cd77e37ed8069f0d9e72f9e832026459273ac1bc2587800dc8fcd1418ec7',
    'AllRecipes-48bde26e015dc9cbcbb540c4710248d538227d4afe5aa3e977e34710289789bb',
    'AllRecipes-cac0d29872bd9f49d34d8c9eac41a3806929420f84e36b8e579c3bce939cdc7b',
    'AllRecipes-9a5dc3fa2511284deeb5ee469d110874b0de9c021439cd0e088d3ef4f53f28bf',
    'BBCFood-6d6cc18dadaffa5ea10194b59aa6e310d34b1f713756d0b528cc57c5e61d92e3',
    'AllRecipes-5fc2fc72d7caf510b4ccde625c54a0907de1489d323d385d74c2a6c9c5d61c7b',
    'AfricanBites-56e7fc4d3a1db457444cf4744911356514b3ac961f04976a0fb127f0ac8145be',
    'AllRecipes-8aa892f3f4d827f781d2bc1491351d982144e2fa2bb3226ebf5cc6af6df5ac5a',
    'AllRecipes-e13da6adb836dcf514a8f285e162a9529271a647a11f2da6e60697541260c1ec',
    'Epicurious-aef6e4737b2b9248ae51893ec6d2295ab2380bc67e817ebef13416c65d44a3a6',
    'AllRecipes-e11c702c9c5f8d5c0d63a6b58a60d90b87f1f4e88dad3586b91b3248bb721504',
    'Epicurious-b6ae682f94cb0c4bf256ebfc569550702ef82612457ff8e601cf9e61e0b5f4ab',
    'Epicurious-9908959a4069c75bd1d95c4b11678d15a63a153c91d164d3f7d1159d35ae05dc',
    'AllRecipes-4f31ce862b67de4659f76e3a4de016a32770c878544d112aae95cc09b63d799a',
    'AllRecipes-f3aafa676ce976137a1e9a62a6beeca6288c2a4b0c35ba2c4da9cd6a4fa9f466',
    'Epicurious-b3f8d44e48bba1b47e5cf1482d8c5e076359fa919061bbfd2f075d131aea2025',
    'Epicurious-6a7b3ef6808832fbf1ab5a8e539eb794866d630c1b65218ee7b5c385b78f65a4',
    'AllRecipes-0caa9e3e35dee2910e6f81c869d1176a2de129b8e3c7fddf6e469b9e3977fadb',
    'AllRecipes-3c9cbb4d78d017a21a48907adbc31c2593ebbd0717b9391779a2f75b531fcbe4',
    'AllRecipes-3e906cbcfdee7e4c52d087efc24aea9c7e3b760a8c5f0d1c85c459f3354b643d',
    'Panlasang_Pinoy-b5a6e813375f4cbb399a2e68dec8f9448d64c4f01f2e5b5accd9188509875f17',
    'Epicurious-d2b862c91c84a69b9b2f2be1a1cc9702a2d6af8a6f1e5dcaccbacda6ed9f31b0',
    'AllRecipes-9e94827f263b0409c124dd60e95e4a61e1d446940e3ad3b88b4e3b43d00b6f65',
    'AllRecipes-b8116cc920cd9d916cd196927ad2af1062785cdaa3d3b4fc3e997ee86fd75c84',
    'Epicurious-4284e53129c7dc89f97f2f1933843946745df061370bd1ab738bf2afe1c537c3',
    'AllRecipes-2b9df9cae8603bc9f0c5ddadf04fe529c1174d38a7e32031e42ee9897ea8e05f',
    'AfricanBites-5ca4ea56e8d49013ebd7457560a386a5e1a1059f267514b7c1dff7b9f0c78d72',
    'AllRecipes-bd864502bd1b052f501d3148d66effc966246a69a5e705c585fa366d9599e090',
    'AllRecipes-1b1ac4f279d0cbb0c680da7a1839d0031a52f3cc73681dbb2644cf96d6aec4f9'
]

In [ ]:
filtered_to_investigate = df.filter(pl.col("mealeon_id").is_in(baseline_to_search))

In [ ]:
filtered_to_investigate

shape: (68, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mealeon_i ┆ language ┆ source_id ┆ title     ┆ … ┆ photo_url ┆ descripti ┆ steps     ┆ cuisines  │
│ d         ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ on        ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ list[str] ┆ list[str] │
│ str       ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AfricanBi ┆ English  ┆ 597818    ┆ Banana    ┆ … ┆ https://w ┆ Homemade  ┆ ["Add dry ┆ ["US Sout │
│ tes-58770 ┆          ┆           ┆ Pudding   ┆   ┆ ww.africa ┆ Banana    ┆ ingredien ┆ hern"]    │
│ 0762275fb ┆          ┆           ┆           ┆   ┆ nbites.co ┆ Pudding – ┆ ts to a   ┆           │
│ f6a…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ a cl…     ┆ sau…      ┆           │
│ AfricanBi ┆ English  ┆ 598753    ┆ Tiramisu  ┆ … ┆ https://w ┆ This      ┆ ["In a    ┆ ["Italian │
│ tes-6f62a ┆          ┆           ┆           ┆   ┆ ww.africa ┆ classic   ┆ medium    ┆ "]        │
│ 39913dd80 ┆          ┆           ┆           ┆   ┆ nbites.co ┆ Italian   ┆ saucepan, ┆           │
│ 29c…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ coffee-fl ┆ whisk …   ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ AfricanBi ┆ English  ┆ 607516    ┆ Apple Pie ┆ … ┆ https://w ┆ Made with ┆ ["Start   ┆ ["America │
│ tes-fc015 ┆          ┆           ┆           ┆   ┆ ww.africa ┆ lightly   ┆ by making ┆ n"]       │
│ a5953d881 ┆          ┆           ┆           ┆   ┆ nbites.co ┆ spiced    ┆ the pie   ┆           │
│ 173…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ apple…    ┆ crus…     ┆           │
│ AfricanBi ┆ English  ┆ 608647    ┆ Fish and  ┆ … ┆ https://w ┆ Perfectly ┆ ["In a    ┆ ["British │
│ tes-2f355 ┆          ┆           ┆ Chips     ┆   ┆ ww.africa ┆ seasoned  ┆ large     ┆ "]        │
│ 54786f85a ┆          ┆           ┆           ┆   ┆ nbites.co ┆ tender    ┆ bowl,     ┆           │
│ 304…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ fish…     ┆ whisk     ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ toget…    ┆           │
│ AfricanBi ┆ English  ┆ 567371    ┆ Huli Huli ┆ … ┆ https://w ┆ Huli Huli ┆ ["In a    ┆ ["America │
│ tes-5ca4e ┆          ┆           ┆ Chicken   ┆   ┆ ww.africa ┆ Chicken - ┆ medium    ┆ n"]       │
│ a56e8d490 ┆          ┆           ┆           ┆   ┆ nbites.co ┆ Grilled   ┆ bowl, mix ┆           │
│ 13e…      ┆          ┆           ┆           ┆   ┆ m/w…      ┆ or…       ┆ the pi…   ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ AllRecipe ┆ English  ┆ 14713     ┆ Souvlaki  ┆ … ┆ https://w ┆ Souvlaki  ┆ ["This    ┆ ["Missing │
│ s-9e94827 ┆          ┆           ┆           ┆   ┆ ww.allrec ┆ is a      ┆ homemade  ┆ Cuisine"] │
│ f263b0409 ┆          ┆           ┆           ┆   ┆ ipes.com/ ┆ Greek     ┆ souvlaki  ┆           │
│ c12…      ┆          ┆           ┆           ┆   ┆ thm…      ┆ specialty ┆ recip…    ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ AllRecipe ┆ English  ┆ 9239      ┆ Yorkshire ┆ … ┆ https://w ┆ This      ┆ ["Mix     ┆ ["Missing │
│ s-92c5c30 ┆          ┆           ┆ Pudding   ┆   ┆ ww.allrec ┆ Yorkshire ┆ together  ┆ Cuisine"] │
│ f5c0b1655 ┆          ┆           ┆           ┆   ┆ ipes.com/ ┆ pudding   ┆ flour and ┆           │
│ a1e…      ┆          ┆           ┆           ┆   ┆ thm…      ┆ recipe …  ┆ salt …    ┆           │
│ AllRecipe ┆ English  ┆ 38113     ┆ Ginger    ┆ … ┆ https://w ┆ This is a ┆ ["In a    ┆ ["Missing │
│ s-3e906cb ┆          ┆           ┆ Beef      ┆   ┆ ww.allrec ┆ recipe    ┆ large     ┆ Cuisine"] │
│ cfdee7e4c ┆          ┆           ┆           ┆   ┆ ipes.com/ ┆ that my   ┆ bowl, mix ┆           │
│ 52d…      ┆          ┆           ┆           ┆   ┆ thm…      ┆ grand…    ┆ onions,…  ┆           │
│ AllRecipe ┆ English  ┆ 256165    ┆ Boeuf Bou ┆ … ┆ https://w ┆ This beef ┆ ["Heat    ┆ ["Missing │
│ s-a0ae2df ┆          ┆           ┆ rguignon  ┆   ┆ ww.allrec ┆ bourguign ┆ oil in a  ┆ Cuisine"] │
│ d0ca25ae3 ┆          ┆           ┆           ┆   ┆ ipes.com/ ┆ on recipe ┆ large,    ┆           │
│ 146…      ┆          ┆           ┆           ┆   ┆ thm…      ┆ c…        ┆ heavy s…  ┆           │
│ AllRecipe ┆ English  ┆ 12406     ┆ Tourtiere ┆ … ┆ https://w ┆ Tradition ┆ ["In a    ┆ ["Missing │
│ s-3c9cbb4 ┆          ┆           ┆           ┆   ┆ ww.allrec ┆ al French ┆ Dutch     ┆ Cuisine"] │
│ d78d017a2 ┆          ┆           ┆           ┆   ┆ ipes.com/ ┆ -Canadian ┆ oven,     ┆           │
│ 1a4…      ┆          ┆           ┆           ┆   ┆ thm…      ┆ Me…       ┆ brown     ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ groun…    ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

First things we need to do are check that these recipes "make sense"
- Are these recipes good baselines?

In [ ]:
with pl.Config(fmt_table_cell_list_len=20,
               fmt_str_lengths=1000,
               set_tbl_width_chars=70
               ):
    print(filtered_to_investigate.select(["title", "ingredients", "description", "cuisines"])[0:5])

shape: (5, 4)
┌─────────────────┬────────────────┬────────────────┬────────────────┐
│ title           ┆ ingredients    ┆ description    ┆ cuisines       │
│ ---             ┆ ---            ┆ ---            ┆ ---            │
│ str             ┆ list[str]      ┆ str            ┆ list[str]      │
╞═════════════════╪════════════════╪════════════════╪════════════════╡
│ Banana Pudding  ┆ ["2 ½          ┆ Homemade       ┆ ["US           │
│                 ┆ tablespoon s   ┆ Banana Pudding ┆ Southern"]     │
│                 ┆ (18.75 g)      ┆ – a classic    ┆                │
│                 ┆ cornstarch ",  ┆ Southern       ┆                │
│                 ┆ "6 tablespoons ┆ no-bake        ┆                │
│                 ┆ (75 g)         ┆ dessert with   ┆                │
│                 ┆ granulated     ┆ decadent       ┆                │
│                 ┆ sugar ",       ┆ layers of      ┆                │
│                 ┆ "Pinch of salt ┆ vanilla        ┆                │
│                 ┆ ", "2 cups     ┆ wafers, fresh  ┆                │
│                 ┆ (480 ml) whole ┆ banana slices, ┆                │
│                 ┆ milk ", "½ cup ┆ whipped cream, ┆                │
│                 ┆ (120 ml) heavy ┆ and vanilla    ┆                │
│                 ┆ cream", "6     ┆ custard all    ┆                │
│                 ┆ large egg      ┆ made from      ┆                │
│                 ┆ yolks ", "3    ┆ scratch. This  ┆                │
│                 ┆ tablespoons    ┆ is a fantastic ┆                │
│                 ┆ (28 g)         ┆ make-ahead     ┆                │
│                 ┆ unsalted       ┆ dessert that   ┆                │
│                 ┆ butter ,       ┆ is a hit all   ┆                │
│                 ┆ softened to    ┆ year round!    ┆                │
│                 ┆ room           ┆                ┆                │
│                 ┆ temperature ", ┆                ┆                │
│                 ┆ "1 tablespoon  ┆                ┆                │
│                 ┆ (13 g) pure    ┆                ┆                │
│                 ┆ vanilla        ┆                ┆                │
│                 ┆ extract  ",    ┆                ┆                │
│                 ┆ "vanilla       ┆                ┆                │
│                 ┆ wafers  ",     ┆                ┆                │
│                 ┆ "4-5  large    ┆                ┆                │
│                 ┆ ripe firm      ┆                ┆                │
│                 ┆ bananas ",     ┆                ┆                │
│                 ┆ "homemade      ┆                ┆                │
│                 ┆ whipped cream  ┆                ┆                │
│                 ┆ "]             ┆                ┆                │
│ Tiramisu        ┆ ["5 large egg  ┆ This classic   ┆ ["Italian"]    │
│                 ┆ yolks , room   ┆ Italian coffee ┆                │
│                 ┆ temperature",  ┆ -flavored      ┆                │
│                 ┆ "¾ cup         ┆ TIRAMISU is a  ┆                │
│                 ┆ granulated     ┆ creamy         ┆                │
│                 ┆ sugar", "½ cup ┆ flavorful      ┆                │
│                 ┆ whole milk ",  ┆ no-bake        ┆                │
│                 ┆ "1 cup         ┆ dessert. It    ┆                │
│                 ┆ mascarpone     ┆ comes in two   ┆                │
│                 ┆ cheese ", "1   ┆ versions - the ┆                │
│                 ┆ cup espresso   ┆ classic one    ┆                │
│                 ┆ or very strong ┆ using eggs AND ┆                │
│                 ┆ coffee (double ┆ a 20-minute    ┆                │
│                 ┆ for alcohol    ┆ quick version. ┆                │
│                 ┆ free) ", "2    ┆ Truly one of   ┆                │
│                 ┆ tablespoons    ┆ the best       ┆                │
│                 ┆ rum (leave out ┆ desserts you   ┆                │
│                 ┆ for            ┆ can make in    ┆                │
│                 ┆ alcohol-free)  ┆ your entire    ┆                │
│                 ┆ ", "1 teaspoon ┆ life!          ┆                │
│                 ┆ vanilla        ┆                ┆                │
│                 ┆ extract ", "½  ┆                ┆                │
│                 ┆ cup coffee     ┆                ┆                │
│                 ┆ liqueur (leave ┆                ┆                │
│                 ┆ out for        ┆                ┆                │
│                 ┆ alcohol-free)  ┆                ┆                │
│                 ┆ ", "2          ┆                ┆                │
│                 ┆ tablespoons    ┆                ┆                │
│                 ┆ cocoa powder , ┆                ┆                │
│                 ┆ split,         ┆                ┆                │
│                 ┆ sweetened or   ┆                ┆                │
│                 ┆ unsweetened    ┆                ┆                │
│                 ┆ ", "24         ┆                ┆                │
│                 ┆ ladyfingers ", ┆                ┆                │
│                 ┆ "2 cups        ┆                ┆                │
│                 ┆ homemade       ┆                ┆                │
│                 ┆ whipped cream  ┆                ┆                │
│                 ┆ ", "1 ½ cup    ┆                ┆                │
│                 ┆ whipped cream  ┆                ┆                │
│                 ┆ ", "⅓ cup      ┆                ┆                │
│                 ┆ granulated     ┆                ┆                │
│                 ┆ sugar", "1     ┆                ┆                │
│                 ┆ teaspoon       ┆                ┆                │
│                 ┆ vanilla        ┆                ┆                │
│                 ┆ extract ", "8  ┆                ┆                │
│                 ┆ ounce  (1 cup) ┆                ┆                │
│                 ┆ mascarpone     ┆                ┆                │
│                 ┆ cheese ", "3-4 ┆                ┆                │
│                 ┆ tablespoons    ┆                ┆                │
│                 ┆ cocoa powder", ┆                ┆                │
│                 ┆ "1 cup         ┆                ┆                │
│                 ┆ espresso or    ┆                ┆                │
│                 ┆ very strong    ┆                ┆                │
│                 ┆ coffee ", "1-2 ┆                ┆                │
│                 ┆ tablespoons    ┆                ┆                │
│                 ┆ rum liquor     ┆                ┆                │
│                 ┆ (optional) ",  ┆                ┆                │
│                 ┆ "½ cup         ┆                ┆                │
│                 ┆ marsala sweet  ┆                ┆                │
│                 ┆ wine  ", … "1  ┆                ┆                │
│                 ┆ cup or more    ┆                ┆                │
│                 ┆ homemade       ┆                ┆                │
│                 ┆ whipped cream  ┆                ┆                │
│                 ┆ (optional, for ┆                ┆                │
│                 ┆ piping) "]     ┆                ┆                │
│ Apple Pie       ┆ ["Homemade pie ┆ Made with      ┆ ["American"]   │
│                 ┆ crust or       ┆ lightly spiced ┆                │
│                 ┆ store-bought   ┆ apple filling, ┆                │
│                 ┆ pie crust  ",  ┆ this APPLE PIE ┆                │
│                 ┆ "7-8 apples    ┆ made with the  ┆                │
│                 ┆ (about 3 ½     ┆ best           ┆                │
│                 ┆ pounds)", "½   ┆ buttery-flaky  ┆                │
│                 ┆ cup brown      ┆ homemade pie   ┆                │
│                 ┆ sugar", "¼ cup ┆ crust is a     ┆                │
│                 ┆ granulated     ┆ must-have on   ┆                │
│                 ┆ sugar", "1     ┆ any family     ┆                │
│                 ┆ teaspoon       ┆ occasion! Use  ┆                │
│                 ┆ ground         ┆ a mix of       ┆                │
│                 ┆ cinnamon ,     ┆ different      ┆                │
│                 ┆ plus more if   ┆ kinds of       ┆                │
│                 ┆ desired", "¼   ┆ apples to make ┆                │
│                 ┆ teaspoon       ┆ the best       ┆                │
│                 ┆ ground nutmeg  ┆ homemade pie!  ┆                │
│                 ┆ plus more if   ┆                ┆                │
│                 ┆ desired", "¼   ┆                ┆                │
│                 ┆ teaspoon       ┆                ┆                │
│                 ┆ ground ginger  ┆                ┆                │
│                 ┆ ", "⅛ teaspoon ┆                ┆                │
│                 ┆ ground         ┆                ┆                │
│                 ┆ allspice plus  ┆                ┆                │
│                 ┆ more if        ┆                ┆                │
│                 ┆ desired", "½   ┆                ┆                │
│                 ┆ teaspoon       ┆                ┆                │
│                 ┆ salt", "2      ┆                ┆                │
│                 ┆ tablespoons    ┆                ┆                │
│                 ┆ fresh lemon    ┆                ┆                │
│                 ┆ juice ", "2    ┆                ┆                │
│                 ┆ tablespoons    ┆                ┆                │
│                 ┆ cold unsalted  ┆                ┆                │
│                 ┆ butter ,       ┆                ┆                │
│                 ┆ divided", "3   ┆                ┆                │
│                 ┆ tablespoons    ┆                ┆                │
│                 ┆ cornstarch",   ┆                ┆                │
│                 ┆ "1 large egg", ┆                ┆                │
│                 ┆ "1 tablespoon  ┆                ┆                │
│                 ┆ heavy cream or ┆                ┆                │
│                 ┆ whole milk",   ┆                ┆                │
│                 ┆ "coarse sugar  ┆                ┆                │
│                 ┆ or turbinado   ┆                ┆                │
│                 ┆ sugar for      ┆                ┆                │
│                 ┆ sprinkling"]   ┆                ┆                │
│ Fish and Chips  ┆ ["1 ¼   cup (5 ┆ Perfectly      ┆ ["British"]    │
│                 ┆ ounces)        ┆ seasoned       ┆                │
│                 ┆ all-purpose    ┆ tender fish    ┆                │
│                 ┆ flour", "¾     ┆ fillet,        ┆                │
│                 ┆ cup (4 ounces) ┆ encased in a   ┆                │
│                 ┆ cornstarch",   ┆ light and      ┆                │
│                 ┆ "2  teaspoons  ┆ mellow beer    ┆                │
│                 ┆ (6g) garlic    ┆ batter served  ┆                │
│                 ┆ powder", "¼    ┆ with crispy,   ┆                │
│                 ┆ teaspoon       ┆ real potato    ┆                │
│                 ┆ (0.5g) cayenne ┆ fries. Serve   ┆                │
│                 ┆ pepper", "1    ┆ these          ┆                │
│                 ┆ teaspoon (2g)  ┆ side-by-side   ┆                │
│                 ┆ paprika", "2   ┆ for a great    ┆                │
│                 ┆ teaspoons (8g) ┆ appetizer or   ┆                │
│                 ┆ baking         ┆ snacks to      ┆                │
│                 ┆ powder", "1 ½  ┆ share with     ┆                │
│                 ┆ teaspoon       ┆ your favorite  ┆                │
│                 ┆ (7.5g) salt",  ┆ game-day       ┆                │
│                 ┆ "½  teaspoon   ┆ buddy!         ┆                │
│                 ┆ (1g) white     ┆                ┆                │
│                 ┆ pepper", "1 ½  ┆                ┆                │
│                 ┆ cups (374g)    ┆                ┆                │
│                 ┆ beer", "1 ½    ┆                ┆                │
│                 ┆ pound          ┆                ┆                │
│                 ┆ (380.39g)      ┆                ┆                │
│                 ┆ skinless cod   ┆                ┆                │
│                 ┆ fillet,  about ┆                ┆                │
│                 ┆ 1 inch thick,  ┆                ┆                │
│                 ┆ cut into       ┆                ┆                │
│                 ┆ strips", "1    ┆                ┆                │
│                 ┆ quart (946ml)  ┆                ┆                │
│                 ┆ water", "ice", ┆                ┆                │
│                 ┆ "1  tablespoon ┆                ┆                │
│                 ┆ (15ml)         ┆                ┆                │
│                 ┆ vinegar", "2-3 ┆                ┆                │
│                 ┆ russet         ┆                ┆                │
│                 ┆ potatoes,      ┆                ┆                │
│                 ┆ about 1 1/2    ┆                ┆                │
│                 ┆ pounds", "salt ┆                ┆                │
│                 ┆ and seasonings ┆                ┆                │
│                 ┆ to taste"]     ┆                ┆                │
│ Huli Huli       ┆ ["3 1/2- 4     ┆ Huli Huli      ┆ ["American"]   │
│ Chicken         ┆ pounds chicken ┆ Chicken -      ┆                │
│                 ┆ drumsticks",   ┆ Grilled or     ┆                │
│                 ┆ "1 cup         ┆ Baked Hawaiian ┆                │
│                 ┆ unsweetened    ┆ Chicken        ┆                │
│                 ┆ pineapple      ┆ Drumsticks     ┆                │
│                 ┆ juice", "1/3   ┆ marinated in a ┆                │
│                 ┆ cup soy        ┆ sweet          ┆                │
│                 ┆ sauce", "1/4   ┆ pineapple,     ┆                │
│                 ┆ cup brown      ┆ ginger, garlic ┆                │
│                 ┆ sugar", "2     ┆ sauce. Sweet,  ┆                │
│                 ┆ Tablespoons    ┆ Sticky and     ┆                │
│                 ┆ Honey", "1/4   ┆ Sweet.         ┆                │
│                 ┆ cup ketchup",  ┆                ┆                │
│                 ┆ "½ Tablsespoon ┆                ┆                │
│                 ┆ fresh grated   ┆                ┆                │
│                 ┆ ginger", "1    ┆                ┆                │
│                 ┆ Tablespoon     ┆                ┆                │
│                 ┆ minced         ┆                ┆                │
│                 ┆ garlic", "1-   ┆                ┆                │
│                 ┆ teaspoon cumin ┆                ┆                │
│                 ┆ spice", "1-    ┆                ┆                │
│                 ┆ teaspoon       ┆                ┆                │
│                 ┆ Sriracha       ┆                ┆                │
│                 ┆ adjust to      ┆                ┆                │
│                 ┆ taste", "1/2   ┆                ┆                │
│                 ┆ -1 Lemon       ┆                ┆                │
│                 ┆ juice", "¼ cup ┆                ┆                │
│                 ┆ chicken        ┆                ┆                │
│                 ┆ broth", "Green ┆                ┆                │
│                 ┆ onions sliced  ┆                ┆                │
│                 ┆ for garnish"]  ┆                ┆                │
└─────────────────┴────────────────┴────────────────┴────────────────┘

Let's re-apply the previous text processing on ingredients to shorten these huge lists and make them easier to read (previous text processing removed numbers and I think units)

Previously, using `TFIDFVectorizer`, the params were:
```
TfidfVectorizer(
    stop_words=stopwords_list,
    min_df=2,
    token_pattern=r"(?u)\b[a-zA-Z]{2,}\b",
    preprocessor=lemmatizer.lemmatize,
)
```

Stopwords were in a CSV located at `../food_stopwords.csv` and did include units and brands

Probably do not need to lemmatize, just apply that regex from token_pattern and filter out stopwords.

How to reapply in Polars?
- [X] Join list of strings (ingredients)
- [X] filter string based on regex and stopwords

In [ ]:
filtered_to_investigate.select("ingredients").to_series().list.join(separator="||")

shape: (68,)
Series: 'ingredients' [str]
[
	"2 ½  tablespoon s (18.75 g) co…
	"5 large egg yolks , room tempe…
	"Homemade pie crust or store-bo…
	"1 ¼   cup (5 ounces) all-purpo…
	"3 1/2- 4 pounds chicken drumst…
	…
	"¼ cup olive oil||¼ cup soy sau…
	"1 ½ cups all-purpose flour||¾ …
	"2  onions, finely chopped||3 c…
	"¼ cup vegetable oil||5  onions…
	"1 pound ground pork||½ pound g…
]

In [ ]:
filtered_to_investigate = filtered_to_investigate.with_columns(
    pl.col("ingredients")
    .list.join(separator="BREAK")
    .str.extract_all(
        r"(?u)\b[a-zA-Z]{2,}\b"
    )
    .alias("regex_filtered_ingredients")
)

In [ ]:
filtered_to_investigate.glimpse()

Rows: 68
Columns: 12
$ mealeon_id                       <str> 'AfricanBites-587700762275fbf6a6e2a343b27cc689317725ae2d1724cd33c6c841583afc3e', 'AfricanBites-6f62a39913dd8029cd399d4ae47b0551f94a16865a3143b5dd28664c0880596e', 'AfricanBites-fc015a5953d8811734f652ad17ba50d73f98d783350df0a95a6e2015007263f0', 'AfricanBites-2f35554786f85a304f1f5e86313f5d35730777a4f0861edf3474a914e9b7ec23', 'AfricanBites-5ca4ea56e8d49013ebd7457560a386a5e1a1059f267514b7c1dff7b9f0c78d72', 'AfricanBites-56e7fc4d3a1db457444cf4744911356514b3ac961f04976a0fb127f0ac8145be', 'AfricanBites-8e8956de6dd17820c4e5146820972193f2587d97e80ee1a754c92dce048e4f9e', 'Panlasang_Pinoy-1d186c4a4c274e42580488e652e3448aa9942642fa9e990d89d3e1894056ce78', 'Panlasang_Pinoy-b5a6e813375f4cbb399a2e68dec8f9448d64c4f01f2e5b5accd9188509875f17', 'AllRecipes-d9b8ecb976729402694fa448a53b741404ef3e10f6dd9fe2219fc6fb3fb7b038'
$ language                         <str> 'English', 'English', 'English', 'English', 'English', 'English', 'English', 'English', 'English', 'English'
$ source_id                        <str> '597818', '598753', '607516', '608647', '567371', '569017', '607562', '83413', '50747', '101422'
$ title                            <str> 'Banana Pudding', 'Tiramisu', 'Apple Pie', 'Fish and Chips', 'Huli Huli Chicken', 'Mexican Rice', 'Beef Wellington', 'Kung Pao Chicken', 'California Roll', 'Scotch Eggs'
$ origin                           <str> 'AfricanBites', 'AfricanBites', 'AfricanBites', 'AfricanBites', 'AfricanBites', 'AfricanBites', 'AfricanBites', 'Panlasang_Pinoy', 'Panlasang_Pinoy', 'AllRecipes'
$ url                              <str> 'https://www.africanbites.com/homemade-banana-pudding/', 'https://www.africanbites.com/tiramisu/', 'https://www.africanbites.com/apple-pie/', 'https://www.africanbites.com/fish-and-chips/', 'https://www.africanbites.com/huli-huli-chicken/', 'https://www.africanbites.com/oven-baked-mexican-rice/', 'https://www.africanbites.com/beef-wellington/', 'https://panlasangpinoy.com/kung-pao-chicken-recipe/', 'https://panlasangpinoy.com/how-to-make-suchi-california-roll-recipe-video/', 'https://www.allrecipes.com/recipe/101422/scotch-eggs/'
$ ingredients                <list[str]> ['2 ½  tablespoon s (18.75 g) cornstarch ', '6 tablespoons  (75 g) granulated sugar ', 'Pinch of salt ', '2 cups (480 ml) whole milk ', '½ cup  (120 ml) heavy cream', '6 large egg yolks ', '3 tablespoons   (28 g) unsalted butter , softened to room temperature ', '1 tablespoon  (13 g) pure vanilla extract  ', 'vanilla wafers  ', '4-5  large ripe firm bananas ', 'homemade whipped cream  '], ['5 large egg yolks , room temperature', '¾ cup granulated sugar', '½ cup whole milk ', '1 cup mascarpone cheese ', '1 cup espresso or very strong coffee (double for alcohol free) ', '2 tablespoons  rum (leave out for alcohol-free) ', '1 teaspoon  vanilla extract ', '½ cup coffee liqueur (leave out for alcohol-free) ', '2 tablespoons  cocoa powder , split, sweetened or unsweetened  ', '24 ladyfingers ', '2 cups homemade whipped cream  ', '1 ½ cup whipped cream ', '⅓ cup  granulated sugar', '1 teaspoon  vanilla extract ', '8  ounce  (1 cup) mascarpone cheese ', '3-4   tablespoons  cocoa powder', '1 cup  espresso or very strong coffee ', '1-2  tablespoons rum liquor (optional) ', '½ cup  marsala sweet wine  ', '24  ladyfingers or more ', '1 cup or more homemade whipped cream  (optional, for piping) '], ['Homemade pie crust or store-bought pie crust  ', '7-8 apples  (about 3 ½ pounds)', '½ cup brown sugar', '¼ cup  granulated sugar', '1 teaspoon ground cinnamon , plus more if desired', '¼ teaspoon ground nutmeg plus more if desired', '¼ teaspoon ground ginger ', '⅛ teaspoon ground allspice plus more if desired', '½ teaspoon salt', '2 tablespoons fresh lemon juice ', '2 tablespoons cold unsalted butter , divided', '3 tablespoons cornstarch', '1 large egg', '1 tablespoon heavy cream or whole milk', 'coarse sugar or turbinado sugar for sprinkling'], ['1 ¼   cup (5 ounces) all-purpose flour', '¾  cup (4 ounces) cornstarch', '2  teaspoons (6g) garlic powder', '¼ teaspoon (0.5g) cayenne pepper', '1  teaspoon (2g) paprika', '2  teaspoons (8g) baking powder', '1 ½ teaspoon (7.5g) salt', '½  teaspoon (1g) white pepper', '1 ½  cups (374g) beer', '1 ½  pound (380.39g) skinless cod fillet,  about 1 inch thick, cut into strips', '1  quart (946ml) water', 'ice', '1  tablespoon (15ml) vinegar', '2-3 russet potatoes,  about 1 1/2 pounds', 'salt and seasonings to taste'], ['3 1/2- 4 pounds chicken drumsticks', '1 cup unsweetened pineapple juice', '1/3 cup soy sauce', '1/4 cup brown sugar', '2 Tablespoons Honey', '1/4 cup ketchup', '½ Tablsespoon fresh grated ginger', '1 Tablespoon minced garlic', '1- teaspoon cumin spice', '1- teaspoon Sriracha adjust to taste', '1/2 -1 Lemon juice', '¼ cup chicken broth', 'Green onions sliced for garnish'], ['3 cups or 600 g rice , (I used Basmati)', '1 medium onion  , chopped', '14 oz can tomatoes sauce', '½ cup or 8 fl oz cooking oil', '2 tsp chicken bouillon', '2 tsp or 11.8 g salt', '1 tbsp or 6.90 g paprika', '1 tbsp or 9.84 g garlic powder', '4 cups or 946 ml chicken broth or water', '1 tsp or 2.33 g white or black pepper', '1  1/2 tsp or 3.05 cumin spice', '3/4 tsp or 2.03 chili spice or 1 minced jalapeño pepper , optional, omit if cooking for kids', '¼  cup or 2 fl oz cooking oil', '2  cups or 400 g long grain rice  , (I used Basmati)', '1 medium onion , chopped', '2  tsp or 5.60 g minced garlic', '1 tsp or 6.90 g paprika', '1 ½  tsp or 3.05 g cumin', '1 tsp chicken bouillon (replace with salt about ½ teaspoon)', '1 tsp or 5.90 g salt', '½ tsp or 1.16 g freshly ground black pepper', '¾  tsp chili or minced jalapenos  (optional)', ' 8 oz tomatoes sauce', '4 cups or 946 ml chicken broth or water', '1 tbsp  freshly chopped parsley , for garnishing'], ['1 pound (455g) mushrooms, roughly chopped', '¼ cup diced onion', '2 teaspoons (10g) minced garlic', '2 teaspoons (2g)  thyme, minced', '2 tablespoons (28g) butter or olive oil', 'salt and pepper to taste', '2 pounds (907g) center-cut beef tenderloin', 'salt and pepper', '½-1 cup (118-236ml) Dijon mustard (depending on the size of the tenderloin)', '6-8 ounces (170-226g) thinly sliced prosciutto ', '12-16 ounces (340-450g) puff pastry, thawed', 'flour for dusting  ', '1 large egg, lightly beaten (for egg wash)', '2 tablespoons (28g) butter or olive oil', '⅓ small onion, sliced or chopped', '3  cloves garlic, peeled and smashed ', '1 bay leaf', '2 sprigs fresh thyme', '½ cup (118ml) wine', '3 cups (710ml) beef stock', '1  cup (236ml) heavy cream', '2  tablespoons (30ml) Dijon mustard', 'salt and pepper to taste (optional)'], ['1 ½ lbs boneless chicken thigh diced', '1 tablespoon soy sauce', '1 tablespoon Shaoxing cooking wine', '2 teaspoons cornstarch', 'A pinch of salt', '8 pieces dried chilies', '1 tablespoon ginger  minced', '4 cloves garlic minced', '5 stems  green onions chopped', '1 zucchini diced', '1 red bell pepper  diced', '1/2 roasted peanuts', '3 tablespoons cooking oil', '2 tablespoons soy sauce', '1 tablespoon dark soy sauce', '1 tablespoon rice vinegar', '1 tablespoon honey', '2 tablespoons Shaoxing cooking wine', '1 teaspoons cornstarch', '1/2 cup chicken stock'], ['1 medium sized avocado peeled and sliced into 1/4-inch thick pieces', '4 sheets sushinori', '1/4 cup sesame seeds', '1 small cucumber peeled, seeded, and sliced in 1/8 inch thick pieces', '4 pieces crabsticks', '3 cups cooked sushi rice', '2 tbsp rice vinegar', '2 tbsp granulated sugar', '1 tsp salt'], ['1 pound bulk pork sausage', '1 tablespoon fresh parsley, chopped', '1 tablespoon grated onion', '¼ teaspoon ground cinnamon', '⅛ teaspoon ground nutmeg', '4  hard-cooked eggs, shelled', '½ cup fine, dry breadcrumbs']
$ photo_url                        <str> 'https://www.africanbites.com/wp-content/uploads/2020/04/IMG_7263-650x650.jpg', 'https://www.africanbites.com/wp-content/uploads/2020/05/IMG_0089-650x650.jpg', 'https://www.africanbites.com/wp-content/uploads/2020/11/IMG_0556-650x650.jpg', 'https://www.africanbites.com/wp-content/uploads/2021/01/IMG_0390-650x650.jpg', 'https://www.africanbites.com/wp-content/uploads/2016/07/IMG_7561-625x650.jpg', 'https://www.africanbites.com/wp-content/uploads/2014/05/Oven-Baked-Mexican-Rice-625x650.jpg', 'https://www.africanbites.com/wp-content/uploads/2020/12/IMG_0830-2-2-650x650.jpg', 'https://panlasangpinoy.com/wp-content/uploads/2024/05/Kung-Pao-Chicken-with-Rice-750x750.jpg', 'https://panlasangpinoy.com/wp-content/uploads/2009/11/CaliRollFront.jpg', 'https://www.allrecipes.com/thmb/O97thoiWu47Ofhr5CJHDU0sxZ0U=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/317815-338fb2cd53fd44b9b0038eb2f64f9fae.jpg'
$ description                      <str> 'Homemade Banana Pudding – a classic Southern no-bake dessert with decadent layers of vanilla wafers, fresh banana slices, whipped cream, and vanilla custard all made from scratch. This is a fantastic make-ahead dessert that is a hit all year round!', 'This classic Italian coffee-flavored TIRAMISU is a creamy flavorful no-bake dessert. It comes in two versions - the classic one using eggs AND a 20-minute quick version. Truly one of the best desserts you can make in your entire life!', 'Made with lightly spiced apple filling, this APPLE PIE made with the best buttery-flaky homemade pie crust is a must-have on any family occasion! Use a mix of different kinds of apples to make the best homemade pie! ', 'Perfectly seasoned tender fish fillet, encased in a light and mellow beer batter served with crispy, real potato fries. Serve these side-by-side for a great appetizer or snacks to share with your favorite game-day buddy!', 'Huli Huli Chicken - Grilled or Baked Hawaiian  Chicken Drumsticks  marinated in a sweet pineapple, ginger, garlic sauce. Sweet, Sticky and Sweet.', "Tender and amazingly delicious rice recipe that's perfect for entertaining or for regular days. It tastes even better than those you pay at restaurants. Minimal prep time with optimal result – comes in 2 methods for your convenience!", 'Juicy, tender, and showstopping beef tenderloin wrapped in prosciutto slices, mushroom duxelles, and a flaky crust. The wine-infused sauce takes it over the top. Serving this beauty at your next gathering will get you rave reviews!', 'No description', 'No description', 'Cut in halves or quarters for appetizers or serve whole as a meal. Serve with sour cream along side.'

In [ ]:
# lets load the food_stopwords.csv into a polars dataframe and extract into a set
with open("../food_stopwords.txt") as f:
    for line in f:
        food_stopwords = line.replace('"', '').split(",")

food_stopwords

['spare',
 'pernod',
 'snow',
 'hollowed',
 'bonein',
 'for',
 'pans',
 'knorr',
 'eighths',
 'approximately',
 'kitchen',
 'canner',
 'crosswise',
 'use',
 'fully',
 'parts',
 'best®',
 'filtered',
 'freshepazote',
 'tasting',
 'flavoring',
 'blended',
 'plump',
 'gold®',
 'percent',
 'insert',
 'shreds',
 'smaller',
 'wiped',
 'ragu',
 'preparation',
 'thirty',
 'king',
 'hinged',
 'half',
 'needed',
 'elixir',
 'starter',
 'nestle',
 'naturally',
 'leafed',
 'attachment',
 'leaved',
 'foil',
 'ROTEL',
 'karo',
 'omitting',
 'with',
 'cracks',
 'cube',
 'precooked',
 'scrubbed',
 'coins',
 'area',
 'earth balance',
 'johnsonville',
 'farm',
 'flavor',
 'online',
 'country bob',
 'jumbo',
 'sticky',
 'crescent',
 'eighteen',
 'boil',
 'ready',
 'superfine',
 'assorted',
 'imported',
 'style',
 'micro',
 'angelhair',
 'preserved',
 'freeze',
 'clark',
 'hon',
 'ripe',
 'grated',
 'jellied',
 'malt-o-meal',
 'cups',
 'handheld',
 'platters',
 'tree',
 'unsalted',
 'store-bought',
 'pickled',
 'lump',
 'reserve',
 'Franks',
 'prefer',
 'roma',
 'washed',
 'catalogue',
 'usually',
 'soften',
 'native',
 'unsweetened',
 'heavy',
 'indonesian',
 'slivered',
 'pits',
 'cracked',
 'de',
 'made',
 'etc',
 'bench',
 'cupsturkey',
 'tray',
 'digital',
 'degrees',
 'together',
 'case',
 'best',
 'unripe',
 'appetizer',
 'kosher',
 'girl',
 'premium',
 'finely',
 'liners',
 'manischewitz',
 'about',
 'produce',
 'hostess',
 'slightly',
 'tablepoons',
 'scaled',
 'filling',
 'recommend',
 'streaky',
 'resealable',
 "kellogg's",
 'excess',
 'piece',
 'steaming',
 'diagonally',
 'body',
 'visible',
 'liter',
 'keep',
 'moistening',
 'petals',
 'pressure',
 'ribbon',
 'transparent',
 'fed',
 'sized',
 'electric',
 'heated',
 'oblong',
 'pack',
 'seasonally',
 'glitter',
 'william',
 'instant',
 'active',
 'release',
 'remaining',
 'perfect',
 'damson',
 'juicy',
 'twine',
 'gerber',
 'stirred',
 'middle',
 'cast',
 'pints',
 'special',
 'loosely',
 'torch',
 'commonly',
 'instructions',
 'product',
 'goya',
 'unconverted',
 'loose',
 'breasts',
 'in',
 'handling',
 'expose',
 'pkg',
 'ton',
 'scissors',
 'version',
 'empty',
 'slicing',
 'gourmet',
 'bought',
 'del',
 'sorted',
 'ha',
 'partially',
 'picked',
 'aluminum',
 'mildly',
 'quill',
 'cupsfresh',
 'RedHot',
 'rinsed',
 'inner',
 'shaped',
 'places',
 'exotic',
 'powdery',
 'springs',
 'molds',
 'cross',
 'terra',
 'handle',
 'oriental',
 'becomes',
 'crust',
 'reducedfat',
 'bottoms',
 'mexico',
 'hard',
 'high',
 'yoplait®',
 'hellmann',
 'TM',
 'wrapping',
 'Boston',
 'directions',
 'thinning',
 'snipped',
 'spices',
 'fresh',
 'diced',
 'waxed',
 'light',
 'deveined',
 'chopped',
 'pullman',
 'leftover',
 'valrhona',
 'medium',
 'little smokies',
 'mrs',
 'canal',
 'joints',
 'order',
 'jello',
 'skillet',
 'side',
 'forming',
 'crumbled',
 'sure',
 'unshelled',
 'available',
 'securely',
 'bayou blast',
 'jarred',
 'recipelink',
 'knot',
 'mam',
 'perforated',
 'dim',
 'spiced',
 'point',
 'hand',
 'omit',
 'edges',
 'hamburger helper',
 'st. germain',
 'shilling',
 'wooden',
 'wineglass',
 'tel',
 'grind',
 'underripe',
 'mixer',
 'RedHot®',
 'rolled',
 'accompaniment',
 'good',
 'Masterpiece',
 'spoon',
 'Paso',
 'cm',
 'dish',
 'drain',
 'minces',
 'retain',
 'st',
 'flavored',
 "mccormick's",
 'petits',
 'calorie',
 'lo',
 'crisp',
 'metal',
 'prime',
 'instacure',
 'sweetness',
 'edge',
 'greased',
 'paintbrush',
 'semi',
 'puree',
 'spoons',
 'quick',
 'briefly',
 'west',
 'whipping',
 'corkscrew',
 'ricer',
 'parchment',
 'excellence',
 'super',
 'charlotte',
 'lexington',
 'tube',
 'authentic',
 'less',
 'baster',
 'shape',
 'minus',
 'remove',
 'racks',
 'india',
 'removed',
 'springform',
 'semidried',
 'milled',
 'chiffonade',
 'segment',
 'hearts',
 'ingredients',
 'holiday',
 'heads',
 'v8',
 'maytag',
 'referred',
 'quartered',
 'square',
 'twice',
 'come',
 'gas',
 'cupspanko',
 'outer',
 'extra',
 'heatproof',
 'thick-cut',
 'dampened',
 'pleated',
 'similar',
 'dash',
 'basting',
 'desert',
 'tips',
 'process',
 'tabasco',
 'bitesized',
 'kettle',
 'hook',
 'litres',
 'appropriate',
 'pop',
 'bitesize',
 'log',
 'slice',
 'westphalian',
 'nutritional',
 'lightly',
 'island',
 'prepare',
 'doone',
 'leveling',
 'unhusked',
 'round',
 'giant',
 'of',
 'distilled',
 'preferred',
 'quills',
 'stainless',
 'morton',
 'rolls',
 'slather',
 'heat',
 'scale',
 'favorite',
 'gutted',
 'four',
 'Bibb',
 'number',
 'john',
 'winter',
 'thermometer',
 'plane',
 'broil',
 'seasoned',
 'alternatively',
 'angled',
 'color',
 'assembling',
 'pulsed',
 'company',
 'holy',
 'mori-nu',
 'draining',
 'links',
 'cure',
 'late',
 'self',
 'near',
 'shucked',
 'well',
 'chilled',
 'attached',
 'poaching',
 'stovetop',
 'serve',
 'whole',
 'foamy',
 'hold',
 'strong',
 'portions',
 'large',
 'El',
 'minced',
 'plant',
 'goes',
 "bird's eye",
 'toasted',
 'unflavored',
 'laughing cow',
 'crock',
 'least',
 'omega',
 'grate',
 'pure',
 'thread',
 'coloring',
 'food',
 'pickling',
 'curly',
 'chunk',
 'separated',
 'peeled',
 'machine',
 'used',
 'spicy',
 'imitation',
 'stores',
 'zester',
 'rub',
 'great',
 'peel',
 'trimmed',
 'fragments',
 'scoop',
 'disposable',
 'scout',
 'spears',
 'vary',
 'restaurant',
 'angel',
 'handful',
 'pit',
 'oounces',
 'strained',
 'beards',
 'stems',
 'thinly',
 'extra sharp',
 'health',
 'substitutes',
 'around',
 'farms',
 'sweep',
 'presliced',
 'charcoal',
 'pepperidge',
 'couple',
 'scharffen',
 'rectangles',
 'bakeware',
 'extrasharp',
 'sea',
 'tiny',
 'Italianstyle',
 'video',
 'nontoxic',
 'combination',
 'untreated',
 'plastic',
 '¼',
 'hours',
 'often',
 'without',
 'cans',
 'delicious',
 'fishmonger',
 'Japanese',
 'pick',
 'low',
 'prevent',
 'swanson',
 'selfrising',
 'leveled',
 'little',
 'sun-maid',
 'northern',
 'microplane',
 'topping',
 'semisoft',
 'carbon',
 'insta',
 'uniform',
 'moisture',
 'wedges',
 'ultra',
 'eyed',
 'peasant',
 'ovenproof',
 'halves',
 'boneless',
 'ordered',
 'Italian',
 'skirt',
 'attachments',
 "frank's®",
 'making',
 'makes',
 'called',
 'famous',
 'spray',
 'mission',
 'long',
 'dark',
 'oz',
 'varieties',
 'packed',
 'pulp',
 'single',
 'crock®',
 'interior',
 'contains',
 'sieve',
 'farmer',
 'pasteurized',
 'part',
 'supermarket',
 'optional',
 'slim',
 'stick',
 'knife',
 'C',
 'dessert',
 'ziploc bag',
 'plumped',
 'lite',
 'leafy',
 'request',
 'at',
 'done',
 'melt',
 'heavily',
 'stuffed',
 'quarts',
 'brushed',
 'preheat',
 'weights',
 'slotted',
 'as',
 'problem',
 'from',
 'hershey carb alternatives',
 'family',
 'stuck',
 'herbs',
 'avoid',
 'silver',
 'flying',
 'buy',
 'chopsticks',
 'fit',
 'hulled',
 'jell',
 'tepid',
 'lengths',
 'gloves',
 'griddle',
 'manual',
 'tablet',
 'mild',
 "eggland's best",
 'debearded',
 'strands',
 'freshest',
 'coin',
 'pillsbury™',
 'strings',
 'nationwide',
 'combine',
 'dover',
 'grill',
 'scored',
 'waxy',
 'spider',
 'watch',
 'dense',
 'snickers',
 'end',
 'pulled',
 'opening',
 "hunt's",
 'cracker barrel',
 'rough',
 'ounce',
 'English',
 'diet',
 'decorations',
 'a',
 'ga',
 'old',
 'larger',
 'completely',
 'plenty',
 "Frank's",
 'dessicated',
 'slit',
 'persian',
 'Thai',
 'ungreased',
 'wwwyear',
 'frozen',
 'brewed',
 'petit',
 'fantastic foods',
 'which',
 'colored',
 'wilted',
 'com',
 'qts',
 'need',
 'inch',
 'fourths',
 'canning',
 'full',
 'stewed',
 'mt',
 'tied',
 'small',
 'flexible',
 'fan',
 "betty crocker's",
 'cooking',
 'polished',
 'pattern',
 'approx',
 'read',
 'tin',
 'ceramic',
 'yield',
 'into',
 'sturdy',
 'hour',
 'aged',
 'surface',
 'decorative',
 'gallons',
 'saucepan',
 'iron',
 'true',
 'aroma',
 'strip',
 'mitts',
 'calore-wise',
 'power',
 'chickenflavored',
 'width',
 'amazon',
 'old el paso',
 'Chacheres',
 'big',
 'thickness',
 'shred',
 'juiced',
 "bird's",
 'eckrich',
 'quality',
 'substitute',
 'club',
 'foam',
 'containers',
 'triple',
 'scraps',
 'cleaver',
 'hidden valley',
 'fried',
 'flavorful',
 'more',
 'ahead',
 'tbs',
 'save',
 'separator',
 'party',
 'crusty',
 'states',
 'right',
 'latin',
 'ram',
 'damp',
 'moderately',
 'needlenose',
 'real',
 'wide',
 'Chobani',
 'unsprayed',
 'American',
 'shopping',
 'passover',
 'hammer',
 'bottomed',
 'scales',
 'teaspoons',
 'firmly',
 'recipe',
 'bunch',
 '½',
 'thickcut',
 'labeled',
 'mediterranean',
 'pods',
 'quarters',
 'trans',
 'combined',
 'wheel',
 'freshly',
 'away',
 'hollow',
 'peeling',
 'unrolled',
 '*available in most target stores',
 'thickest',
 'follows',
 "land o' lakes",
 'nine',
 'adjoining',
 'firm',
 'segments',
 'mrs. dash',
 'spooned',
 'kernels',
 'bobolis',
 'ten',
 'pretty',
 'overripe',
 'unavailable',
 'progresso™',
 'generously',
 'mix',
 'herbes',
 'unhulled',
 'scoops',
 'link',
 'undrained',
 'look',
 'kilogram',
 'moist',
 'terrine',
 'inches',
 'smokie',
 'herbed',
 'person',
 'brands',
 'uwajimaya',
 'juice',
 'wing',
 'breast',
 'content',
 'dusting',
 'across',
 'squeeze',
 'lbs',
 'peppered',
 'necessary',
 'perilla',
 'scrambled',
 'defatted',
 'bell®',
 '⅔',
 'granules',
 'would',
 'fitting',
 'beaten',
 'cubes',
 'progresso',
 'rim',
 'carnation',
 'eastern',
 'grains',
 'picks',
 'laver',
 'kikkoman',
 'diagonal',
 'prince',
 'count',
 'milliliter',
 'whisk',
 'third',
 'per',
 'towels',
 'popped',
 'pepperidge farm',
 'secrets®',
 'ingredient',
 'gem',
 'tying',
 'somewhat',
 'amount',
 'blender',
 'fairly',
 'seasonal',
 'giada de laurentiis genovese',
 'rapid',
 'needles',
 'kirby',
 'trumpet',
 'sizes',
 'terry',
 'toblerone',
 'times',
 'canned',
 'v8 fusion',
 'hot',
 'work',
 'lot',
 'fun',
 'lebanese',
 'glove',
 'reconstituted',
 'jars',
 'wings',
 'press',
 'along',
 'nests',
 'portuguese',
 'also',
 'plate',
 'unpopped',
 'sifting',
 'nestl',
 'igourmet',
 'extralarge',
 'softer',
 'charred',
 'discarding',
 'like',
 'leave',
 'many',
 'discarded',
 'bowl',
 'eighth',
 'stone',
 'betty crocker',
 'mini',
 'may',
 'burner',
 'cards',
 'tossed',
 'edward',
 'prebaked',
 'pat',
 'thawed',
 'herb',
 'bragg',
 "annie's",
 'wild',
 'sub',
 'variety',
 'coarsely',
 'hormel',
 'brought',
 'grater',
 'stop',
 'diamond',
 'street',
 'plain',
 'edged',
 'bertolli®',
 'apart',
 'tongs',
 'French',
 'skewers',
 'leathery',
 'mixing',
 'following',
 'balls',
 'purchased',
 'coils',
 'ends',
 'grainy',
 'handles',
 'fluid',
 'rather',
 'split',
 'course',
 'ever',
 'sweet',
 'Hunts',
 '®',
 'cold',
 'pulverized',
 'thigh',
 'simmer',
 'rustique',
 'key',
 'fire',
 'bite',
 'sponge',
 'paper',
 'creamstyle',
 'colman',
 'gently',
 'thin',
 'thoroughly',
 'milnot',
 'sectioned',
 'baskets',
 'crystal light',
 'scant',
 'cloth',
 'knuckle',
 'adjustable',
 'uncle',
 'glass',
 'segmented',
 'submerged',
 'vitamin',
 'splash',
 'cupmirin',
 'streaming',
 'drops',
 'storebought',
 'acting',
 'and',
 'branch',
 'mortar',
 '⅓',
 'jarlsberg',
 'scooped',
 'tip',
 'using',
 'unsifted',
 'tsp',
 'call',
 'rice-a-roni',
 'feet',
 'pillsbury plus',
 'ruler',
 'shards',
 'cooker',
 'grating',
 'unless',
 'bright',
 'depending',
 'gold medal',
 'grinds',
 'pitted',
 'weighing',
 'stem',
 'open',
 'unsulfured',
 'Hot',
 'equivalent',
 '14.5',
 'stalk',
 'mash',
 'stiffly',
 'see',
 'latter',
 'almost',
 'condiment',
 'specialty',
 'credit',
 'perfectly',
 'lengthwise',
 'dredging',
 'uncooked',
 'softened',
 'slender',
 'another',
 'baker',
 'n',
 "n't",
 'tubular',
 'knorr®',
 'desiccated',
 'oscar mayer',
 'aisle',
 'stolichnaya',
 'spots',
 'gallon',
 'will',
 'spatulas',
 'feathers',
 ...]

In [ ]:
filtered_to_investigate = filtered_to_investigate.with_columns(
    pl.col("ingredients")
    .list.join(separator="|")
    .str.to_lowercase()
    .str.extract_all(
        r"(?u)\b[a-zA-Z]{2,}\b"
    )
    .list.set_difference(food_stopwords)
    .alias("regex_filtered_ingredients")
)

In [ ]:
filtered_to_investigate.select("regex_filtered_ingredients").glimpse()

Rows: 68
Columns: 1
$ regex_filtered_ingredients <list[str]> ['cream', 'cornstarch', 'vanilla', 'milk', 'sugar', 'bananas', 'extract', 'salt', 'egg', 'butter', 'wafers'], ['liquor', 'egg', 'out', 'rum', 'wine', 'ladyfingers', 'vanilla', 'sugar', 'cream', 'milk', 'mascarpone', 'cheese', 'espresso', 'cocoa', 'alcohol', 'marsala', 'coffee', 'liqueur', 'extract'], ['sprinkling', 'pie', 'turbinado', 'butter', 'salt', 'milk', 'apples', 'ginger', 'cream', 'nutmeg', 'brown', 'sugar', 'if', 'cornstarch', 'lemon', 'cinnamon', 'allspice', 'egg'], ['russet', 'vinegar', 'water', 'beer', 'flour', 'cornstarch', 'potatoes', 'garlic', 'fillet', 'ice', 'cayenne', 'pepper', 'paprika', 'baking', 'salt', 'white', 'cod'], ['sriracha', 'chicken', 'drumsticks', 'lemon', 'spice', 'pineapple', 'broth', 'soy', 'sauce', 'brown', 'sugar', 'garlic', 'honey', 'ketchup', 'tablsespoon', 'onions', 'cumin', 'ginger', 'adjust', 'green'], ['jalapenos', 'parsley', 'rice', 'replace', 'basmati', 'chili', 'onion', 'if', 'water', 'spice', 'tomatoes', 'sauce', 'kids', 'black', 'broth', 'oil', 'pepper', 'chicken', 'bouillon', 'salt', 'cumin', 'paprika', 'garlic', 'white'], ['puff', 'mushrooms', 'tenderloin', 'wine', 'mustard', 'cream', 'onion', 'stock', 'bay', 'garlic', 'thyme', 'dijon', 'butter', 'egg', 'olive', 'oil', 'salt', 'leaf', 'pepper', 'flour', 'on', 'prosciutto', 'center', 'pastry', 'beef'], ['garlic', 'oil', 'chicken', 'pepper', 'stock', 'bell', 'soy', 'sauce', 'shaoxing', 'rice', 'wine', 'peanuts', 'cornstarch', 'zucchini', 'honey', 'salt', 'red', 'green', 'chilies', 'ginger', 'vinegar', 'onions'], ['crabsticks', 'salt', 'avocado', 'vinegar', 'sesame', 'rice', 'sushi', 'sushinori', 'cucumber', 'sugar', 'seeds'], ['nutmeg', 'onion', 'pork', 'sausage', 'cinnamon', 'eggs', 'parsley', 'shelled', 'breadcrumbs']

Look at recipes, see if ingredients make sense with a canonical version online

In [ ]:
with pl.Config(fmt_table_cell_list_len=20,
               fmt_str_lengths=1000,
               set_tbl_width_chars=70
               ):
    print(filtered_to_investigate.select(["title", "mealeon_id","regex_filtered_ingredients"])[0:5])

shape: (5, 3)
┌───────────────────┬────────────────────────┬───────────────────────┐
│ title             ┆ mealeon_id             ┆ regex_filtered_ingred │
│ ---               ┆ ---                    ┆ ients                 │
│ str               ┆ str                    ┆ ---                   │
│                   ┆                        ┆ list[str]             │
╞═══════════════════╪════════════════════════╪═══════════════════════╡
│ Banana Pudding    ┆ AfricanBites-587700762 ┆ ["cream",             │
│                   ┆ 275fbf6a6e2a343b27cc68 ┆ "cornstarch",         │
│                   ┆ 9317725ae2d1724cd33c6c ┆ "vanilla", "milk",    │
│                   ┆ 841583afc3e            ┆ "sugar", "bananas",   │
│                   ┆                        ┆ "extract", "salt",    │
│                   ┆                        ┆ "egg", "butter",      │
│                   ┆                        ┆ "wafers"]             │
│ Tiramisu          ┆ AfricanBites-6f62a3991 ┆ ["liquor", "egg",     │
│                   ┆ 3dd8029cd399d4ae47b055 ┆ "out", "rum", "wine", │
│                   ┆ 1f94a16865a3143b5dd286 ┆ "ladyfingers",        │
│                   ┆ 64c0880596e            ┆ "vanilla", "sugar",   │
│                   ┆                        ┆ "cream", "milk",      │
│                   ┆                        ┆ "mascarpone",         │
│                   ┆                        ┆ "cheese", "espresso", │
│                   ┆                        ┆ "cocoa", "alcohol",   │
│                   ┆                        ┆ "marsala", "coffee",  │
│                   ┆                        ┆ "liqueur", "extract"] │
│ Apple Pie         ┆ AfricanBites-fc015a595 ┆ ["sprinkling", "pie", │
│                   ┆ 3d8811734f652ad17ba50d ┆ "turbinado",          │
│                   ┆ 73f98d783350df0a95a6e2 ┆ "butter", "salt",     │
│                   ┆ 015007263f0            ┆ "milk", "apples",     │
│                   ┆                        ┆ "ginger", "cream",    │
│                   ┆                        ┆ "nutmeg", "brown",    │
│                   ┆                        ┆ "sugar", "if",        │
│                   ┆                        ┆ "cornstarch",         │
│                   ┆                        ┆ "lemon", "cinnamon",  │
│                   ┆                        ┆ "allspice", "egg"]    │
│ Fish and Chips    ┆ AfricanBites-2f3555478 ┆ ["russet", "vinegar", │
│                   ┆ 6f85a304f1f5e86313f5d3 ┆ "water", "beer",      │
│                   ┆ 5730777a4f0861edf3474a ┆ "flour",              │
│                   ┆ 914e9b7ec23            ┆ "cornstarch",         │
│                   ┆                        ┆ "potatoes", "garlic", │
│                   ┆                        ┆ "fillet", "ice",      │
│                   ┆                        ┆ "cayenne", "pepper",  │
│                   ┆                        ┆ "paprika", "baking",  │
│                   ┆                        ┆ "salt", "white",      │
│                   ┆                        ┆ "cod"]                │
│ Huli Huli Chicken ┆ AfricanBites-5ca4ea56e ┆ ["sriracha",          │
│                   ┆ 8d49013ebd7457560a386a ┆ "chicken",            │
│                   ┆ 5e1a1059f267514b7c1dff ┆ "drumsticks",         │
│                   ┆ 7b9f0c78d72            ┆ "lemon", "spice",     │
│                   ┆                        ┆ "pineapple", "broth", │
│                   ┆                        ┆ "soy", "sauce",       │
│                   ┆                        ┆ "brown", "sugar",     │
│                   ┆                        ┆ "garlic", "honey",    │
│                   ┆                        ┆ "ketchup",            │
│                   ┆                        ┆ "tablsespoon",        │
│                   ┆                        ┆ "onions", "cumin",    │
│                   ┆                        ┆ "ginger", "adjust",   │
│                   ┆                        ┆ "green"]              │
└───────────────────┴────────────────────────┴───────────────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=20,
               fmt_str_lengths=1000,
               set_tbl_width_chars=70
               ):
    print(filtered_to_investigate.select(["title", "mealeon_id","regex_filtered_ingredients"])[5:10])

shape: (5, 3)
┌──────────────────┬────────────────────────┬────────────────────────┐
│ title            ┆ mealeon_id             ┆ regex_filtered_ingredi │
│ ---              ┆ ---                    ┆ ents                   │
│ str              ┆ str                    ┆ ---                    │
│                  ┆                        ┆ list[str]              │
╞══════════════════╪════════════════════════╪════════════════════════╡
│ Mexican Rice     ┆ AfricanBites-56e7fc4d3 ┆ ["jalapenos",          │
│                  ┆ a1db457444cf4744911356 ┆ "parsley", "rice",     │
│                  ┆ 514b3ac961f04976a0fb12 ┆ "replace", "basmati",  │
│                  ┆ 7f0ac8145be            ┆ "chili", "onion",      │
│                  ┆                        ┆ "if", "water",         │
│                  ┆                        ┆ "spice", "tomatoes",   │
│                  ┆                        ┆ "sauce", "kids",       │
│                  ┆                        ┆ "black", "broth",      │
│                  ┆                        ┆ "oil", "pepper",       │
│                  ┆                        ┆ "chicken", "bouillon", │
│                  ┆                        ┆ … "white"]             │
│ Beef Wellington  ┆ AfricanBites-8e8956de6 ┆ ["puff", "mushrooms",  │
│                  ┆ dd17820c4e514682097219 ┆ "tenderloin", "wine",  │
│                  ┆ 3f2587d97e80ee1a754c92 ┆ "mustard", "cream",    │
│                  ┆ dce048e4f9e            ┆ "onion", "stock",      │
│                  ┆                        ┆ "bay", "garlic",       │
│                  ┆                        ┆ "thyme", "dijon",      │
│                  ┆                        ┆ "butter", "egg",       │
│                  ┆                        ┆ "olive", "oil",        │
│                  ┆                        ┆ "salt", "leaf",        │
│                  ┆                        ┆ "pepper", … "beef"]    │
│ Kung Pao Chicken ┆ Panlasang_Pinoy-1d186c ┆ ["garlic", "oil",      │
│                  ┆ 4a4c274e42580488e652e3 ┆ "chicken", "pepper",   │
│                  ┆ 448aa9942642fa9e990d89 ┆ "stock", "bell",       │
│                  ┆ d3e1894056ce78         ┆ "soy", "sauce",        │
│                  ┆                        ┆ "shaoxing", "rice",    │
│                  ┆                        ┆ "wine", "peanuts",     │
│                  ┆                        ┆ "cornstarch",          │
│                  ┆                        ┆ "zucchini", "honey",   │
│                  ┆                        ┆ "salt", "red",         │
│                  ┆                        ┆ "green", "chilies", …  │
│                  ┆                        ┆ "onions"]              │
│ California Roll  ┆ Panlasang_Pinoy-b5a6e8 ┆ ["crabsticks", "salt", │
│                  ┆ 13375f4cbb399a2e68dec8 ┆ "avocado", "vinegar",  │
│                  ┆ f9448d64c4f01f2e5b5acc ┆ "sesame", "rice",      │
│                  ┆ d9188509875f17         ┆ "sushi", "sushinori",  │
│                  ┆                        ┆ "cucumber", "sugar",   │
│                  ┆                        ┆ "seeds"]               │
│ Scotch Eggs      ┆ AllRecipes-d9b8ecb9767 ┆ ["nutmeg", "onion",    │
│                  ┆ 29402694fa448a53b74140 ┆ "pork", "sausage",     │
│                  ┆ 4ef3e10f6dd9fe2219fc6f ┆ "cinnamon", "eggs",    │
│                  ┆ b3fb7b038              ┆ "parsley", "shelled",  │
│                  ┆                        ┆ "breadcrumbs"]         │
└──────────────────┴────────────────────────┴────────────────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=20,
               fmt_str_lengths=200,
               set_tbl_width_chars=50
               ):
    print(filtered_to_investigate.select(["title", "mealeon_id","regex_filtered_ingredients"])[10:15])

shape: (5, 3)
┌──────────────┬────────────────┬────────────────┐
│ title        ┆ mealeon_id     ┆ regex_filtered │
│ ---          ┆ ---            ┆ _ingredients   │
│ str          ┆ str            ┆ ---            │
│              ┆                ┆ list[str]      │
╞══════════════╪════════════════╪════════════════╡
│ Tiramisu     ┆ AllRecipes-867 ┆ ["cookies",    │
│              ┆ b4f3b539b381fb ┆ "egg",         │
│              ┆ 9f35252402fc14 ┆ "cheese",      │
│              ┆ efc9d6fcc64353 ┆ "rum",         │
│              ┆ 089959ac159372 ┆ "white",       │
│              ┆ a8199          ┆ "sugar",       │
│              ┆                ┆ "milk",        │
│              ┆                ┆ "ladyfinger",  │
│              ┆                ┆ "cocoa",       │
│              ┆                ┆ "cream",       │
│              ┆                ┆ "coffee",      │
│              ┆                ┆ "vanilla",     │
│              ┆                ┆ "extract",     │
│              ┆                ┆ "mascarpone"]  │
│ Pozole       ┆ AllRecipes-cac ┆ ["avocado",    │
│              ┆ 0d29872bd9f49d ┆ "chicken",     │
│              ┆ 34d8c9eac41a38 ┆ "oil",         │
│              ┆ 06929420f84e36 ┆ "onion",       │
│              ┆ b8e579c3bce939 ┆ "white",       │
│              ┆ cdc7b          ┆ "lime",        │
│              ┆                ┆ "pork",        │
│              ┆                ┆ "tenderloin",  │
│              ┆                ┆ "salt",        │
│              ┆                ┆ "radishes",    │
│              ┆                ┆ "hominy",      │
│              ┆                ┆ "pepper",      │
│              ┆                ┆ "broth",       │
│              ┆                ┆ "garlic",      │
│              ┆                ┆ "lettuce",     │
│              ┆                ┆ "stock",       │
│              ┆                ┆ "water",       │
│              ┆                ┆ "black",       │
│              ┆                ┆ "cilantro",    │
│              ┆                ┆ "sodium"]      │
│ Pierogies    ┆ AllRecipes-b81 ┆ ["butter",     │
│              ┆ 16cc920cd9d916 ┆ "flour",       │
│              ┆ cd196927ad2af1 ┆ "sour",        │
│              ┆ 062785cdaa3d3b ┆ "cream",       │
│              ┆ 4fc3e997ee86fd ┆ "onions",      │
│              ┆ 75c84          ┆ "potatoes"]    │
│ Carnitas     ┆ BBCFood-6d6cc1 ┆ ["cinnamon",   │
│              ┆ 8dadaffa5ea101 ┆ "pork",        │
│              ┆ 94b59aa6e310d3 ┆ "shoulder",    │
│              ┆ 4b1f713756d0b5 ┆ "cola",        │
│              ┆ 28cc57c5e61d92 ┆ "thyme",       │
│              ┆ e3             ┆ "oregano",     │
│              ┆                ┆ "paprika",     │
│              ┆                ┆ "brown",       │
│              ┆                ┆ "sugar",       │
│              ┆                ┆ "stock",       │
│              ┆                ┆ "vegetable",   │
│              ┆                ┆ "oil",         │
│              ┆                ┆ "olive",       │
│              ┆                ┆ "cumin",       │
│              ┆                ┆ "lard",        │
│              ┆                ┆ "onion",       │
│              ┆                ┆ "butter",      │
│              ┆                ┆ "salt",        │
│              ┆                ┆ "garlic", …    │
│              ┆                ┆ "mustard"]     │
│ Cacio e pepe ┆ BBCFood-11015d ┆ ["spaghetti",  │
│              ┆ e4db20e53dcda0 ┆ "black",       │
│              ┆ 035673dfdbeca3 ┆ "pecorino",    │
│              ┆ 55d2a1d37d71f1 ┆ "pepper",      │
│              ┆ 3d5fe5ea7ccca0 ┆ "salt"]        │
│              ┆ 2d             ┆                │
└──────────────┴────────────────┴────────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(["title", "mealeon_id","regex_filtered_ingredients"])[15:20])

shape: (5, 3)
┌────────────────┬───────────────┬───────────────┐
│ title          ┆ mealeon_id    ┆ regex_filtere │
│ ---            ┆ ---           ┆ d_ingredients │
│ str            ┆ str           ┆ ---           │
│                ┆               ┆ list[str]     │
╞════════════════╪═══════════════╪═══════════════╡
│ Cannoli        ┆ BBCFood-d59ab ┆ ["orange",    │
│                ┆ 715a7f6f00221 ┆ "mascarpone", │
│                ┆ 55b1149e4e059 ┆ "flour",      │
│                ┆ b0497fd790993 ┆ "vegetable",  │
│                ┆ fb11f1795b901 ┆ "only",       │
│                ┆ cae8f97       ┆ "cinnamon",   │
│                ┆               ┆ "ricotta",    │
│                ┆               ┆ "chocolate",  │
│                ┆               ┆ "caster",     │
│                ┆               ┆ "sugar",      │
│                ┆               ┆ "wine", "bica │
│                ┆               ┆ rbonate",     │
│                ┆               ┆ "zest",       │
│                ┆               ┆ "soda",       │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "marsala",    │
│                ┆               ┆ "egg"]        │
│ Tiramisu       ┆ BBCFood-c6b95 ┆ ["finger",    │
│                ┆ 81aa49ee6b0cc ┆ "marsala",    │
│                ┆ 3f686f58cfd12 ┆ "eggs",       │
│                ┆ 4c395284cc46d ┆ "cocoa",      │
│                ┆ fcde5bc931982 ┆ "caster",     │
│                ┆ 975ee15       ┆ "sugar",      │
│                ┆               ┆ "mascarpone", │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "savoiardi",  │
│                ┆               ┆ "cream",      │
│                ┆               ┆ "espresso",   │
│                ┆               ┆ "coffee",     │
│                ┆               ┆ "biscuits"]   │
│ Chicken tikka  ┆ BBCFood-0a7c8 ┆ ["turmeric",  │
│ masala         ┆ 10d7b7c99ae72 ┆ "you",        │
│                ┆ 8f9a2deff1434 ┆ "chicken",    │
│                ┆ 0edb099949f20 ┆ "stock",      │
│                ┆ fed75a8083c29 ┆ "ginger",     │
│                ┆ ca83aab       ┆ "only",       │
│                ┆               ┆ "lemon",      │
│                ┆               ┆ "tikka",      │
│                ┆               ┆ "masala",     │
│                ┆               ┆ "curry",      │
│                ┆               ┆ "paste",      │
│                ┆               ┆ "cumin",      │
│                ┆               ┆ "yoghurt",    │
│                ┆               ┆ "vegetable",  │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "ghee",       │
│                ┆               ┆ "coriander",  │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "cinnamon",   │
│                ┆               ┆ "how",        │
│                ┆               ┆ "cardamom",   │
│                ┆               ┆ "on", "it",   │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "garam",      │
│                ┆               ┆ "cayenne",    │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "water",      │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "tomatoes"]   │
│ Beef           ┆ BBCFood-3aa95 ┆ ["butter",    │
│ Wellington     ┆ 07e04707431ec ┆ "egg",        │
│                ┆ 512662444ef60 ┆ "vegetable",  │
│                ┆ 2910c6c0ecc99 ┆ "oil",        │
│                ┆ 7de7ea2067299 ┆ "shallot",    │
│                ┆ 85c5c08       ┆ "peelings",   │
│                ┆               ┆ "madeira",    │
│                ┆               ┆ "chestnut",   │
│                ┆               ┆ "mushrooms",  │
│                ┆               ┆ "chicken",    │
│                ┆               ┆ "cream",      │
│                ┆               ┆ "mandoline",  │
│                ┆               ┆ "potatoes",   │
│                ┆               ┆ "fry",        │
│                ┆               ┆ "beef",       │
│                ┆               ┆ "fillet",     │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "port",       │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "clove",      │
│                ┆               ┆ "you",        │
│                ┆               ┆ "stock",      │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "brine",      │
│                ┆               ┆ "truffle",    │
│                ┆               ┆ "puff",       │
│                ┆               ┆ "pastry",     │
│                ┆               ┆ "on", "veal"] │
│ Fish and chips ┆ BBCFood-adcbf ┆ ["beef",      │
│                ┆ ceaa8636f83ff ┆ "dripping",   │
│                ┆ 8866d44bc7a44 ┆ "piper",      │
│                ┆ 385c71250d73d ┆ "oil", "are", │
│                ┆ 427c08dbe345e ┆ "fridge",     │
│                ┆ 4127143       ┆ "how", "is",  │
│                ┆               ┆ "you",        │
│                ┆               ┆ "hungry",     │
│                ┆               ┆ "tail",       │
│                ┆               ┆ "fish",       │
│                ┆               ┆ "black",      │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "on", "far",  │
│                ┆               ┆ "floury",     │
│                ┆               ┆ "flavour",    │
│                ┆               ┆ "but",        │
│                ┆               ┆ "sunflower",  │
│                ┆               ┆ "vegetable",  │
│                ┆               ┆ "flour",      │
│                ┆               ┆ "lager",      │
│                ┆               ┆ "just",       │
│                ┆               ┆ "maris",      │
│                ┆               ┆ "desiree",    │
│                ┆               ┆ "raising",    │
│                ┆               ┆ "cod",        │
│                ┆               ┆ "haddock",    │
│                ┆               ┆ "fillets",    │
│                ┆               ┆ "taken",      │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "than",       │
│                ┆               ┆ "potatoes"]   │
└────────────────┴───────────────┴───────────────┘

| title (str) | mealeon_id (str) | reference_url (str) | passable (y/n) |
│ Banana Pudding | AfricanBites-587700762275fbf6a6e2a343b27cc689317725ae2d1724cd33c6c841583afc3e | https://www.the-girl-who-ate-everything.com/magnolia-bakerys-famous-banana-pudding/ | yes |
| Tiramisu | AfricanBites-6f62a39913dd8029cd399d4ae47b0551f94a16865a3143b5dd28664c0880596e | 
https://cooking.nytimes.com/recipes/1018684-classic-tiramisu | yes | 
| Apple Pie | AfricanBites-fc015a5953d8811734f652ad17ba50d73f98d783350df0a95a6e2015007263f0 | https://www.allrecipes.com/recipe/12682/apple-pie-by-grandma-ople/ | yes | 
│ Fish and Chips | AfricanBites-2f35554786f85a304f1f5e86313f5d35730777a4f0861edf3474a914e9b7ec23 | https://www.thespruceeats.com/best-fish-and-chips-recipe-434856 | yes | 
│ Huli Huli Chicken | AfricanBites-5ca4ea56e8d49013ebd7457560a386a5e1a1059f267514b7c1dff7b9f0c78d72 | https://www.allrecipes.com/recipe/229690/huli-huli-chicken/ │ yes │
|

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[20:25]
         )

shape: (5, 3)
┌───────────────┬────────────────┬───────────────┐
│ title         ┆ mealeon_id     ┆ regex_filtere │
│ ---           ┆ ---            ┆ d_ingredients │
│ str           ┆ str            ┆ ---           │
│               ┆                ┆ list[str]     │
╞═══════════════╪════════════════╪═══════════════╡
│ Haggis        ┆ BBCFood-2ab22c ┆ ["sheep",     │
│               ┆ d0a3889f38cf74 ┆ "stomach",    │
│               ┆ 0040d33aae5a4b ┆ "pepper",     │
│               ┆ aa8568b70cde52 ┆ "ox",         │
│               ┆ 33d6f8a6739581 ┆ "secum",      │
│               ┆ 40             ┆ "salt",       │
│               ┆                ┆ "nutmeg",     │
│               ┆                ┆ "onions",     │
│               ┆                ┆ "coriander",  │
│               ┆                ┆ "turned",     │
│               ┆                ┆ "oatmeal",    │
│               ┆                ┆ "out", "fat", │
│               ┆                ┆ "mace",       │
│               ┆                ┆ "stock",      │
│               ┆                ┆ "beef",       │
│               ┆                ┆ "salted",     │
│               ┆                ┆ "water",      │
│               ┆                ┆ "heart",      │
│               ┆                ┆ "lungs",      │
│               ┆                ┆ "haggis",     │
│               ┆                ┆ "black",      │
│               ┆                ┆ "lamb"]       │
│ Scotch eggs   ┆ BBCFood-53dc7b ┆ ["white",     │
│               ┆ d8da3ef8a7dedf ┆ "flour",      │
│               ┆ ef0b2be1880f71 ┆ "eggs",       │
│               ┆ 585752d8113313 ┆ "black",      │
│               ┆ c6d9e49bd5cba6 ┆ "pork",       │
│               ┆ fa             ┆ "sausage",    │
│               ┆                ┆ "meat", "brea │
│               ┆                ┆ dcrumbs",     │
│               ┆                ┆ "oil",        │
│               ┆                ┆ "sage",       │
│               ┆                ┆ "thyme",      │
│               ┆                ┆ "vegetable",  │
│               ┆                ┆ "cayenne",    │
│               ┆                ┆ "pepper"]     │
│ Scotch eggs   ┆ BBCFood-ee117c ┆ ["salt",      │
│               ┆ e84728c9b2e906 ┆ "pepper",     │
│               ┆ 54f59895a89dc7 ┆ "black",      │
│               ┆ c10599b61bed83 ┆ "eggs",       │
│               ┆ f55e9bdf723e68 ┆ "sausage",    │
│               ┆ 90             ┆ "meat", "brea │
│               ┆                ┆ dcrumbs",     │
│               ┆                ┆ "oil",        │
│               ┆                ┆ "thyme",      │
│               ┆                ┆ "flour",      │
│               ┆                ┆ "onion",      │
│               ┆                ┆ "vegetable",  │
│               ┆                ┆ "parsley",    │
│               ┆                ┆ "egg"]        │
│ Buffalo wings ┆ BBCFood-47410d ┆ ["chicken",   │
│               ┆ c7097b2609d5c0 ┆ "sugar",      │
│               ┆ a80e4ce6f938b0 ┆ "butter",     │
│               ┆ 0be18b52907e5a ┆ "creamy",     │
│               ┆ 5322e33d6edee3 ┆ "vinegar",    │
│               ┆ 35             ┆ "caster",     │
│               ┆                ┆ "cheese",     │
│               ┆                ┆ "drumettes",  │
│               ┆                ┆ "flats",      │
│               ┆                ┆ "vegetable",  │
│               ┆                ┆ "oil",        │
│               ┆                ┆ "buttermilk", │
│               ┆                ┆ "onion",      │
│               ┆                ┆ "cider",      │
│               ┆                ┆ "few",        │
│               ┆                ┆ "celery",     │
│               ┆                ┆ "garlic",     │
│               ┆                ┆ "salt",       │
│               ┆                ┆ "blue",       │
│               ┆                ┆ "sauce",      │
│               ┆                ┆ "black",      │
│               ┆                ┆ "pepper"]     │
│ Pad Thai      ┆ BBCFood-056f01 ┆ ["flat",      │
│               ┆ 6b0b0d8c383c1a ┆ "rice",       │
│               ┆ 6bf47077a46a64 ┆ "noodles",    │
│               ┆ 529c04ab043c14 ┆ "garlic",     │
│               ┆ dce3b23d3980e0 ┆ "onions",     │
│               ┆ ed             ┆ "vein",       │
│               ┆                ┆ "fish",       │
│               ┆                ┆ "sugar",      │
│               ┆                ┆ "eggs",       │
│               ┆                ┆ "coriander",  │
│               ┆                ┆ "brown",      │
│               ┆                ┆ "pla", "nam", │
│               ┆                ┆ "red",        │
│               ┆                ┆ "chilli",     │
│               ┆                ┆ "seeds",      │
│               ┆                ┆ "lime",       │
│               ┆                ┆ "limes",      │
│               ┆                ┆ "zest", "bean │
│               ┆                ┆ sprouts",     │
│               ┆                ┆ "sauce",      │
│               ┆                ┆ "sunflower",  │
│               ┆                ┆ "oil",        │
│               ┆                ┆ "black",      │
│               ┆                ┆ "tiger",      │
│               ┆                ┆ "prawns",     │
│               ┆                ┆ "sesame",     │
│               ┆                ┆ "shelled"]    │
└───────────────┴────────────────┴───────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[25:30]
         )

shape: (5, 3)
┌────────────┬─────────────────┬─────────────────┐
│ title      ┆ mealeon_id      ┆ regex_filtered_ │
│ ---        ┆ ---             ┆ ingredients     │
│ str        ┆ str             ┆ ---             │
│            ┆                 ┆ list[str]       │
╞════════════╪═════════════════╪═════════════════╡
│ Margherita ┆ AllRecipes-715d ┆ ["tomatoes",    │
│ Pizza      ┆ 84d02e183deaaf2 ┆ "pam", "olive", │
│            ┆ 400f7526c80a2b0 ┆ "oil", "no",    │
│            ┆ 1a25032c1abb125 ┆ "cornmeal",     │
│            ┆ c28fe4d879cc672 ┆ "cheese",       │
│            ┆                 ┆ "plum",         │
│            ┆                 ┆ "mozzarella",   │
│            ┆                 ┆ "flour",        │
│            ┆                 ┆ "bread",        │
│            ┆                 ┆ "dough",        │
│            ┆                 ┆ "yellow",       │
│            ┆                 ┆ "basil",        │
│            ┆                 ┆ "hunt",         │
│            ┆                 ┆ "pepper",       │
│            ┆                 ┆ "black"]        │
│ Taco Rice  ┆ AllRecipes-e11c ┆ ["cheddar",     │
│            ┆ 702c9c5f8d5c0d6 ┆ "rice",         │
│            ┆ 3a6b58a60d90b87 ┆ "chicken",      │
│            ┆ f1f4e88dad3586b ┆ "broth",        │
│            ┆ 91b3248bb721504 ┆ "tomato",       │
│            ┆                 ┆ "sauce",        │
│            ┆                 ┆ "sour", "taco", │
│            ┆                 ┆ "olives",       │
│            ┆                 ┆ "black",        │
│            ┆                 ┆ "cream",        │
│            ┆                 ┆ "cheese"]       │
│ Elotes     ┆ AllRecipes-5fc2 ┆ ["ears",        │
│            ┆ fc72d7caf510b4c ┆ "corn", "on",   │
│            ┆ cde625c54a0907d ┆ "cotija",       │
│            ┆ e1489d323d385d7 ┆ "cob", "chile", │
│            ┆ 4c2a6c9c5d61c7b ┆ "mayonnaise",   │
│            ┆                 ┆ "peanut",       │
│            ┆                 ┆ "oil",          │
│            ┆                 ┆ "guajillo",     │
│            ┆                 ┆ "lime",         │
│            ┆                 ┆ "cheese",       │
│            ┆                 ┆ "salt"]         │
│ Pad Thai   ┆ AllRecipes-d4bb ┆ ["bean",        │
│            ┆ 95742a7fd71eb84 ┆ "mung", "rice", │
│            ┆ 8a7d4b2a4dc1322 ┆ "noodles",      │
│            ┆ 0e5bb378e1b6805 ┆ "fish",         │
│            ┆ d5ea493e0e1166d ┆ "peanut",       │
│            ┆                 ┆ "oil",          │
│            ┆                 ┆ "sprouts",      │
│            ┆                 ┆ "garlic",       │
│            ┆                 ┆ "greens",       │
│            ┆                 ┆ "chile", "egg", │
│            ┆                 ┆ "scallion",     │
│            ┆                 ┆ "vinegar",      │
│            ┆                 ┆ "sauce",        │
│            ┆                 ┆ "shrimp",       │
│            ┆                 ┆ "sugar",        │
│            ┆                 ┆ "peanuts"]      │
│ Yorkshire  ┆ AllRecipes-bb6d ┆ ["eggs",        │
│ Pudding    ┆ d1b85cfd3cbfeb6 ┆ "drippings",    │
│            ┆ 8160c187862ec6d ┆ "salt",         │
│            ┆ e84739123733cee ┆ "flour",        │
│            ┆ aae2976141f8936 ┆ "milk"]         │
└────────────┴─────────────────┴─────────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[31:35]
         )

shape: (4, 3)
┌────────────────┬───────────────┬───────────────┐
│ title          ┆ mealeon_id    ┆ regex_filtere │
│ ---            ┆ ---           ┆ d_ingredients │
│ str            ┆ str           ┆ ---           │
│                ┆               ┆ list[str]     │
╞════════════════╪═══════════════╪═══════════════╡
│ Kung Pao       ┆ AllRecipes-9b ┆ ["paste",     │
│ Chicken        ┆ fd691bb0521c3 ┆ "cornstarch", │
│                ┆ bba0275d1ef18 ┆ "vinegar",    │
│                ┆ ac30ea15c2aeb ┆ "garlic",     │
│                ┆ 0a48f2b9df1d5 ┆ "water",      │
│                ┆ defd962bed    ┆ "white",      │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "brown",      │
│                ┆               ┆ "soy",        │
│                ┆               ┆ "sauce",      │
│                ┆               ┆ "sesame",     │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "sugar",      │
│                ┆               ┆ "chili",      │
│                ┆               ┆ "peanuts",    │
│                ┆               ┆ "chicken",    │
│                ┆               ┆ "chestnuts",  │
│                ┆               ┆ "green",      │
│                ┆               ┆ "onions"]     │
│ Apple Pie      ┆ AllRecipes-38 ┆ ["pie",       │
│                ┆ 4fd2f67b06a5b ┆ "sugar",      │
│                ┆ fdf532f94d5e8 ┆ "margarine",  │
│                ┆ 9df99e08b91c5 ┆ "brown",      │
│                ┆ d9dace20fd29b ┆ "pared",      │
│                ┆ ba7b8fdad3    ┆ "white",      │
│                ┆               ┆ "apples",     │
│                ┆               ┆ "flour",      │
│                ┆               ┆ "pastry",     │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "cinnamon",   │
│                ┆               ┆ "ginger",     │
│                ┆               ┆ "nutmeg",     │
│                ┆               ┆ "lemon",      │
│                ┆               ┆ "egg"]        │
│ Huli Huli      ┆ AllRecipes-bd ┆ ["sugar",     │
│ Chicken        ┆ 864502bd1b052 ┆ "chicken",    │
│                ┆ f501d3148d66e ┆ "rice",       │
│                ┆ ffc966246a69a ┆ "pineapple",  │
│                ┆ 5e705c585fa36 ┆ "concentrate" │
│                ┆ 6d9599e090    ┆ , "brown",    │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "soy",        │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "vinegar",    │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "broth",      │
│                ┆               ┆ "ginger",     │
│                ┆               ┆ "sauce"]      │
│ Flapper Pie    ┆ AllRecipes-0c ┆ ["cornstarch" │
│                ┆ aa9e3e35dee29 ┆ , "graham",   │
│                ┆ 10e6f81c869d1 ┆ "cracker",    │
│                ┆ 176a2de129b8e ┆ "crumbs",     │
│                ┆ 3c7fddf6e469b ┆ "whites",     │
│                ┆ 9e3977fadb    ┆ "white",      │
│                ┆               ┆ "sugar",      │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "extract",    │
│                ┆               ┆ "egg",        │
│                ┆               ┆ "vanilla",    │
│                ┆               ┆ "cinnamon",   │
│                ┆               ┆ "milk"]       │
└────────────────┴───────────────┴───────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[35:40]
         )

shape: (5, 3)
┌────────────────┬───────────────┬───────────────┐
│ title          ┆ mealeon_id    ┆ regex_filtere │
│ ---            ┆ ---           ┆ d_ingredients │
│ str            ┆ str           ┆ ---           │
│                ┆               ┆ list[str]     │
╞════════════════╪═══════════════╪═══════════════╡
│ Chicken Tikka  ┆ Epicurious-a0 ┆ ["garlic",    │
│ Masala         ┆ ab4c8e25f1fe8 ┆ "vegetable",  │
│                ┆ e65f400f93db2 ┆ "oil",        │
│                ┆ 3cf55e1e46cb4 ┆ "rice",       │
│                ┆ 361cd65426f90 ┆ "steamed",    │
│                ┆ 8f3013f33d    ┆ "cream",      │
│                ┆               ┆ "ginger",     │
│                ┆               ┆ "cardamom",   │
│                ┆               ┆ "turmeric",   │
│                ┆               ┆ "garam",      │
│                ┆               ┆ "masala",     │
│                ┆               ┆ "coriander",  │
│                ┆               ┆ "cumin",      │
│                ┆               ┆ "basmati",    │
│                ┆               ┆ "cilantro",   │
│                ┆               ┆ "milk",       │
│                ┆               ┆ "yogurt",     │
│                ┆               ┆ "not",        │
│                ┆               ┆ "greek",      │
│                ┆               ┆ "tomato",     │
│                ┆               ┆ "ghee",       │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "paste",      │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "tomatoes",   │
│                ┆               ┆ "chicken",    │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "red",        │
│                ┆               ┆ "chiles"]     │
│ Taco Rice      ┆ Epicurious-b6 ┆ ["rice",      │
│                ┆ ae682f94cb0c4 ┆ "chili",      │
│                ┆ bf256ebfc5695 ┆ "paste",      │
│                ┆ 50702ef826124 ┆ "salt",       │
│                ┆ 57ff8e601cf9e ┆ "white",      │
│                ┆ 61e0b5f4ab    ┆ "cumin",      │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "tomato",     │
│                ┆               ┆ "oregano"]    │
│ Kung Pao       ┆ Epicurious-ca ┆ ["sesame",    │
│ Chicken        ┆ 2d5e56121ae04 ┆ "soy",        │
│                ┆ e8b7bdcd07648 ┆ "sauce",      │
│                ┆ 796b2d95afed0 ┆ "green",      │
│                ┆ 17fc56200535a ┆ "chinese",    │
│                ┆ d43ca8e51d    ┆ "rice",       │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "chilies",    │
│                ┆               ┆ "red",        │
│                ┆               ┆ "sherry",     │
│                ┆               ┆ "cornstarch", │
│                ┆               ┆ "vegetable",  │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "chicken",    │
│                ┆               ┆ "scallions",  │
│                ┆               ┆ "thighs",     │
│                ┆               ┆ "sichuan",    │
│                ┆               ┆ "sugar",      │
│                ┆               ┆ "peanut",     │
│                ┆               ┆ "white",      │
│                ┆               ┆ "black",      │
│                ┆               ┆ "vinegar",    │
│                ┆               ┆ "peanuts",    │
│                ┆               ┆ "ginger",     │
│                ┆               ┆ "hoisin",     │
│                ┆               ┆ "balsamic",   │
│                ┆               ┆ "oil"]        │
│ Cincinnati     ┆ Epicurious-ca ┆ ["vinegar",   │
│ Chili          ┆ 99be627e88806 ┆ "kidney",     │
│                ┆ d8357a5cbfdd3 ┆ "chili",      │
│                ┆ 14b3643028f27 ┆ "olive",      │
│                ┆ 5e6ae1c90adfc ┆ "oil", "worce │
│                ┆ f3ae9e30d4    ┆ stershire",   │
│                ┆               ┆ "cheddar",    │
│                ┆               ┆ "rated",      │
│                ┆               ┆ "onions",     │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "beans",      │
│                ┆               ┆ "cheese",     │
│                ┆               ┆ "brown",      │
│                ┆               ┆ "sugar",      │
│                ┆               ┆ "lamb",       │
│                ┆               ┆ "parsley",    │
│                ┆               ┆ "cocoa",      │
│                ┆               ┆ "oregano",    │
│                ┆               ┆ "sauce",      │
│                ┆               ┆ "allspice",   │
│                ┆               ┆ "cinnamon",   │
│                ┆               ┆ "cayenne",    │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "goat",       │
│                ┆               ┆ "gouda",      │
│                ┆               ┆ "milk",       │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "beef",       │
│                ┆               ┆ "broth",      │
│                ┆               ┆ "spaghetti",  │
│                ┆               ┆ "tomato",     │
│                ┆               ┆ "paste",      │
│                ┆               ┆ "apple",      │
│                ┆               ┆ "cider"]      │
│ Apple Pie      ┆ Epicurious-aa ┆ ["nutmeg",    │
│                ┆ 7806301b6fc90 ┆ "brown",      │
│                ┆ 4134d692a2a42 ┆ "lemon",      │
│                ┆ 5d0a0fd5a1f6f ┆ "pie",        │
│                ┆ 95cb431e8c311 ┆ "dough",      │
│                ┆ 73db7d99fa    ┆ "sugar",      │
│                ┆               ┆ "egg",        │
│                ┆               ┆ "apples",     │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "flour",      │
│                ┆               ┆ "cinnamon",   │
│                ┆               ┆ "milk",       │
│                ┆               ┆ "water",      │
│                ┆               ┆ "ginger"]     │
└────────────────┴───────────────┴───────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[41:45]
         )

shape: (4, 3)
┌──────────┬──────────────────┬──────────────────┐
│ title    ┆ mealeon_id       ┆ regex_filtered_i │
│ ---      ┆ ---              ┆ ngredients       │
│ str      ┆ str              ┆ ---              │
│          ┆                  ┆ list[str]        │
╞══════════╪══════════════════╪══════════════════╡
│ Kalbi    ┆ Epicurious-7e9ff ┆ ["bbq",          │
│          ┆ 3fc13b040941ed9f ┆ "marinade",      │
│          ┆ 7a4bbfd809e17a9c ┆ "scallions",     │
│          ┆ e7d5b569f1f6c4ba ┆ "korean",        │
│          ┆ 96e9a9ae140      ┆ "short", "ribs", │
│          ┆                  ┆ "each"]          │
│ Bagels   ┆ Epicurious-b3f8d ┆ ["salt",         │
│          ┆ 44e48bba1b47e5cf ┆ "baking",        │
│          ┆ 1482d8c5e076359f ┆ "barley",        │
│          ┆ a919061bbfd2f075 ┆ "malt", "syrup", │
│          ┆ d131aea2025      ┆ "honey",         │
│          ┆                  ┆ "flour", "rice", │
│          ┆                  ┆ "water",         │
│          ┆                  ┆ "diastatic",     │
│          ┆                  ┆ "soda", "bread", │
│          ┆                  ┆ "yeast"]         │
│ Pad Thai ┆ Epicurious-0293b ┆ ["nam",          │
│          ┆ 95bfc74cf90dc07e ┆ "peanuts",       │
│          ┆ 2ee399312e40e03d ┆ "paste", "rice", │
│          ┆ 14dd99e5db84e678 ┆ "noodles",       │
│          ┆ a1393b131cc      ┆ "sauce",         │
│          ┆                  ┆ "vegetable",     │
│          ┆                  ┆ "oil", "garlic", │
│          ┆                  ┆ "egg", "fish",   │
│          ┆                  ┆ "radish",        │
│          ┆                  ┆ "chiles",        │
│          ┆                  ┆ "shrimp",        │
│          ┆                  ┆ "tamarind",      │
│          ┆                  ┆ "water",         │
│          ┆                  ┆ "chives",        │
│          ┆                  ┆ "syrup", "pla",  │
│          ┆                  ┆ "tofu", "bean",  │
│          ┆                  ┆ "curd",          │
│          ┆                  ┆ "sprouts",       │
│          ┆                  ┆ "palm", "lime",  │
│          ┆                  ┆ "sugar"]         │
│ Pho      ┆ Epicurious-99089 ┆ ["lime", "rice", │
│          ┆ 59a4069c75bd1d95 ┆ "noodles",       │
│          ┆ c4b11678d15a63a1 ┆ "basil", "bell", │
│          ┆ 53c91d164d3f7d11 ┆ "peas", "star",  │
│          ┆ 59d35ae05dc      ┆ "red",           │
│          ┆                  ┆ "cilantro",      │
│          ┆                  ┆ "broth",         │
│          ┆                  ┆ "carrots",       │
│          ┆                  ┆ "anise",         │
│          ┆                  ┆ "ginger",        │
│          ┆                  ┆ "pepper",        │
│          ┆                  ┆ "sodium",        │
│          ┆                  ┆ "scallions",     │
│          ┆                  ┆ "chicken"]       │
└──────────┴──────────────────┴──────────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[45:50]
         )

shape: (5, 3)
┌────────────────┬───────────────┬───────────────┐
│ title          ┆ mealeon_id    ┆ regex_filtere │
│ ---            ┆ ---           ┆ d_ingredients │
│ str            ┆ str           ┆ ---           │
│                ┆               ┆ list[str]     │
╞════════════════╪═══════════════╪═══════════════╡
│ Pierogies      ┆ Epicurious-42 ┆ ["cutter",    │
│                ┆ 84e53129c7dc8 ┆ "nutmeg",     │
│                ┆ 9f97f2f193384 ┆ "potatoes",   │
│                ┆ 3946745df0613 ┆ "flour",      │
│                ┆ 70bd1ab738bf2 ┆ "white",      │
│                ┆ afe1c537c3    ┆ "black",      │
│                ┆               ┆ "cream",      │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "water",      │
│                ┆               ┆ "cookie",     │
│                ┆               ┆ "egg",        │
│                ┆               ┆ "sour",       │
│                ┆               ┆ "vegetable",  │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "cheddar",    │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "russet",     │
│                ┆               ┆ "baking"]     │
│ Seafood        ┆ Epicurious-4b ┆ ["oil",       │
│ Pancake        ┆ 6f818877199d3 ┆ "sesame",     │
│                ┆ 75e801cec974c ┆ "squid",      │
│                ┆ 6f6b037b4c0b2 ┆ "calamari",   │
│                ┆ aa2bbec0238dd ┆ "shrimp",     │
│                ┆ 77f797264d    ┆ "oysters",    │
│                ┆               ┆ "seeds",      │
│                ┆               ┆ "flour",      │
│                ┆               ┆ "water",      │
│                ┆               ┆ "eggs",       │
│                ┆               ┆ "sugar",      │
│                ┆               ┆ "sauce",      │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "vegetable",  │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "scallions",  │
│                ┆               ┆ "soy", "red", │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "vinegar"]    │
│ Lasagna        ┆ Epicurious-9e ┆ ["lettuces",  │
│                ┆ 24d01c507b4ee ┆ "thyme",      │
│                ┆ 64ee484fc4efa ┆ "shallot",    │
│                ┆ fb5f3d44709ab ┆ "sun",        │
│                ┆ b8fc36f1b34a9 ┆ "olive",      │
│                ┆ 1f7b69b678    ┆ "tomatoes",   │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "rawmesan",   │
│                ┆               ┆ "syrup",      │
│                ┆               ┆ "spinach",    │
│                ┆               ┆ "grape",      │
│                ┆               ┆ "lemon",      │
│                ┆               ┆ "water",      │
│                ┆               ┆ "mushrooms",  │
│                ┆               ┆ "nama",       │
│                ┆               ┆ "oregano",    │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "shoyu",      │
│                ┆               ┆ "cherry",     │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "corn",       │
│                ┆               ┆ "maple",      │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "each",       │
│                ┆               ┆ "celtic",     │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "cremini",    │
│                ┆               ┆ "basil",      │
│                ┆               ┆ "below",      │
│                ┆               ┆ "cheese",     │
│                ┆               ┆ "zucchini"]   │
│ Boeuf          ┆ Epicurious-77 ┆ ["tomato",    │
│ Bourguignon    ┆ 61b0f03aaf56b ┆ "du", "if",   │
│                ┆ 52b1de417213b ┆ "bacon",      │
│                ┆ 66fddf1d49c55 ┆ "red",        │
│                ┆ 4dabaacb23c9c ┆ "pearl",      │
│                ┆ 7a260982ba    ┆ "beef",       │
│                ┆               ┆ "chuck",      │
│                ┆               ┆ "bay",        │
│                ┆               ┆ "paste",      │
│                ┆               ┆ "onions",     │
│                ┆               ┆ "flour",      │
│                ┆               ┆ "not",        │
│                ┆               ┆ "vegetable",  │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "california", │
│                ┆               ┆ "butter",     │
│                ┆               ┆ "brandy",     │
│                ┆               ┆ "potatoes",   │
│                ┆               ┆ "burgundy",   │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "celery",     │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "parsley",    │
│                ┆               ┆ "mushrooms",  │
│                ┆               ┆ "no",         │
│                ┆               ┆ "carrots",    │
│                ┆               ┆ "thyme"]      │
│ Boeuf          ┆ Epicurious-e3 ┆ ["baby",      │
│ Bourguignon    ┆ 67b68ed6df8b0 ┆ "onions",     │
│                ┆ bccbeb73f9d82 ┆ "garlic",     │
│                ┆ 897294ef267fa ┆ "pearl",      │
│                ┆ 3a74d30505ce7 ┆ "bunches",    │
│                ┆ 470b2384dc    ┆ "carrots",    │
│                ┆               ┆ "thyme",      │
│                ┆               ┆ "red",        │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "tomato",     │
│                ┆               ┆ "bacon",      │
│                ┆               ┆ "rosemary",   │
│                ┆               ┆ "paste",      │
│                ┆               ┆ "carrot",     │
│                ┆               ┆ "broth",      │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "mushrooms",  │
│                ┆               ┆ "flour",      │
│                ┆               ┆ "sage",       │
│                ┆               ┆ "beef",       │
│                ┆               ┆ "bay",        │
│                ┆               ┆ "shiitake"]   │
└────────────────┴───────────────┴───────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[50:55]
         )

shape: (5, 3)
┌────────────────┬───────────────┬───────────────┐
│ title          ┆ mealeon_id    ┆ regex_filtere │
│ ---            ┆ ---           ┆ d_ingredients │
│ str            ┆ str           ┆ ---           │
│                ┆               ┆ list[str]     │
╞════════════════╪═══════════════╪═══════════════╡
│ California     ┆ Epicurious-d2 ┆ ["avocado",   │
│ Rolls          ┆ b862c91c84a69 ┆ "sauce",      │
│                ┆ b9b2f2be1a1cc ┆ "scotch",     │
│                ┆ 9702a2d6af8a6 ┆ "crab",       │
│                ┆ f1e5dcaccbacd ┆ "meat",       │
│                ┆ a6ed9f31b0    ┆ "legs",       │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "shelled",    │
│                ┆               ┆ "vinegared",  │
│                ┆               ┆ "water",      │
│                ┆               ┆ "nori",       │
│                ┆               ┆ "soy",        │
│                ┆               ┆ "lemon",      │
│                ┆               ┆ "wasabi",     │
│                ┆               ┆ "asakusa",    │
│                ┆               ┆ "rice",       │
│                ┆               ┆ "alaskan"]    │
│ Yellow Pea     ┆ Epicurious-6a ┆ ["thyme",     │
│ Soup           ┆ 7b3ef6808832f ┆ "hock",       │
│                ┆ bf1ab5a8e539e ┆ "ham",        │
│                ┆ b794866d630c1 ┆ "yellow",     │
│                ┆ b65218ee7b5c3 ┆ "peas",       │
│                ┆ 85b78f65a4    ┆ "smoked",     │
│                ┆               ┆ "water",      │
│                ┆               ┆ "root",       │
│                ┆               ┆ "over",       │
│                ┆               ┆ "leeks",      │
│                ┆               ┆ "white",      │
│                ┆               ┆ "celery",     │
│                ┆               ┆ "only",       │
│                ┆               ┆ "carrots"]    │
│ Yorkshire      ┆ Epicurious-3b ┆ ["eggs",      │
│ Pudding        ┆ 409b8e753718b ┆ "drippings",  │
│                ┆ db27213040549 ┆ "milk",       │
│                ┆ 1c4dcb4c26e73 ┆ "salt",       │
│                ┆ 412b54cea4083 ┆ "flour",      │
│                ┆ 19dc932c6e    ┆ "beef"]       │
│ Pho            ┆ AllRecipes-4f ┆ ["sirloin",   │
│                ┆ 31ce862b67de4 ┆ "bone",       │
│                ┆ 659f76e3a4de0 ┆ "rice",       │
│                ┆ 16a32770c8785 ┆ "beef",       │
│                ┆ 44d112aae95cc ┆ "shank",      │
│                ┆ 09b63d799a    ┆ "onion",      │
│                ┆               ┆ "green",      │
│                ┆               ┆ "sprouts",    │
│                ┆               ┆ "ginger",     │
│                ┆               ┆ "root",       │
│                ┆               ┆ "noodles",    │
│                ┆               ┆ "star",       │
│                ┆               ┆ "anise",      │
│                ┆               ┆ "cilantro",   │
│                ┆               ┆ "bean",       │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "onions",     │
│                ┆               ┆ "fish",       │
│                ┆               ┆ "sauce"]      │
│ Mexican Rice   ┆ AllRecipes-8a ┆ ["tomato",    │
│                ┆ a892f3f4d827f ┆ "vegetable",  │
│                ┆ 781d2bc149135 ┆ "oil",        │
│                ┆ 1d982144e2fa2 ┆ "sauce",      │
│                ┆ bb3226ebf5cc6 ┆ "chicken",    │
│                ┆ af6df5ac5a    ┆ "broth",      │
│                ┆               ┆ "cumin",      │
│                ┆               ┆ "rice",       │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "salt"]       │
└────────────────┴───────────────┴───────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[55:60]
         )

shape: (5, 3)
┌─────────────┬─────────────────┬────────────────┐
│ title       ┆ mealeon_id      ┆ regex_filtered │
│ ---         ┆ ---             ┆ _ingredients   │
│ str         ┆ str             ┆ ---            │
│             ┆                 ┆ list[str]      │
╞═════════════╪═════════════════╪════════════════╡
│ Carnitas    ┆ AllRecipes-9a5d ┆ ["chicken",    │
│             ┆ c3fa2511284deeb ┆ "salsa",       │
│             ┆ 5ee469d110874b0 ┆ "pork",        │
│             ┆ de9c021439cd0e0 ┆ "shoulder",    │
│             ┆ 88d3ef4f53f28bf ┆ "corn",        │
│             ┆                 ┆ "annatto",     │
│             ┆                 ┆ "flour",       │
│             ┆                 ┆ "sazon",       │
│             ┆                 ┆ "water",       │
│             ┆                 ┆ "adobo",       │
│             ┆                 ┆ "pico",        │
│             ┆                 ┆ "pepper",      │
│             ┆                 ┆ "gallo",       │
│             ┆                 ┆ "onion",       │
│             ┆                 ┆ "oil",         │
│             ┆                 ┆ "guacamole",   │
│             ┆                 ┆ "garlic",      │
│             ┆                 ┆ "green",       │
│             ┆                 ┆ "tortillas",   │
│             ┆                 ┆ "jalapeno",    │
│             ┆                 ┆ "orange",      │
│             ┆                 ┆ "bouillon",    │
│             ┆                 ┆ "cover"]       │
│ Arancini    ┆ AllRecipes-d431 ┆ ["flour",      │
│             ┆ cefd9f595be8a8f ┆ "olive",       │
│             ┆ cd7ff9e05a82ca1 ┆ "oil", "ham",  │
│             ┆ b79220c72edde1a ┆ "onion",       │
│             ┆ a2a0b6574060c04 ┆ "crumbs",      │
│             ┆                 ┆ "vegetable",   │
│             ┆                 ┆ "clove",       │
│             ┆                 ┆ "garlic",      │
│             ┆                 ┆ "milk",        │
│             ┆                 ┆ "cheese",      │
│             ┆                 ┆ "mozzarella",  │
│             ┆                 ┆ "arborio",     │
│             ┆                 ┆ "rice",        │
│             ┆                 ┆ "eggs",        │
│             ┆                 ┆ "white",       │
│             ┆                 ┆ "wine",        │
│             ┆                 ┆ "parmesan",    │
│             ┆                 ┆ "pepper",      │
│             ┆                 ┆ "chicken",     │
│             ┆                 ┆ "stock",       │
│             ┆                 ┆ "bread",       │
│             ┆                 ┆ "green",       │
│             ┆                 ┆ "peas",        │
│             ┆                 ┆ "salt"]        │
│ Kimchi Soup ┆ AllRecipes-c6d0 ┆ ["onions",     │
│             ┆ cd77e37ed8069f0 ┆ "water",       │
│             ┆ d9e72f9e8320264 ┆ "kimchi",      │
│             ┆ 59273ac1bc25878 ┆ "pepper",      │
│             ┆ 00dc8fcd1418ec7 ┆ "salt",        │
│             ┆                 ┆ "white",       │
│             ┆                 ┆ "shoulder",    │
│             ┆                 ┆ "paste",       │
│             ┆                 ┆ "sugar",       │
│             ┆                 ┆ "green",       │
│             ┆                 ┆ "pork"]        │
│ Menudo      ┆ AllRecipes-48bd ┆ ["chili",      │
│             ┆ e26e015dc9cbcbb ┆ "beef",        │
│             ┆ 540c4710248d538 ┆ "tripe",       │
│             ┆ 227d4afe5aa3e97 ┆ "onions",      │
│             ┆ 7e34710289789bb ┆ "hominy",      │
│             ┆                 ┆ "pepper",      │
│             ┆                 ┆ "salt",        │
│             ┆                 ┆ "white"]       │
│ Lasagna     ┆ AllRecipes-fddb ┆ ["clove",      │
│             ┆ 273d401ac45b568 ┆ "olive",       │
│             ┆ 695daeb1abe0b63 ┆ "oil",         │
│             ┆ 2696dd867992fd4 ┆ "onion",       │
│             ┆ 01e31dc794d66f9 ┆ "zucchini",    │
│             ┆                 ┆ "bay", "leaf", │
│             ┆                 ┆ "noodles",     │
│             ┆                 ┆ "garlic",      │
│             ┆                 ┆ "parmesan",    │
│             ┆                 ┆ "lasagna",     │
│             ┆                 ┆ "oregano",     │
│             ┆                 ┆ "basil",       │
│             ┆                 ┆ "mozzarella",  │
│             ┆                 ┆ "eggs",        │
│             ┆                 ┆ "cheese",      │
│             ┆                 ┆ "tomatoes",    │
│             ┆                 ┆ "mushrooms",   │
│             ┆                 ┆ "spinach",     │
│             ┆                 ┆ "ricotta",     │
│             ┆                 ┆ "cinnamon"]    │
└─────────────┴─────────────────┴────────────────┘

In [ ]:
with pl.Config(fmt_table_cell_list_len=50,
               fmt_str_lengths=2000,
               set_tbl_width_chars=50,
               ):
    print(filtered_to_investigate.select(
        ["title", 
         "mealeon_id",
         "regex_filtered_ingredients"
         ]
         )[60:69]
         )

shape: (8, 3)
┌────────────────┬───────────────┬───────────────┐
│ title          ┆ mealeon_id    ┆ regex_filtere │
│ ---            ┆ ---           ┆ d_ingredients │
│ str            ┆ str           ┆ ---           │
│                ┆               ┆ list[str]     │
╞════════════════╪═══════════════╪═══════════════╡
│ Huli Huli      ┆ AllRecipes-1b ┆ ["onions",    │
│ Chicken        ┆ 1ac4f279d0cbb ┆ "chickens",   │
│                ┆ 0c680da7a1839 ┆ "each",       │
│                ┆ d0031a52f3cc7 ┆ "ginger",     │
│                ┆ 3681dbb2644cf ┆ "green",      │
│                ┆ 96d6aec4f9    ┆ "sherry",     │
│                ┆               ┆ "ketchup",    │
│                ┆               ┆ "mustard",    │
│                ┆               ┆ "pineapple",  │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "soy",        │
│                ┆               ┆ "sauce",      │
│                ┆               ┆ "brown",      │
│                ┆               ┆ "sugar"]      │
│ Beef           ┆ AllRecipes-69 ┆ ["pepper",    │
│ Wellington     ┆ 14cfedf5d3af5 ┆ "beef",       │
│                ┆ 2ea66433959c9 ┆ "tenderloin", │
│                ┆ 58821b8940ee1 ┆ "liver",      │
│                ┆ 948fbe29f841d ┆ "butter",     │
│                ┆ 48ad1de4a4    ┆ "egg",        │
│                ┆               ┆ "puff",       │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "red",        │
│                ┆               ┆ "pastry",     │
│                ┆               ┆ "broth",      │
│                ┆               ┆ "wine",       │
│                ┆               ┆ "mushrooms",  │
│                ┆               ┆ "salt"]       │
│ Poutine        ┆ AllRecipes-f3 ┆ ["cheese",    │
│                ┆ aafa676ce9761 ┆ "beef",       │
│                ┆ 37a1e9a62a6be ┆ "cheddar",    │
│                ┆ eca6288c2a4b0 ┆ "french",     │
│                ┆ c35ba2c4da9cd ┆ "gravy"]      │
│                ┆ 6a4fa9f466    ┆               │
│ Souvlaki       ┆ AllRecipes-9e ┆ ["yellow",    │
│                ┆ 94827f263b040 ┆ "olive",      │
│                ┆ 9c124dd60e95e ┆ "oil", "soy", │
│                ┆ 4a61e1d446940 ┆ "sauce",      │
│                ┆ e3ad3b88b4e3b ┆ "onions",     │
│                ┆ 43d00b6f65    ┆ "lemon",      │
│                ┆               ┆ "green",      │
│                ┆               ┆ "pork",       │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "bell",       │
│                ┆               ┆ "peppers",    │
│                ┆               ┆ "tenderloin", │
│                ┆               ┆ "oregano"]    │
│ Yorkshire      ┆ AllRecipes-92 ┆ ["drippings", │
│ Pudding        ┆ c5c30f5c0b165 ┆ "eggs",       │
│                ┆ 5a1e1900fcdaa ┆ "milk",       │
│                ┆ 603917f2abf62 ┆ "flour",      │
│                ┆ 529c130713412 ┆ "beef",       │
│                ┆ a844046e33    ┆ "salt",       │
│                ┆               ┆ "water"]      │
│ Ginger Beef    ┆ AllRecipes-3e ┆ ["onions",    │
│                ┆ 906cbcfdee7e4 ┆ "rice",       │
│                ┆ c52d087efc24a ┆ "soup",       │
│                ┆ ea9c7e3b760a8 ┆ "peanut",     │
│                ┆ c5f0d1c85c459 ┆ "garlic",     │
│                ┆ f3354b643d    ┆ "onion",      │
│                ┆               ┆ "tomatoes",   │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "flank",      │
│                ┆               ┆ "water",      │
│                ┆               ┆ "white",      │
│                ┆               ┆ "ginger",     │
│                ┆               ┆ "root",       │
│                ┆               ┆ "oil",        │
│                ┆               ┆ "condensed",  │
│                ┆               ┆ "turmeric",   │
│                ┆               ┆ "steak",      │
│                ┆               ┆ "salt",       │
│                ┆               ┆ "chile"]      │
│ Boeuf          ┆ AllRecipes-a0 ┆ ["wine",      │
│ Bourguignon    ┆ ae2dfd0ca25ae ┆ "vegetable",  │
│                ┆ 3146df101d1dc ┆ "oil",        │
│                ┆ 0e7c54e39eec6 ┆ "onions",     │
│                ┆ 9617ff634f42d ┆ "flour",      │
│                ┆ 80d7b70be4    ┆ "thyme",      │
│                ┆               ┆ "pepper",     │
│                ┆               ┆ "beef",       │
│                ┆               ┆ "black",      │
│                ┆               ┆ "mushrooms",  │
│                ┆               ┆ "broth",      │
│                ┆               ┆ "red",        │
│                ┆               ┆ "marjoram"]   │
│ Tourtiere      ┆ AllRecipes-3c ┆ ["black",     │
│                ┆ 9cbb4d78d017a ┆ "salt",       │
│                ┆ 21a48907adbc3 ┆ "pork",       │
│                ┆ 1c2593ebbd071 ┆ "veal",       │
│                ┆ 7b9391779a2f7 ┆ "cornstarch", │
│                ┆ 5b531fcbe4    ┆ "bacon",      │
│                ┆               ┆ "pie",        │
│                ┆               ┆ "water",      │
│                ┆               ┆ "onion",      │
│                ┆               ┆ "celery",     │
│                ┆               ┆ "clove",      │
│                ┆               ┆ "garlic",     │
│                ┆               ┆ "crusts",     │
│                ┆               ┆ "sage",       │
│                ┆               ┆ "pepper"]     │
└────────────────┴───────────────┴───────────────┘

Need to test search queries that:
1) Get the recipe we're looking for
    - Query should already have the recipe title, recipe cuisine
    - We use the title and cuisine to get the ingredients
2) Do not return the same recipe name back
    eg `WHERE !(title contains [query_recipe_title])`
    or `WHERE !(title [fuzzy logic] [query_recipe_title])`
3) Do not return the same cuisine back
    eg `WHERE !(cuisine contains [query_recipe_cuisine or query_recipe_cuisine_superset])`
4) Maximize ingredient similarity (start with cosine similarity)
    - Could try vespa dotProduct, wand

In [ ]:
# ok baseline recipes
baselines = [
    "BBCFood-11015de4db20e53dcda0035673dfdbeca355d2a1d37d71f13d5fe5ea7ccca02d", #cacio e pepe
    "AllRecipes-fddb273d401ac45b568695daeb1abe0b632696dd867992fd401e31dc794d66f9", #lasagna
    "AllRecipes-715d84d02e183deaaf2400f7526c80a2b01a25032c1abb125c28fe4d879cc672", #margherita pizza
    "AfricanBites-6f62a39913dd8029cd399d4ae47b0551f94a16865a3143b5dd28664c0880596e", #tiramisu
    "AllRecipes-867b4f3b539b381fb9f35252402fc14efc9d6fcc64353089959ac159372a8199", #tiramisu
    "BBCFood-c6b9581aa49ee6b0cc3f686f58cfd124c395284cc46dfcde5bc931982975ee15", #tiramisu
    "BBCFood-d59ab715a7f6f0022155b1149e4e059b0497fd790993fb11f1795b901cae8f97", #cannoli
    "AllRecipes-d431cefd9f595be8a8fcd7ff9e05a82ca1b79220c72edde1aa2a0b6574060c04", #arancini
    "BBCFood-056f016b0b0d8c383c1a6bf47077a46a64529c04ab043c14dce3b23d3980e0ed", # pad thai
    "AllRecipes-d4bb95742a7fd71eb848a7d4b2a4dc13220e5bb378e1b6805d5ea493e0e1166d", # pad thai
    "Epicurious-0293b95bfc74cf90dc07e2ee399312e40e03d14dd99e5db84e678a1393b131cc", # pad thai
    "Epicurious-ca2d5e56121ae04e8b7bdcd07648796b2d95afed017fc56200535ad43ca8e51d", # kung pao chicken
    "Epicurious-7761b0f03aaf56b52b1de417213b66fddf1d49c554dabaacb23c9c7a260982ba", # boeuf bourguignon
    "Epicurious-e367b68ed6df8b0bccbeb73f9d82897294ef267fa3a74d30505ce7470b2384dc", # boeuf bourguignon 
    "AllRecipes-6914cfedf5d3af52ea66433959c958821b8940ee1948fbe29f841d48ad1de4a4", # beef wellington
    "AfricanBites-2f35554786f85a304f1f5e86313f5d35730777a4f0861edf3474a914e9b7ec23", # fish and chips
    "BBCFood-adcbfceaa8636f83ff8866d44bc7a44385c71250d73d427c08dbe345e4127143", # fish and chips
    "BBCFood-0a7c810d7b7c99ae728f9a2deff14340edb099949f20fed75a8083c29ca83aab", # chicken tikka masala
    "Epicurious-a0ab4c8e25f1fe8e65f400f93db23cf55e1e46cb4361cd65426f908f3013f33d", #chicken tikka masala
    "AllRecipes-bb6dd1b85cfd3cbfeb68160c187862ec6de84739123733ceeaae2976141f8936", # yorkshire pudding
    "AllRecipes-92c5c30f5c0b1655a1e1900fcdaa603917f2abf62529c130713412a844046e33", # yorkshire pudding
    "AfricanBites-fc015a5953d8811734f652ad17ba50d73f98d783350df0a95a6e2015007263f0", # apple pie
    "AllRecipes-384fd2f67b06a5bfdf532f94d5e89df99e08b91c5d9dace20fd29bba7b8fdad3", # apple pie, this might need to get taken out
    "Epicurious-aa7806301b6fc904134d692a2a425d0a0fd5a1f6f95cb431e8c31173db7d99fa", # apple pie
    "BBCFood-ee117ce84728c9b2e90654f59895a89dc7c10599b61bed83f55e9bdf723e6890", # scotch egg
    "BBCFood-53dc7bd8da3ef8a7dedfef0b2be1880f71585752d8113313c6d9e49bd5cba6fa", # scotch egg
    "BBCFood-2ab22cd0a3889f38cf740040d33aae5a4baa8568b70cde5233d6f8a673958140", # haggis
    "BBCFood-47410dc7097b2609d5c0a80e4ce6f938b00be18b52907e5a5322e33d6edee335", # buffalo wings
    "AfricanBites-587700762275fbf6a6e2a343b27cc689317725ae2d1724cd33c6c841583afc3e", # banana pudding
    "Epicurious-ca99be627e88806d8357a5cbfdd314b3643028f275e6ae1c90adfcf3ae9e30d4", # cincinnati chili
    "Epicurious-7e9ff3fc13b040941ed9f7a4bbfd809e17a9ce7d5b569f1f6c4ba96e9a9ae140", #kalbi
    "Epicurious-4b6f818877199d375e801cec974c6f6b037b4c0b2aa2bbec0238dd77f797264d", # seafood pancake
    "AllRecipes-c6d0cd77e37ed8069f0d9e72f9e832026459273ac1bc2587800dc8fcd1418ec7", #kimchi soup
    "AllRecipes-48bde26e015dc9cbcbb540c4710248d538227d4afe5aa3e977e34710289789bb", # menudo
    "AllRecipes-cac0d29872bd9f49d34d8c9eac41a3806929420f84e36b8e579c3bce939cdc7b", # pozole
    "AllRecipes-9a5dc3fa2511284deeb5ee469d110874b0de9c021439cd0e088d3ef4f53f28bf", # carnitas
    "BBCFood-6d6cc18dadaffa5ea10194b59aa6e310d34b1f713756d0b528cc57c5e61d92e3", # carnitas
    "AllRecipes-5fc2fc72d7caf510b4ccde625c54a0907de1489d323d385d74c2a6c9c5d61c7b", # elotes
    "AllRecipes-8aa892f3f4d827f781d2bc1491351d982144e2fa2bb3226ebf5cc6af6df5ac5a", # mexican rice
    "AllRecipes-4f31ce862b67de4659f76e3a4de016a32770c878544d112aae95cc09b63d799a", # pho
    "Epicurious-b3f8d44e48bba1b47e5cf1482d8c5e076359fa919061bbfd2f075d131aea2025", # bagels
    "Epicurious-6a7b3ef6808832fbf1ab5a8e539eb794866d630c1b65218ee7b5c385b78f65a4", # yellow pea soup
    "AllRecipes-0caa9e3e35dee2910e6f81c869d1176a2de129b8e3c7fddf6e469b9e3977fadb", # custard 
    "AllRecipes-3c9cbb4d78d017a21a48907adbc31c2593ebbd0717b9391779a2f75b531fcbe4", # tourtiere
    "Epicurious-d2b862c91c84a69b9b2f2be1a1cc9702a2d6af8a6f1e5dcaccbacda6ed9f31b0", # california roll
    "AllRecipes-b8116cc920cd9d916cd196927ad2af1062785cdaa3d3b4fc3e997ee86fd75c84", # pierogi
    "Epicurious-4284e53129c7dc89f97f2f1933843946745df061370bd1ab738bf2afe1c537c3", # pierogi
    "AfricanBites-5ca4ea56e8d49013ebd7457560a386a5e1a1059f267514b7c1dff7b9f0c78d72", # huli huli chicken
    "AllRecipes-bd864502bd1b052f501d3148d66effc966246a69a5e705c585fa366d9599e090", # huli huli chicken
    "AllRecipes-1b1ac4f279d0cbb0c680da7a1839d0031a52f3cc73681dbb2644cf96d6aec4f9", # huli huli chicken
]

In [ ]:
len(baselines)

50

In [ ]:
baseline_df = filtered_to_investigate.filter(
    pl.col("mealeon_id").str.contains_any(baselines)
)

baseline_df

shape: (50, 12)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mealeon_i ┆ language ┆ source_id ┆ title     ┆ … ┆ descripti ┆ steps     ┆ cuisines  ┆ regex_fil │
│ d         ┆ ---      ┆ ---       ┆ ---       ┆   ┆ on        ┆ ---       ┆ ---       ┆ tered_ing │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ list[str] ┆ list[str] ┆ redients  │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ list[str] │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AfricanBi ┆ English  ┆ 597818    ┆ Banana    ┆ … ┆ Homemade  ┆ ["Add dry ┆ ["US Sout ┆ ["cream", │
│ tes-58770 ┆          ┆           ┆ Pudding   ┆   ┆ Banana    ┆ ingredien ┆ hern"]    ┆ "cornstar │
│ 0762275fb ┆          ┆           ┆           ┆   ┆ Pudding – ┆ ts to a   ┆           ┆ ch", …    │
│ f6a…      ┆          ┆           ┆           ┆   ┆ a cl…     ┆ sau…      ┆           ┆ "waf…     │
│ AfricanBi ┆ English  ┆ 598753    ┆ Tiramisu  ┆ … ┆ This      ┆ ["In a    ┆ ["Italian ┆ ["liquor" │
│ tes-6f62a ┆          ┆           ┆           ┆   ┆ classic   ┆ medium    ┆ "]        ┆ , "egg",  │
│ 39913dd80 ┆          ┆           ┆           ┆   ┆ Italian   ┆ saucepan, ┆           ┆ … "extrac │
│ 29c…      ┆          ┆           ┆           ┆   ┆ coffee-fl ┆ whisk …   ┆           ┆ t"]       │
│           ┆          ┆           ┆           ┆   ┆ …         ┆           ┆           ┆           │
│ AfricanBi ┆ English  ┆ 607516    ┆ Apple Pie ┆ … ┆ Made with ┆ ["Start   ┆ ["America ┆ ["sprinkl │
│ tes-fc015 ┆          ┆           ┆           ┆   ┆ lightly   ┆ by making ┆ n"]       ┆ ing",     │
│ a5953d881 ┆          ┆           ┆           ┆   ┆ spiced    ┆ the pie   ┆           ┆ "pie", …  │
│ 173…      ┆          ┆           ┆           ┆   ┆ apple…    ┆ crus…     ┆           ┆ "egg"]    │
│ AfricanBi ┆ English  ┆ 608647    ┆ Fish and  ┆ … ┆ Perfectly ┆ ["In a    ┆ ["British ┆ ["russet" │
│ tes-2f355 ┆          ┆           ┆ Chips     ┆   ┆ seasoned  ┆ large     ┆ "]        ┆ , "vinega │
│ 54786f85a ┆          ┆           ┆           ┆   ┆ tender    ┆ bowl,     ┆           ┆ r", …     │
│ 304…      ┆          ┆           ┆           ┆   ┆ fish…     ┆ whisk     ┆           ┆ "cod"]    │
│           ┆          ┆           ┆           ┆   ┆           ┆ toget…    ┆           ┆           │
│ AfricanBi ┆ English  ┆ 567371    ┆ Huli Huli ┆ … ┆ Huli Huli ┆ ["In a    ┆ ["America ┆ ["srirach │
│ tes-5ca4e ┆          ┆           ┆ Chicken   ┆   ┆ Chicken - ┆ medium    ┆ n"]       ┆ a", "chic │
│ a56e8d490 ┆          ┆           ┆           ┆   ┆ Grilled   ┆ bowl, mix ┆           ┆ ken", …   │
│ 13e…      ┆          ┆           ┆           ┆   ┆ or…       ┆ the pi…   ┆           ┆ "gre…     │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ AllRecipe ┆ English  ┆ 14054     ┆ Lasagna   ┆ … ┆ Vegetable ┆ ["Heat    ┆ ["Missing ┆ ["clove", │
│ s-fddb273 ┆          ┆           ┆           ┆   ┆ lasagna   ┆ 1/4 cup   ┆ Cuisine"] ┆ "olive",  │
│ d401ac45b ┆          ┆           ┆           ┆   ┆ with all  ┆ oil in a  ┆           ┆ … "cinnam │
│ 568…      ┆          ┆           ┆           ┆   ┆ the…      ┆ large …   ┆           ┆ on…       │
│ AllRecipe ┆ English  ┆ 229690    ┆ Huli Huli ┆ … ┆ 'Huli     ┆ ["Rinse   ┆ ["Missing ┆ ["onions" │
│ s-1b1ac4f ┆          ┆           ┆ Chicken   ┆   ┆ Huli      ┆ chicken   ┆ Cuisine"] ┆ , "chicke │
│ 279d0cbb0 ┆          ┆           ┆           ┆   ┆ Chicken'  ┆ pieces    ┆           ┆ ns", …    │
│ c68…      ┆          ┆           ┆           ┆   ┆ (turn,    ┆ and pat…  ┆           ┆ "suga…    │
│           ┆          ┆           ┆           ┆   ┆ tur…      ┆           ┆           ┆           │
│ AllRecipe ┆ English  ┆ 16899     ┆ Beef Well ┆ … ┆ This beef ┆ ["This    ┆ ["Missing ┆ ["pepper" │
│ s-6914cfe ┆          ┆           ┆ ington    ┆   ┆ Wellingto ┆ classic   ┆ Cuisine"] ┆ , "beef", │
│ df5d3af52 ┆          ┆           ┆           ┆   ┆ n recipe  ┆ Beef Well ┆           ┆ … "salt"] │
│ ea6…      ┆          ┆           ┆           ┆   ┆ ma…       ┆ ington…   ┆           ┆           │
│ AllRecipe ┆ English  ┆ 9239      ┆ Yorkshire ┆ … ┆ This      ┆ ["Mix     ┆ ["Missing ┆ ["drippin │
│ s-92c5c30 ┆          ┆           ┆ Pudding   ┆   ┆ Yorkshire ┆ together  ┆ Cuisine"] ┆ gs",      │
│ f5c0b1655 ┆          ┆           ┆           ┆   ┆ pudding   ┆ flour and ┆           ┆ "eggs", … │
│ a1e…      ┆          ┆           ┆           ┆   ┆ recipe …  ┆ salt …    ┆           ┆ "water…   │
│ AllRecipe ┆ English  ┆ 12406     ┆ Tourtiere ┆ … ┆ Tradition ┆ ["In a    ┆ ["Missing ┆ ["black", │
│ s-3c9cbb4 ┆          ┆           ┆           ┆   ┆ al French ┆ Dutch     ┆ Cuisine"] ┆ "salt", … │
│ d78d017a2 ┆          ┆           ┆           ┆   ┆ -Canadian ┆ oven,     ┆           ┆ "pepper"] │
│ 1a4…      ┆          ┆           ┆           ┆   ┆ Me…       ┆ brown     ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ groun…    ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
baseline_df.filter(
    pl.col("title").str.to_lowercase().str.contains("tiramisu")
)

shape: (3, 12)
┌────────────┬──────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mealeon_id ┆ language ┆ source_id ┆ title    ┆ … ┆ descripti ┆ steps     ┆ cuisines  ┆ regex_fil │
│ ---        ┆ ---      ┆ ---       ┆ ---      ┆   ┆ on        ┆ ---       ┆ ---       ┆ tered_ing │
│ str        ┆ str      ┆ str       ┆ str      ┆   ┆ ---       ┆ list[str] ┆ list[str] ┆ redients  │
│            ┆          ┆           ┆          ┆   ┆ str       ┆           ┆           ┆ ---       │
│            ┆          ┆           ┆          ┆   ┆           ┆           ┆           ┆ list[str] │
╞════════════╪══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AfricanBit ┆ English  ┆ 598753    ┆ Tiramisu ┆ … ┆ This      ┆ ["In a    ┆ ["Italian ┆ ["liquor" │
│ es-6f62a39 ┆          ┆           ┆          ┆   ┆ classic   ┆ medium    ┆ "]        ┆ , "egg",  │
│ 913dd8029c ┆          ┆           ┆          ┆   ┆ Italian   ┆ saucepan, ┆           ┆ … "extrac │
│ …          ┆          ┆           ┆          ┆   ┆ coffee-fl ┆ whisk …   ┆           ┆ t"]       │
│            ┆          ┆           ┆          ┆   ┆ …         ┆           ┆           ┆           │
│ AllRecipes ┆ English  ┆ 21412     ┆ Tiramisu ┆ … ┆ This      ┆ ["Tiramis ┆ ["Missing ┆ ["cookies │
│ -867b4f3b5 ┆          ┆           ┆          ┆   ┆ delicious ┆ u, with   ┆ Cuisine"] ┆ ", "egg", │
│ 39b381fb9f ┆          ┆           ┆          ┆   ┆ tiramisu  ┆ its irres ┆           ┆ … "mascar │
│ …          ┆          ┆           ┆          ┆   ┆ made w…   ┆ isti…     ┆           ┆ po…       │
│ BBCFood-c6 ┆ English  ┆ https://w ┆ Tiramisu ┆ … ┆ This      ┆ ["In a    ┆ ["Italian ┆ ["finger" │
│ b9581aa49e ┆          ┆ ww.bbc.co ┆          ┆   ┆ authentic ┆ large     ┆ "]        ┆ , "marsal │
│ e6b0cc3f68 ┆          ┆ .uk/food/ ┆          ┆   ┆ Italian   ┆ bowl,     ┆           ┆ a", …     │
│ …          ┆          ┆ rec…      ┆          ┆   ┆ tiramis…  ┆ whisk the ┆           ┆ "biscu…   │
│            ┆          ┆           ┆          ┆   ┆           ┆ e…        ┆           ┆           │
└────────────┴──────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# polars search can be 
recipe_title = "tiramisu"
recipe_cuisine = "italian"

baseline_df.filter(
    pl.col("title").str.to_lowercase().str.contains(recipe_title),
    pl.col("cuisines").list.contains(recipe_cuisine.title())
)

shape: (2, 12)
┌────────────┬──────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mealeon_id ┆ language ┆ source_id ┆ title    ┆ … ┆ descripti ┆ steps     ┆ cuisines  ┆ regex_fil │
│ ---        ┆ ---      ┆ ---       ┆ ---      ┆   ┆ on        ┆ ---       ┆ ---       ┆ tered_ing │
│ str        ┆ str      ┆ str       ┆ str      ┆   ┆ ---       ┆ list[str] ┆ list[str] ┆ redients  │
│            ┆          ┆           ┆          ┆   ┆ str       ┆           ┆           ┆ ---       │
│            ┆          ┆           ┆          ┆   ┆           ┆           ┆           ┆ list[str] │
╞════════════╪══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AfricanBit ┆ English  ┆ 598753    ┆ Tiramisu ┆ … ┆ This      ┆ ["In a    ┆ ["Italian ┆ ["liquor" │
│ es-6f62a39 ┆          ┆           ┆          ┆   ┆ classic   ┆ medium    ┆ "]        ┆ , "egg",  │
│ 913dd8029c ┆          ┆           ┆          ┆   ┆ Italian   ┆ saucepan, ┆           ┆ … "extrac │
│ …          ┆          ┆           ┆          ┆   ┆ coffee-fl ┆ whisk …   ┆           ┆ t"]       │
│            ┆          ┆           ┆          ┆   ┆ …         ┆           ┆           ┆           │
│ BBCFood-c6 ┆ English  ┆ https://w ┆ Tiramisu ┆ … ┆ This      ┆ ["In a    ┆ ["Italian ┆ ["finger" │
│ b9581aa49e ┆          ┆ ww.bbc.co ┆          ┆   ┆ authentic ┆ large     ┆ "]        ┆ , "marsal │
│ e6b0cc3f68 ┆          ┆ .uk/food/ ┆          ┆   ┆ Italian   ┆ bowl,     ┆           ┆ a", …     │
│ …          ┆          ┆ rec…      ┆          ┆   ┆ tiramis…  ┆ whisk the ┆           ┆ "biscu…   │
│            ┆          ┆           ┆          ┆   ┆           ┆ e…        ┆           ┆           │
└────────────┴──────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

- From this dataframe, we want the `mealeon_id`, `ingredients` to be used in Vespa

- `mealeon_id` can be used directly in vespa. JUST KIDDING

- `title`

-  `ingredients` need some form of vectorization/embedding creation

- embedding creation can be done with vespa feed?
  - might be able to use json feed 

- vespa distance-metric with the filters above for avoiding same name and same cuisine

In [ ]:
with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f"select * from sources mealeon3 where title contains '{recipe_title}' limit 10",
        query=recipe_title,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
pprint.pp(response.hits)

[]

In [ ]:
recipe_title

'tiramisu'

In [ ]:
with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f'select * from sources mealeon3 where !(title contains "{recipe_title}") and !(cuisine in {recipe_cuisine}) limit 10',
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f'select * from sources mealeon3 where !(cuisine in {recipe_cuisine}) limit 10',
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
type(recipe_cuisine)

In [ ]:
with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f"select * from sources mealeon3 where !(cuisine in {[recipe_cuisine]}) limit 10",
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
recipe_cuisine

'italian'

In [ ]:
print([recipe_cuisine])

In [ ]:
cuisines_queried = [recipe_cuisine]

with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f"select * from sources mealeon3 where !(cuisine in {cuisines_queried}) limit 10",
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f"select * from sources mealeon3 where !(cuisine in ({recipe_cuisine}) limit 10",
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
with app.syncio(connections=1) as session:
    response: VespaQueryResponse = session.query(
        yql=f"select * from sources mealeon3 where !(cuisines in ('italian')) limit 10",
        query=query,
        ranking="bm25"
        # body={"input.query(q)": f"embed({query})"},
    )
    assert response.is_successful()

In [ ]:
pprint.pp(response.hits)

[]

In [ ]:
# actual results
results = resp_json['hits']
results

In [ ]:
# | hide
nbdev.nbdev_export()