---
output-file: migrate_foodb_json_to_postgres.html
title: Convert FooDB JSON files into Polars then Postgres

---

In [ ]:
# import libraries
import json
import os
import polars as pl
import polars.selectors as cs
from sqlalchemy import create_engine

In [ ]:
json_path = "../data/raw/foodb_2020_04_07_json/"

# let's open one of these files and see what happens
# ideally, we open each file in the directory
# keep the file name (ie, everything before .json)
# use the file name as a table name in postgres

for filename in os.listdir(json_path):
    if filename.endswith(".json"):
        print(filename)

FoodTaxonomy.json
OntologySynonym.json
NcbiTaxonomyMap.json
Food.json
Enzyme.json
Nutrient.json
Reference.json
Flavor.json
OntologyTerm.json
Pathway.json
Content.json
HealthEffect.json

In [ ]:
for filename in os.listdir(json_path):
    if filename.endswith(".json"):
        df_label = filename[:-5]
        date_columns = ["created_at", "updated_at"]
        print(f"Processing {os.path.join(json_path, filename)}")
        df = pl.read_ndjson(os.path.join(json_path, filename))
        df = df.with_columns(
            cs.by_name(date_columns, require_all=False).cast(pl.Datetime)
        )
        with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000):
            print(df.head())

Processing ../data/raw/foodb_2020_04_07_json/FoodTaxonomy.json
shape: (5, 7)
┌─────┬─────────┬──────────────────┬─────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ id  ┆ food_id ┆ ncbi_taxonomy_id ┆ classification_name ┆ classification_order ┆ created_at          ┆ updated_at          │
│ --- ┆ ---     ┆ ---              ┆ ---                 ┆ ---                  ┆ ---                 ┆ ---                 │
│ i64 ┆ i64     ┆ i64              ┆ str                 ┆ i64                  ┆ datetime[μs]        ┆ datetime[μs]        │
╞═════╪═════════╪══════════════════╪═════════════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ 1   ┆ 1       ┆ 357850           ┆ "Eukaryota"         ┆ 1                    ┆ 2017-03-29 18:35:53 ┆ 2017-03-29 18:35:53 │
│ 2   ┆ 1       ┆ 357850           ┆ "Viridiplantae"     ┆ 2                    ┆ 2017-03-29 18:35:53 ┆ 2017-03-29 18:35:53 │
│ 3   ┆ 1       ┆ 357850           ┆ "Streptophyta"      ┆ 3                    ┆ 2017-03-29 18:35:53 ┆ 2017-03-29 18:35:53 │
│ 4   ┆ 1       ┆ 357850           ┆ "Embryophyta"       ┆ 4                    ┆ 2017-03-29 18:35:53 ┆ 2017-03-29 18:35:53 │
│ 5   ┆ 1       ┆ 357850           ┆ "Tracheophyta"      ┆ 5                    ┆ 2017-03-29 18:35:53 ┆ 2017-03-29 18:35:53 │
└─────┴─────────┴──────────────────┴─────────────────────┴──────────────────────┴─────────────────────┴─────────────────────┘
Processing ../data/raw/foodb_2020_04_07_json/OntologySynonym.json
shape: (5, 11)
┌──────┬──────────────────┬───────────────────────┬─────────────┬───┬─────────┬─────────┬─────────────────────┬─────────────────────┐
│ id   ┆ ontology_term_id ┆ synonym               ┆ external_id ┆ … ┆ comment ┆ curator ┆ created_at          ┆ updated_at          │
│ ---  ┆ ---              ┆ ---                   ┆ ---         ┆   ┆ ---     ┆ ---     ┆ ---                 ┆ ---                 │
│ i64  ┆ i64              ┆ str                   ┆ null        ┆   ┆ null    ┆ null    ┆ datetime[μs]        ┆ datetime[μs]        │
╞══════╪══════════════════╪═══════════════════════╪═════════════╪═══╪═════════╪═════════╪═════════════════════╪═════════════════════╡
│ 3357 ┆ 8378             ┆ Hypercholesterolaemia ┆ null        ┆ … ┆ null    ┆ null    ┆ 2018-02-27 00:23:14 ┆ 2018-02-27 00:23:14 │
│ 3358 ┆ 8378             ┆ High cholesterol      ┆ null        ┆ … ┆ null    ┆ null    ┆ 2018-02-27 00:23:14 ┆ 2018-02-27 00:23:14 │
│ 3359 ┆ 10060            ┆ Sleeping              ┆ null        ┆ … ┆ null    ┆ null    ┆ 2018-02-27 00:23:14 ┆ 2018-02-27 00:23:14 │
│ 3360 ┆ 10051            ┆ Appetite              ┆ null        ┆ … ┆ null    ┆ null    ┆ 2018-02-27 00:23:14 ┆ 2018-02-27 00:23:14 │
│ 3361 ┆ 9333             ┆ Anti trypanosomic     ┆ null        ┆ … ┆ null    ┆ null    ┆ 2018-02-27 00:23:14 ┆ 2018-02-27 00:23:14 │
└──────┴──────────────────┴───────────────────────┴─────────────┴───┴─────────┴─────────┴─────────────────────┴─────────────────────┘
Processing ../data/raw/foodb_2020_04_07_json/NcbiTaxonomyMap.json
shape: (5, 5)
┌─────┬───────────────┬──────────────┬──────────────┬──────────────┐
│ id  ┆ TaxonomyName  ┆ Rank         ┆ created_at   ┆ updated_at   │
│ --- ┆ ---           ┆ ---          ┆ ---          ┆ ---          │
│ i64 ┆ str           ┆ str          ┆ datetime[μs] ┆ datetime[μs] │
╞═════╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ 1   ┆ Eukaryota     ┆ superkingdom ┆ null         ┆ null         │
│ 2   ┆ Viridiplantae ┆ kingdom      ┆ null         ┆ null         │
│ 3   ┆ Streptophyta  ┆ phylum       ┆ null         ┆ null         │
│ 4   ┆ Embryophyta   ┆ no rank      ┆ null         ┆ null         │
│ 5   ┆ Tracheophyta  ┆ no rank      ┆ null         ┆ null         │
└─────┴───────────────┴──────────────┴──────────────┴──────────────┘
Processing ../data/raw/foodb_2020_04_07_json/Food.json
shape: (5, 23)
┌─────┬───────────────┬────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───┬──────────┬──────────────────┬─────────────────┬───────────┐
│ id  ┆ name          ┆ name_scientific                ┆ description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ┆ … ┆ category ┆ ncbi_taxonomy_id ┆ export_to_foodb ┆ public_id │
│ --- ┆ ---           ┆ ---                            ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ┆   ┆ ---      ┆ ---              ┆ ---             ┆ ---       │
│ i64 ┆ str           ┆ str                            ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ┆   ┆ str      ┆ i64              ┆ bool            ┆ str       │
╞═════╪═══════════════╪════════════════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══╪══════════╪══════════════════╪═════════════════╪═══════════╡
│ 1   ┆ Angelica      ┆ Angelica keiskei               ┆ Angelica is a genus of about 60 species of tall biennial and perennial herbs in the family Apiaceae, native to temperate and subarctic regions of the Northern Hemisphere, reaching as far north as Iceland and Lapland. They grow to 1–3 m tall, with large bipinnate leaves and large compound umbels of white or greenish-white flowers. Some species can be found in purple moor and rush pastures.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ┆ … ┆ specific ┆ 357850           ┆ true            ┆ FOOD00001 │
│ 2   ┆ Savoy cabbage ┆ Brassica oleracea var. sabauda ┆ Savoy cabbage (Brassica oleracea convar. capitata var. sabauda L. ) is a variety of the cabbage, a cultivar of the plant species Brassica oleracea. Savoy cabbage is a winter vegetable. A variety of the savoy cabbage is the January King Cabbage. Savoy cabbage can be used in a variety of recipes. It pairs well with red wine, apples, spices, horseradish and meat. It can be used for roulades, in stews and soups, as well as roasted plain and drizzled with olive oil. Cabbage that is heavy for its size with leaves that are unblemished and have a bright, fresh look are signs of desirable quality. Whole cabbages are preferred whenever possible as pre-cut or preshredded cabbage has a greatly diminished vitamin content. Peak season for most cabbages runs from November through April. Fresh whole cabbage will keep in the refrigerator for one to six weeks depending on type and   ┆ … ┆ specific ┆ 1216010          ┆ true            ┆ FOOD00002 │
│     ┆               ┆                                ┆ variety. Hard green, white or red cabbages will keep the longest while the looser Savoy and Chinese varieties need to be con…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ┆   ┆          ┆                  ┆                 ┆           │
│ 3   ┆ Silver linden ┆ Tilia argentea                 ┆ Tilia tomentosa (Silver Lime in the UK and Silver Linden in the US) is a species of Tilia native to southeastern Europe and southwestern Asia, from Hungary and the Balkans east to western Turkey, occurring at moderate altitudes. It is a deciduous tree growing to 20–35 m tall, with a trunk up to 2 m diameter. The leaves are alternately arranged, rounded to triangular-ovate, 4–13 cm long and broad with a 2.5–4 cm petiole, green and mostly hairless above, densely white tomentose with white hairs below, and with a coarsely toothed margin. The flowers are pale yellow, hermaphrodite, produced in cymes of three to ten in mid to late summer with a pale green subtending leafy bract; they have a strong scent and are pollinated by honeybees. The nectar however contains sugars which cannot be digested by other bees, to whom the tree is somewhat toxic. The fruit is a dry        ┆ … ┆ specific ┆ null             ┆ true            ┆ FOOD00003 │
│     ┆               ┆                                ┆ nut-like drupe 8–10 mm long, downy, and slightly ribbed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ┆   ┆          ┆                  ┆                 ┆           │
│ 4   ┆ Kiwi          ┆ Actinidia chinensis            ┆ The kiwifruit, often shortened to kiwi in many parts of the world, is the edible berry of a woody vine in the genus Actinidia. The most common cultivar group of kiwifruit ('Hayward') is oval, about the size of a large hen's egg (5?8 centimetres in length and 4.5?5.5 centimetres in diameter). It has a fibrous, dull greenish-brown skin and bright green or golden flesh with rows of tiny, black, edible seeds. The fruit has a soft texture and a sweet but unique flavor, and today is a commercial crop in several countries, such as Italy, New Zealand, Chile, Greece and France.                                                                                                                                                                                                                                                                                                               ┆ … ┆ specific ┆ 3625             ┆ true            ┆ FOOD00004 │
│ 5   ┆ Allium        ┆ Allium                         ┆ Allium haematochiton is a species of wild onion known by the common name redskin onion. It is native to northern Baja California and southern California. It it grows on the slopes of the coastal hills and mountains, such as those of the Peninsular Ranges, Transverse Ranges, and southern California Coast Ranges.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ┆ … ┆ specific ┆ 4678             ┆ true            ┆ FOOD00005 │
└─────┴───────────────┴────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───┴──────────┴──────────────────┴─────────────────┴───────────┘
Processing ../data/raw/foodb_2020_04_07_json/Enzyme.json
shape: (5, 32)
┌─────┬──────────────────────────────────┬───────────┬─────────────┬───┬────────────┬────────────┬─────────────────────┬─────────────────────┐
│ id  ┆ name                             ┆ gene_name ┆ description ┆ … ┆ creator_id ┆ updater_id ┆ created_at          ┆ updated_at          │
│ --- ┆ ---                              ┆ ---       ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---                 ┆ ---                 │
│ i64 ┆ str                              ┆ str       ┆ null        ┆   ┆ null       ┆ null       ┆ datetime[μs]        ┆ datetime[μs]        │
╞═════╪══════════════════════════════════╪═══════════╪═════════════╪═══╪════════════╪════════════╪═════════════════════╪═════════════════════╡
│ 1   ┆ UDP-glucuronosyltransferase 2B28 ┆ UGT2B28   ┆ null        ┆ … ┆ null       ┆ null       ┆ 2015-02-23 22:40:56 ┆ 2015-02-23 22:40:56 │
│ 2   ┆ Estrogen receptor beta           ┆ ESR2      ┆ null        ┆ … ┆ null       ┆ null       ┆ 2015-02-23 22:40:57 ┆ 2015-02-23 22:40:57 │
│ 3   ┆ UDP-glucuronosyltransferase 2B4  ┆ UGT2B4    ┆ null        ┆ … ┆ null       ┆ null       ┆ 2015-02-23 22:40:57 ┆ 2015-02-23 22:40:57 │
│ 4   ┆ UDP-glucuronosyltransferase 1-4  ┆ UGT1A4    ┆ null        ┆ … ┆ null       ┆ null       ┆ 2015-02-23 22:40:57 ┆ 2015-02-23 22:40:57 │
│ 5   ┆ UDP-glucuronosyltransferase 2B10 ┆ UGT2B10   ┆ null        ┆ … ┆ null       ┆ null       ┆ 2015-02-23 22:40:57 ┆ 2015-02-23 22:40:57 │
└─────┴──────────────────────────────────┴───────────┴─────────────┴───┴────────────┴────────────┴─────────────────────┴─────────────────────┘
Processing ../data/raw/foodb_2020_04_07_json/Nutrient.json
shape: (5, 22)
┌─────┬───────────┬───────────┬─────────────────┬───┬────────────┬────────────┬─────────────────────┬─────────────────────┐
│ id  ┆ legacy_id ┆ public_id ┆ name            ┆ … ┆ creator_id ┆ updater_id ┆ created_at          ┆ updated_at          │
│ --- ┆ ---       ┆ ---       ┆ ---             ┆   ┆ ---        ┆ ---        ┆ ---                 ┆ ---                 │
│ i64 ┆ i64       ┆ str       ┆ str             ┆   ┆ null       ┆ null       ┆ datetime[μs]        ┆ datetime[μs]        │
╞═════╪═══════════╪═══════════╪═════════════════╪═══╪════════════╪════════════╪═════════════════════╪═════════════════════╡
│ 1   ┆ 10930     ┆ FDBN00001 ┆ Fat             ┆ … ┆ null       ┆ null       ┆ 2014-11-05 13:42:10 ┆ 2014-11-05 13:42:10 │
│ 2   ┆ 10946     ┆ FDBN00002 ┆ Proteins        ┆ … ┆ null       ┆ null       ┆ 2014-11-05 13:42:15 ┆ 2014-11-05 13:42:15 │
│ 3   ┆ 16037     ┆ FDBN00003 ┆ Carbohydrate    ┆ … ┆ null       ┆ null       ┆ 2014-11-05 13:44:06 ┆ 2014-11-05 13:44:06 │
│ 4   ┆ 23404     ┆ FDBN00004 ┆ Fatty acids     ┆ … ┆ null       ┆ null       ┆ 2014-11-05 13:46:00 ┆ 2014-11-05 13:46:00 │
│ 5   ┆ 11134     ┆ FDBN00005 ┆ Fiber (dietary) ┆ … ┆ null       ┆ null       ┆ 2014-11-05 13:47:36 ┆ 2014-11-05 13:47:36 │

These tables were too wide even with the wider settings
OntologySynonym
Food
Enzyme
Nutrient
Reference
OntologyTerm
Content
HealthEffect

Other fields, need to check for data types
external_id
comment
curator
creator_id
updater_id

In [ ]:
# instead of getting df.head(), can i just print the columns and their data types?
# maybe `glimpse`

for filename in os.listdir(json_path):
    if filename.endswith(".json"):
        df_label = filename[:-5]
        date_columns = ["created_at", "updated_at"]
        print(f"Processing {os.path.join(json_path, filename)}")
        df = pl.read_ndjson(os.path.join(json_path, filename))
        df = df.with_columns(
            cs.by_name(date_columns, require_all=False).cast(pl.Datetime)
        )
        print(df.glimpse())

Processing ../data/raw/foodb_2020_04_07_json/FoodTaxonomy.json
Rows: 889
Columns: 7
$ id                            <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ food_id                       <i64> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
$ ncbi_taxonomy_id              <i64> 357850, 357850, 357850, 357850, 357850, 357850, 357850, 357850, 357850, 357850
$ classification_name           <str> '"Eukaryota"', '"Viridiplantae"', '"Streptophyta"', '"Embryophyta"', '"Tracheophyta"', '"Spermatophyta"', '"Magnoliophyta"', '"eudicotyledons"', '"Gunneridae"', '"Pentapetalae"'
$ classification_order          <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ created_at           <datetime[μs]> 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53
$ updated_at           <datetime[μs]> 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53, 2017-03-29 18:35:53

None
Processing ../data/raw/foodb_2020_04_07_json/OntologySynonym.json
Rows: 1669
Columns: 11
$ id                        <i64> 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366
$ ontology_term_id          <i64> 8378, 8378, 10060, 10051, 9333, 9333, 9333, 9333, 8986, 8527
$ synonym                   <str> 'Hypercholesterolaemia', 'High cholesterol', 'Sleeping', 'Appetite', 'Anti trypanosomic', 'Trypanocide', 'Trypanosomicidal agents', 'Trypanocidal agent', 'Gsd type ix', 'Drta'
$ external_id              <null> None, None, None, None, None, None, None, None, None, None
$ external_srouce          <null> None, None, None, None, None, None, None, None, None, None
$ parent_id                <null> None, None, None, None, None, None, None, None, None, None
$ parent_source            <null> None, None, None, None, None, None, None, None, None, None
$ comment                  <null> None, None, None, None, None, None, None, None, None, None
$ curator                  <null> None, None, None, None, None, None, None, None, None, None
$ created_at       <datetime[μs]> 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:15, 2018-02-27 00:23:15, 2018-02-27 00:23:15, 2018-02-27 00:23:15
$ updated_at       <datetime[μs]> 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:14, 2018-02-27 00:23:15, 2018-02-27 00:23:15, 2018-02-27 00:23:15, 2018-02-27 00:23:15

None
Processing ../data/raw/foodb_2020_04_07_json/NcbiTaxonomyMap.json
Rows: 242
Columns: 5
$ id                    <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ TaxonomyName          <str> 'Eukaryota', 'Viridiplantae', 'Streptophyta', 'Embryophyta', 'Tracheophyta', 'Spermatophyta', 'Magnoliophyta', 'eudicotyledons', 'Gunneridae', 'Pentapetalae'
$ Rank                  <str> 'superkingdom', 'kingdom', 'phylum', 'no rank', 'no rank', 'no rank', 'no rank', 'no rank', 'no rank', 'no rank'
$ created_at   <datetime[μs]> None, None, None, None, None, None, None, None, None, None
$ updated_at   <datetime[μs]> None, None, None, None, None, None, None, None, None, None

None
Processing ../data/raw/foodb_2020_04_07_json/Food.json
Rows: 992
Columns: 23
$ id                            <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ name                          <str> 'Angelica', 'Savoy cabbage', 'Silver linden', 'Kiwi', 'Allium', 'Garden onion', 'Leek', 'Garlic', 'Chives', 'Lemon verbena'
$ name_scientific               <str> 'Angelica keiskei', 'Brassica oleracea var. sabauda', 'Tilia argentea', 'Actinidia chinensis', 'Allium', 'Allium cepa', 'Allium porrum', 'Allium sativum', 'Allium schoenoprasum', 'Aloysia triphylla'
$ description                   <str> 'Angelica is a genus of about 60 species of tall biennial and perennial herbs in the family Apiaceae, native to temperate and subarctic regions of the Northern Hemisphere, reaching as far north as Iceland and Lapland. They grow to 1–3 m tall, with large bipinnate leaves and large compound umbels of white or greenish-white flowers. Some species can be found in purple moor and rush pastures.', 'Savoy cabbage (Brassica oleracea convar. capitata var. sabauda L. ) is a variety of the cabbage, a cultivar of the plant species Brassica oleracea. Savoy cabbage is a winter vegetable. A variety of the savoy cabbage is the January King Cabbage. Savoy cabbage can be used in a variety of recipes. It pairs well with red wine, apples, spices, horseradish and meat. It can be used for roulades, in stews and soups, as well as roasted plain and drizzled with olive oil. Cabbage that is heavy for its size with leaves that are unblemished and have a bright, fresh look are signs of desirable quality. Whole cabbages are preferred whenever possible as pre-cut or preshredded cabbage has a greatly diminished vitamin content. Peak season for most cabbages runs from November through April. Fresh whole cabbage will keep in the refrigerator for one to six weeks depending on type and variety. Hard green, white or red cabbages will keep the longest while the looser Savoy and Chinese varieties need to be consumed more quickly. It is necessary to keep the outer leaves intact without washing when storing since moisture hastens decay. Cabbage provides fiber, vitamins A, C, K and B6, folate, potassium, manganese, thiamin, calcium, iron and magnesium.', 'Tilia tomentosa (Silver Lime in the UK and Silver Linden in the US) is a species of Tilia native to southeastern Europe and southwestern Asia, from Hungary and the Balkans east to western Turkey, occurring at moderate altitudes. It is a deciduous tree growing to 20–35 m tall, with a trunk up to 2 m diameter. The leaves are alternately arranged, rounded to triangular-ovate, 4–13\xa0cm long and broad with a 2.5–4\xa0cm petiole, green and mostly hairless above, densely white tomentose with white hairs below, and with a coarsely toothed margin. The flowers are pale yellow, hermaphrodite, produced in cymes of three to ten in mid to late summer with a pale green subtending leafy bract; they have a strong scent and are pollinated by honeybees. The nectar however contains sugars which cannot be digested by other bees, to whom the tree is somewhat toxic. The fruit is a dry nut-like drupe 8–10\xa0mm long, downy, and slightly ribbed.', "The kiwifruit, often shortened to kiwi in many parts of the world, is the edible berry of a woody vine in the genus Actinidia. The most common cultivar group of kiwifruit ('Hayward') is oval, about the size of a large hen's egg (5?8 centimetres in length and 4.5?5.5 centimetres in diameter). It has a fibrous, dull greenish-brown skin and bright green or golden flesh with rows of tiny, black, edible seeds. The fruit has a soft texture and a sweet but unique flavor, and today is a commercial crop in several countries, such as Italy, New Zealand, Chile, Greece and France.", 'Allium haematochiton is a species of wild onion known by the common name redskin onion. It is native to northern Baja California and southern California. It it grows on the slopes of the coastal hills and mountains, such as those of the Peninsular Ranges, Transverse Ranges, and southern California Coast Ranges.', 'The onion (Allium cepa) (Latin \'cepa\' = onion), also known as the bulb onion or common onion, is used as a vegetable and is the most widely cultivated species of the genus Allium. This genus also contains several other species variously referred to as onions and cultivated for food, such as the Japanese bunching onion (A. fistulosum), the Egyptian onion (A. ×proliferum), and the Canada onion (A. canadense). The name "wild onion" is applied to a number of Allium species but A. cepa is exclusively known from cultivation and its ancestral wild original form is not known, although escapes from cultivation have become established in some regions.The onion is most frequently a biennial or a perennial plant, but is usually treated as an annual and harvested in its first growing season.\r\nOnions are cultivated and used around the world. As a foodstuff they are usually served cooked, as a vegetable or part of a prepared savoury dish, but can also be eaten raw or used to make pickles or chutneys. They are pungent when chopped and contain certain chemical substances which irritate the eyes. Onions contain phenolics and flavonoids that have potential anti-inflammatory, anti-cholesterol, anticancer and antioxidant properties.', 'The leek is a vegetable that belongs, along with onion and garlic, to the genus Allium, currently placed in family Amaryllidaceae, subfamily Allioideae. Historically many scientific names were used for leeks, which are now treated as cultivars of Allium ampeloprasum. Two related vegetables, elephant garlic and kurrat, are also cultivars of A. \xa0ampeloprasum, although different in their uses as food. The edible part of the leek plant is a bundle of leaf sheaths that is sometimes erroneously called a stem or stalk.', 'With a history of human use of over 7,000 years, garlic (Allium sativum) is native to central Asia, and has long been a staple in the Mediterranean region, as well as a frequent seasoning in Asia, Africa, and Europe. There are two sub-varieties of allium sativum: Allium sativum var. sativum (soft-necked garlic) and Allium sativum var. ophioscorodon (hard-necked garlic). Soft-necked garlic is the most commonly found. Bulb garlic is available in many forms, including fresh, frozen, dried, fermented (black garlic) and shelf stable products (in tubes or jars). [Wikipedia]', 'Chives is the common name of Allium schoenoprasum, the smallest species of the edible onions. A perennial plant, it is native to Europe, Asia and North America. A. schoenoprasum is the only species of Allium native to both the New and the Old Worlds. The name of the species derives from the Greek skhoínos and práson. Its English name, chives, derives from the French word cive, from cepa, the Latin word for onion. Chives are a commonly used herb and can be found in grocery stores or grown in home gardens. In culinary use, the scapes are diced and used as an ingredient for fish, potatoes, soups, and other dishes. Chives have insect-repelling properties that can be used in gardens to control pests.', 'Aloysia citrodora is a species of flowering plant in the verbena family Verbenaceae, native to northwestern Argentina and southern Bolivia. Common names include lemon verbena and lemon beebrush. It was brought to Europe by the Spanish and the Portuguese in the 17th century.'
$ itis_id                       <str> '', None, '845789', '506775', '42634', '42720', '42659', '42652', '42636', '32135'
$ wikipedia_id                  <str> 'Angelica', 'Savoy cabbage', 'Tilia tomentosa', 'Kiwifruit', 'Allium haematochiton', 'Onion', 'Leek', 'Garlic', 'Chives', 'Aloysia citrodora'
$ picture_file_name             <str> '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg'
$ picture_content_type          <str> 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg'
$ picture_file_size             <i64> 111325, 155178, 56367, 110661, 341911, 138437, 4857, 545294, 1411537, 142723
$ picture_updated_at            <str> '2012-04-20T09:29:57.000Z', '2012-04-20T09:39:54.000Z', '2012-04-20T09:41:25.000Z', '2012-04-20T09:32:21.000Z', '2012-04-20T09:37:44.000Z', '2012-04-20T09:41:21.000Z', '2012-04-20T09:33:40.000Z', '2012-04-20T09:42:05.000Z', '2012-04-20T09:42:09.000Z', '2012-04-20T09:32:16.000Z'
$ legacy_id                     <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ food_group                    <str> 'Herbs and Spices', 'Vegetables', 'Herbs and Spices', 'Fruits', 'Vegetables', 'Vegetables', 'Vegetables', 'Herbs and Spices', 'Herbs and Spices', 'Herbs and Spices'
$ food_subgroup                 <str> 'Herbs', 'Cabbages', 'Herbs', 'Tropical fruits', 'Onion-family vegetables', 'Onion-family vegetables', 'Onion-family vegetables', 'Herbs', 'Herbs', 'Herbs'
$ food_type                     <str> 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1'
$ created_at           <datetime[μs]> 2011-02-09 00:37:14, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15
$ updated_at           <datetime[μs]> 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-17 16:19:45, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13
$ creator_id                   <null> None, None, None, None, None, None, None, None, None, None
$ updater_id                    <i64> 2, None, None, None, None, None, None, 2, None, None
$ export_to_afcdb              <bool> False, False, False, False, False, True, False, True, False, False
$ category                      <str> 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific'
$ ncbi_taxonomy_id              <i64> 357850, 1216010, None, 3625, 4678, 4679, None, 4682, 74900, 542672
$ export_to_foodb              <bool> True, True, True, True, True, True, True, True, True, True
$ public_id                     <str> 'FOOD00001', 'FOOD00002', 'FOOD00003', 'FOOD00004', 'FOOD00005', 'FOOD00006', 'FOOD00007', 'FOOD00008', 'FOOD00009', 'FOOD00010'

None
Processing ../data/raw/foodb_2020_04_07_json/Enzyme.json
Rows: 1744
Columns: 32
$ id                             <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ name                           <str> 'UDP-glucuronosyltransferase 2B28', 'Estrogen receptor beta', 'UDP-glucuronosyltransferase 2B4', 'UDP-glucuronosyltransferase 1-4', 'UDP-glucuronosyltransferase 2B10', 'UDP-glucuronosyltransferase 2B7', 'UDP-glucuronosyltransferase 2B15', 'UDP-glucuronosyltransferase 2A1', 'UDP-glucuronosyltransferase 1-1', 'UDP-glucuronosyltransferase 1-9'
$ gene_name                      <str> 'UGT2B28', 'ESR2', 'UGT2B4', 'UGT1A4', 'UGT2B10', 'UGT2B7', 'UGT2B15', 'UGT2A1', 'UGT1A1', 'UGT1A9'
$ description                   <null> None, None, None, None, None, None, None, None, None, None
$ go_classification             <null> None, None, None, None, None, None, None, None, None, None
$ general_function              <null> None, None, None, None, None, None, None, None, None, None
$ specific_function             <null> None, None, None, None, None, None, None, None, None, None
$ pathway                       <null> None, None, None, None, None, None, None, None, None, None
$ reaction                      <null> None, None, None, None, None, None, None, None, None, None
$ cellular_location             <null> None, None, None, None, None, None, None, None, None, None
$ signals                       <null> None, None, None, None, None, None, None, None, None, None
$ transmembrane_regions         <null> None, None, None, None, None, None, None, None, None, None
$ molecular_weight              <null> None, None, None, None, None, None, None, None, None, None
$ theoretical_pi                <null> None, None, None, None, None, None, None, None, None, None
$ locus                         <null> None, None, None, None, None, None, None, None, None, None
$ chromosome                    <null> None, None, None, None, None, None, None, None, None, None
$ uniprot_name                  <null> None, None, None, None, None, None, None, None, None, None
$ uniprot_id                     <str> 'Q9BY64', 'Q92731', 'P06133', 'P22310', 'P36537', 'P16662', 'P54855', 'Q9Y4X1', 'P22309', 'O60656'
$ pdb_id                        <null> None, None, None, None, None, None, None, None, None, None
$ genbank_protein_id            <null> None, None, None, None, None, None, None, None, None, None
$ genbank_gene_id               <null> None, None, None, None, None, None, None, None, None, None
$ genecard_id                   <null> None, None, None, None, None, None, None, None, None, None
$ genatlas_id                   <null> None, None, None, None, None, None, None, None, None, None
$ hgnc_id                       <null> None, None, None, None, None, None, None, None, None, None
$ hprd_id                       <null> None, None, None, None, None, None, None, None, None, None
$ organism                      <null> None, None, None, None, None, None, None, None, None, None
$ general_citations             <null> None, None, None, None, None, None, None, None, None, None
$ comments                      <null> None, None, None, None, None, None, None, None, None, None
$ creator_id                    <null> None, None, None, None, None, None, None, None, None, None
$ updater_id                    <null> None, None, None, None, None, None, None, None, None, None
$ created_at            <datetime[μs]> 2015-02-23 22:40:56, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57
$ updated_at            <datetime[μs]> 2015-02-23 22:40:56, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57, 2015-02-23 22:40:57

None
Processing ../data/raw/foodb_2020_04_07_json/Nutrient.json
Rows: 39
Columns: 22
$ id                           <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ legacy_id                    <i64> 10930, 10946, 16037, 23404, 11134, 58893, 58894, 58895, 58896, 58897
$ public_id                    <str> 'FDBN00001', 'FDBN00002', 'FDBN00003', 'FDBN00004', 'FDBN00005', 'FDBN00006', 'FDBN00007', 'FDBN00008', 'FDBN00009', 'FDBN00010'
$ name                         <str> 'Fat', 'Proteins', 'Carbohydrate', 'Fatty acids', 'Fiber (dietary)', '13:0', '14:1', '15:1', '16:1 c', '16:1 t'
$ export                      <bool> False, False, False, False, False, False, False, False, False, False
$ state                       <null> None, None, None, None, None, None, None, None, None, None
$ annotation_quality           <str> 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low'
$ description                  <str> None, None, 'Carbohydrates (or saccharides) are organic compounds with the empirical formula Cm(H2O)n. The carbohydrates  are divided into four chemical groupings: monosaccharides, disaccharides, oligosaccharides, and polysaccharides. The monosaccharides and disaccharides are commonly referred to as sugars. [Wikipedia]', None, None, None, None, None, None, None
$ wikipedia_id                 <str> None, None, 'Carbohydrate', None, None, None, None, None, None, None
$ comments                    <null> None, None, None, None, None, None, None, None, None, None
$ dfc_id                      <null> None, None, None, None, None, None, None, None, None, None
$ duke_id                      <str> 'FAT', 'PROTEIN|PROTEINS', 'CARBOHYDRATE|CARBOHYDRATES', 'FATTY-ACIDS', 'FIBER(DIETARY)', None, None, None, None, None
$ eafus_id                     <str> None, None, None, '1335', None, None, None, None, None, None
$ dfc_name                    <null> None, None, None, None, None, None, None, None, None, None
$ compound_source              <str> 'DUKE', 'DUKE', 'DUKE', 'EAFUS', 'DUKE', 'TABLES', 'TABLES', 'TABLES', 'TABLES', 'TABLES'
$ metabolism                  <null> None, None, None, None, None, None, None, None, None, None
$ synthesis_citations         <null> None, None, None, None, None, None, None, None, None, None
$ general_citations           <null> None, None, None, None, None, None, None, None, None, None
$ creator_id                  <null> None, None, None, None, None, None, None, None, None, None

In [ ]:
for filename in os.listdir(json_path):
    if filename.endswith(".json"):
        df_label = filename[:-5]
        date_columns = ["created_at", "updated_at"]
        print(f"Processing {os.path.join(json_path, filename)}")
        df = pl.read_ndjson(os.path.join(json_path, filename))
        df = df.with_columns(
            cs.by_name(date_columns, require_all=False).cast(pl.Datetime)
        )
        print(df.describe())

Processing ../data/raw/foodb_2020_04_07_json/FoodTaxonomy.json
shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ id         ┆ food_id    ┆ ncbi_taxo ┆ classific ┆ classific ┆ created_a ┆ updated_a │
│ ---        ┆ ---        ┆ ---        ┆ nomy_id   ┆ ation_nam ┆ ation_ord ┆ t         ┆ t         │
│ str        ┆ f64        ┆ f64        ┆ ---       ┆ e         ┆ er        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆ f64       ┆ ---       ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆           ┆ str       ┆ f64       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 889.0      ┆ 889.0      ┆ 889.0     ┆ 889       ┆ 889.0     ┆ 889       ┆ 889       │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0         ┆ 0.0       ┆ 0         ┆ 0         │
│ mean       ┆ 461.805399 ┆ 468.755906 ┆ 107470.01 ┆ null      ┆ 8.088864  ┆ 2017-03-2 ┆ 2017-03-2 │
│            ┆            ┆            ┆ 7998      ┆           ┆           ┆ 9 18:36:0 ┆ 9 18:36:0 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 0.057367  ┆ 0.057367  │
│ std        ┆ 269.259761 ┆ 284.173069 ┆ 158486.07 ┆ null      ┆ 4.612212  ┆ null      ┆ null      │
│            ┆            ┆            ┆ 961       ┆           ┆           ┆           ┆           │
│ min        ┆ 1.0        ┆ 1.0        ┆ 2708.0    ┆ "Acanthom ┆ 1.0       ┆ 2017-03-2 ┆ 2017-03-2 │
│            ┆            ┆            ┆           ┆ orphata"  ┆           ┆ 9         ┆ 9         │
│            ┆            ┆            ┆           ┆           ┆           ┆ 18:35:53  ┆ 18:35:53  │
│ 25%        ┆ 223.0      ┆ 218.0      ┆ 6544.0    ┆ null      ┆ 4.0       ┆ 2017-03-2 ┆ 2017-03-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 9         ┆ 9         │
│            ┆            ┆            ┆           ┆           ┆           ┆ 18:35:57  ┆ 18:35:57  │
│ 50%        ┆ 460.0      ┆ 453.0      ┆ 59499.0   ┆ null      ┆ 8.0       ┆ 2017-03-2 ┆ 2017-03-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 9         ┆ 9         │
│            ┆            ┆            ┆           ┆           ┆           ┆ 18:36:00  ┆ 18:36:00  │
│ 75%        ┆ 697.0      ┆ 786.0      ┆ 153159.0  ┆ null      ┆ 12.0      ┆ 2017-03-2 ┆ 2017-03-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 9         ┆ 9         │
│            ┆            ┆            ┆           ┆           ┆           ┆ 18:36:03  ┆ 18:36:03  │
│ max        ┆ 919.0      ┆ 909.0      ┆ 941588.0  ┆ "rosids"  ┆ 18.0      ┆ 2017-03-2 ┆ 2017-03-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 9         ┆ 9         │
│            ┆            ┆            ┆           ┆           ┆           ┆ 18:36:06  ┆ 18:36:06  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
Processing ../data/raw/foodb_2020_04_07_json/OntologySynonym.json
shape: (9, 12)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬─────────┬───────────┬───────────┐
│ statistic  ┆ id         ┆ ontology_t ┆ synonym   ┆ … ┆ comment ┆ curator ┆ created_a ┆ updated_a │
│ ---        ┆ ---        ┆ erm_id     ┆ ---       ┆   ┆ ---     ┆ ---     ┆ t         ┆ t         │
│ str        ┆ f64        ┆ ---        ┆ str       ┆   ┆ f64     ┆ f64     ┆ ---       ┆ ---       │
│            ┆            ┆ f64        ┆           ┆   ┆         ┆         ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═════════╪═══════════╪═══════════╡
│ count      ┆ 1669.0     ┆ 1669.0     ┆ 1669      ┆ … ┆ 0.0     ┆ 0.0     ┆ 1669      ┆ 1669      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0         ┆ … ┆ 1669.0  ┆ 1669.0  ┆ 0         ┆ 0         │
│ mean       ┆ 4191.0     ┆ 8881.98741 ┆ null      ┆ … ┆ null    ┆ null    ┆ 2018-02-2 ┆ 2018-02-2 │
│            ┆            ┆ 8          ┆           ┆   ┆         ┆         ┆ 7 00:23:4 ┆ 7 00:23:4 │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 2.416416  ┆ 2.416416  │
│ std        ┆ 481.943116 ┆ 610.500586 ┆ null      ┆ … ┆ null    ┆ null    ┆ null      ┆ null      │
│ min        ┆ 3357.0     ┆ 7681.0     ┆ 'childhoo ┆ … ┆ null    ┆ null    ┆ 2018-02-2 ┆ 2018-02-2 │
│            ┆            ┆            ┆ d renal   ┆   ┆         ┆         ┆ 7         ┆ 7         │
│            ┆            ┆            ┆ wilms     ┆   ┆         ┆         ┆ 00:23:14  ┆ 00:23:14  │
│            ┆            ┆            ┆ tumor'	…  ┆   ┆         ┆         ┆           ┆           │
│ 25%        ┆ 3774.0     ┆ 8481.0     ┆ null      ┆ … ┆ null    ┆ null    ┆ 2018-02-2 ┆ 2018-02-2 │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 7         ┆ 7         │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 00:23:29  ┆ 00:23:29  │
│ 50%        ┆ 4191.0     ┆ 8913.0     ┆ null      ┆ … ┆ null    ┆ null    ┆ 2018-02-2 ┆ 2018-02-2 │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 7         ┆ 7         │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 00:23:43  ┆ 00:23:43  │
│ 75%        ┆ 4608.0     ┆ 9247.0     ┆ null      ┆ … ┆ null    ┆ null    ┆ 2018-02-2 ┆ 2018-02-2 │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 7         ┆ 7         │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 00:23:55  ┆ 00:23:55  │
│ max        ┆ 5025.0     ┆ 10113.0    ┆  neurolog ┆ … ┆ null    ┆ null    ┆ 2018-02-2 ┆ 2018-02-2 │
│            ┆            ┆            ┆ ic system ┆   ┆         ┆         ┆ 7         ┆ 7         │
│            ┆            ┆            ┆           ┆   ┆         ┆         ┆ 00:24:12  ┆ 00:24:12  │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴─────────┴───────────┴───────────┘
Processing ../data/raw/foodb_2020_04_07_json/NcbiTaxonomyMap.json
shape: (9, 6)
┌────────────┬───────────┬─────────────────┬───────┬────────────┬────────────┐
│ statistic  ┆ id        ┆ TaxonomyName    ┆ Rank  ┆ created_at ┆ updated_at │
│ ---        ┆ ---       ┆ ---             ┆ ---   ┆ ---        ┆ ---        │
│ str        ┆ f64       ┆ str             ┆ str   ┆ str        ┆ str        │
╞════════════╪═══════════╪═════════════════╪═══════╪════════════╪════════════╡
│ count      ┆ 242.0     ┆ 242             ┆ 242   ┆ 0          ┆ 0          │
│ null_count ┆ 0.0       ┆ 0               ┆ 0     ┆ 242        ┆ 242        │
│ mean       ┆ 121.5     ┆ null            ┆ null  ┆ null       ┆ null       │
│ std        ┆ 70.003571 ┆ null            ┆ null  ┆ null       ┆ null       │
│ min        ┆ 1.0       ┆ Acanthomorphata ┆ class ┆ null       ┆ null       │
│ 25%        ┆ 61.0      ┆ null            ┆ null  ┆ null       ┆ null       │
│ 50%        ┆ 122.0     ┆ null            ┆ null  ┆ null       ┆ null       │
│ 75%        ┆ 182.0     ┆ null            ┆ null  ┆ null       ┆ null       │
│ max        ┆ 242.0     ┆ rosids          ┆ tribe ┆ null       ┆ null       │
└────────────┴───────────┴─────────────────┴───────┴────────────┴────────────┘
Processing ../data/raw/foodb_2020_04_07_json/Food.json
shape: (9, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ statistic ┆ id        ┆ name      ┆ name_scie ┆ … ┆ category ┆ ncbi_taxo ┆ export_to ┆ public_id │
│ ---       ┆ ---       ┆ ---       ┆ ntific    ┆   ┆ ---      ┆ nomy_id   ┆ _foodb    ┆ ---       │
│ str       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ---       ┆ str       │
│           ┆           ┆           ┆ str       ┆   ┆          ┆ f64       ┆ f64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 992.0     ┆ 992       ┆ 683       ┆ … ┆ 901      ┆ 619.0     ┆ 992.0     ┆ 992       │
│ null_coun ┆ 0.0       ┆ 0         ┆ 309       ┆ … ┆ 91       ┆ 373.0     ┆ 0.0       ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ mean      ┆ 509.63810 ┆ null      ┆ null      ┆ … ┆ null     ┆ 99958.252 ┆ 0.803427  ┆ null      │
│           ┆ 5         ┆           ┆           ┆   ┆          ┆ 019       ┆           ┆           │
│ std       ┆ 298.10539 ┆ null      ┆ null      ┆ … ┆ null     ┆ 198751.62 ┆ null      ┆ null      │
│           ┆ 2         ┆           ┆           ┆   ┆          ┆ 9015      ┆           ┆           │
│ min       ┆ 1.0       ┆ Abalone   ┆           ┆ … ┆ generic  ┆ 2706.0    ┆ 0.0       ┆ FOOD00001 │
│ 25%       ┆ 249.0     ┆ null      ┆ null      ┆ … ┆ null     ┆ 6448.0    ┆ null      ┆ null      │
│ 50%       ┆ 508.0     ┆ null      ┆ null      ┆ … ┆ null     ┆ 29965.0   ┆ null      ┆ null      │
│ 75%       ┆ 769.0     ┆ null      ┆ null      ┆ … ┆ null     ┆ 108881.0  ┆ null      ┆ null      │
│ max       ┆ 1024.0    ┆ linseed   ┆ Zoarces   ┆ … ┆ specific ┆ 1.574408e ┆ 1.0       ┆ FOOD00992 │
│           ┆           ┆ oil       ┆ americanu ┆   ┆          ┆ 6         ┆           ┆           │
│           ┆           ┆           ┆ s         ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘
Processing ../data/raw/foodb_2020_04_07_json/Enzyme.json
shape: (9, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id        ┆ name      ┆ gene_name ┆ … ┆ creator_i ┆ updater_i ┆ created_a ┆ updated_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ d         ┆ d         ┆ t         ┆ at       │
│ str       ┆ f64       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1744.0    ┆ 1744      ┆ 1744      ┆ … ┆ 0.0       ┆ 0.0       ┆ 1744      ┆ 1744     │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 1744.0    ┆ 1744.0    ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 872.5     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2015-02-2 ┆ 2015-02- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4 07:04:1 ┆ 24 07:04 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3.401376  ┆ :13.4013 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 76       │
│ std       ┆ 503.59375 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1.0       ┆ 1,2-dihyd ┆ A4GALT    ┆ … ┆ null      ┆ null      ┆ 2015-02-2 ┆ 2015-02- │
│           ┆           ┆ roxy-3-ke ┆           ┆   ┆           ┆           ┆ 3         ┆ 23       │
│           ┆           ┆ to-5-meth ┆           ┆   ┆           ┆           ┆ 22:40:56  ┆ 22:40:56 │
│           ┆           ┆ ylt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 437.0     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2015-02-2 ┆ 2015-02- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 23       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:27:36  ┆ 23:27:36 │
│ 50%       ┆ 873.0     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2015-02-2 ┆ 2015-02- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 00:43:23  ┆ 00:43:23 │
│ 75%       ┆ 1308.0    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2015-02-2 ┆ 2015-02- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 22:30:24  ┆ 22:30:24 │
│ max       ┆ 1744.0    ┆ tRNA pseu ┆ pcap      ┆ … ┆ null      ┆ null      ┆ 2015-02-2 ┆ 2015-02- │
│           ┆           ┆ douridine ┆           ┆   ┆           ┆           ┆ 5         ┆ 25       │
│           ┆           ┆ synthase- ┆           ┆   ┆           ┆           ┆ 00:27:36  ┆ 00:27:36 │
│           ┆           ┆ li…       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘
Processing ../data/raw/foodb_2020_04_07_json/Nutrient.json
shape: (9, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id        ┆ legacy_id ┆ public_id ┆ … ┆ creator_i ┆ updater_i ┆ created_a ┆ updated_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ d         ┆ d         ┆ t         ┆ at       │
│ str       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 39.0      ┆ 38.0      ┆ 39        ┆ … ┆ 0.0       ┆ 0.0       ┆ 39        ┆ 39       │
│ null_coun ┆ 0.0       ┆ 1.0       ┆ 0         ┆ … ┆ 39.0      ┆ 39.0      ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 20.0      ┆ 53064.5   ┆ null      ┆ … ┆ null      ┆ null      ┆ 2014-12-1 ┆ 2014-12- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9 23:16:5 ┆ 19 23:16 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5.538461  ┆ :55.5384 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 61       │
│ std       ┆ 11.401754 ┆ 15321.324 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 207       ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1.0       ┆ 10930.0   ┆ FDBN00001 ┆ … ┆ null      ┆ null      ┆ 2014-11-0 ┆ 2014-11- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 13:42:10  ┆ 13:42:10 │
│ 25%       ┆ 11.0      ┆ 58897.0   ┆ null      ┆ … ┆ null      ┆ null      ┆ 2014-11-0 ┆ 2014-11- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 13:50:04  ┆ 13:50:04 │
│ 50%       ┆ 20.0      ┆ 58907.0   ┆ null      ┆ … ┆ null      ┆ null      ┆ 2014-11-0 ┆ 2014-11- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 13:53:26  ┆ 13:53:26 │
│ 75%       ┆ 30.0      ┆ 58916.0   ┆ null      ┆ … ┆ null      ┆ null      ┆ 2014-11-0 ┆ 2014-11- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 13:59:36  ┆ 13:59:36 │
│ max       ┆ 39.0      ┆ 58928.0   ┆ FDBN00039 ┆ … ┆ null      ┆ null      ┆ 2019-08-0 ┆ 2019-08- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 19:45:58  ┆ 19:45:58 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘
Processing ../data/raw/foodb_2020_04_07_json/Reference.json
shape: (9, 13)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ id        ┆ ref_type ┆ text      ┆ … ┆ created_a ┆ updated_a ┆ source_id ┆ source_ty │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ t         ┆ t         ┆ ---       ┆ pe        │
│ str       ┆ f64       ┆ str      ┆ str       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆ str       ┆           ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 31778.0   ┆ 31778    ┆ 31778     ┆ … ┆ 31778     ┆ 31778     ┆ 31778.0   ┆ 31778     │
│ null_coun ┆ 0.0       ┆ 0        ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0         │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 15898.035 ┆ null     ┆ null      ┆ … ┆ 2015-02-2 ┆ 2015-02-2 ┆ 15672.574 ┆ null      │
│           ┆ 182       ┆          ┆           ┆   ┆ 4 11:38:4 ┆ 4 11:38:4 ┆ 454       ┆           │
│           ┆           ┆          ┆           ┆   ┆ 0.196519  ┆ 0.196519  ┆           ┆           │
│ std       ┆ 9177.3776 ┆ null     ┆ null      ┆ … ┆ null      ┆ null      ┆ 7944.4185 ┆ null      │
│           ┆ 83        ┆          ┆           ┆   ┆           ┆           ┆ 3         ┆           │
│ min       ┆ 1.0       ┆ general  ┆ 'T Hart   ┆ … ┆ 2015-02-2 ┆ 2015-02-2 ┆ 1.0       ┆ Compound  │
│           ┆           ┆          ┆ BA, Ip    ┆   ┆ 3         ┆ 3         ┆           ┆           │
│           ┆           ┆          ┆ Via Ching ┆   ┆ 22:39:47  ┆ 22:39:47  ┆           ┆           │
│           ┆           ┆          ┆ TR, V…    ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ 7951.0    ┆ null     ┆ null      ┆ … ┆ 2015-02-2 ┆ 2015-02-2 ┆ 10831.0   ┆ null      │
│           ┆           ┆          ┆           ┆   ┆ 3         ┆ 3         ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ 23:56:50  ┆ 23:56:50  ┆           ┆           │
│ 50%       ┆ 15897.0   ┆ null     ┆ null      ┆ … ┆ 2015-02-2 ┆ 2015-02-2 ┆ 17279.0   ┆ null      │
│           ┆           ┆          ┆           ┆   ┆ 4         ┆ 4         ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ 18:12:38  ┆ 18:12:38  ┆           ┆           │
│ 75%       ┆ 23847.0   ┆ null     ┆ null      ┆ … ┆ 2015-02-2 ┆ 2015-02-2 ┆ 22617.0   ┆ null      │
│           ┆           ┆          ┆           ┆   ┆ 4         ┆ 4         ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ 22:50:56  ┆ 22:50:56  ┆           ┆           │
│ max       ┆ 31791.0   ┆ general  ┆ von der   ┆ … ┆ 2015-02-2 ┆ 2015-02-2 ┆ 30104.0   ┆ Compound  │
│           ┆           ┆          ┆ Werth JM, ┆   ┆ 5         ┆ 5         ┆           ┆           │
│           ┆           ┆          ┆ English   ┆   ┆ 00:32:27  ┆ 00:32:27  ┆           ┆           │
│           ┆           ┆          ┆ JS, …     ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Processing ../data/raw/foodb_2020_04_07_json/Flavor.json
shape: (9, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id        ┆ name      ┆ flavor_gr ┆ … ┆ created_a ┆ updated_a ┆ creator_i ┆ updater_ │
│ ---       ┆ ---       ┆ ---       ┆ oup       ┆   ┆ t         ┆ t         ┆ d         ┆ id       │
│ str       ┆ f64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │

We can start with only a few tables first:

- Food
- Nutrient
- Content
- HealthEffect
- Flavor
- FoodTaxonomy

Clean up these tables/types, send to postgres

Can I make a graph DB that has each food item and some similarity measure against all other food items? Maybe weighed by ingredient/compound concentration?

- Ingredient similarity based on compounds (Food, similarity graph)
- Food CONTAINS ingredient (Content, knowledge graph)
- Food CATEGORY compound? (Flavor, knowledge graph)

Build out hierarchy

In [ ]:
food_df = pl.read_ndjson(json_path + "Food.json")

food_df = food_df.with_columns(
    cs.by_name(date_columns, require_all=False).cast(pl.Datetime)
)

food_df.glimpse()

Rows: 992
Columns: 23
$ id                            <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ name                          <str> 'Angelica', 'Savoy cabbage', 'Silver linden', 'Kiwi', 'Allium', 'Garden onion', 'Leek', 'Garlic', 'Chives', 'Lemon verbena'
$ name_scientific               <str> 'Angelica keiskei', 'Brassica oleracea var. sabauda', 'Tilia argentea', 'Actinidia chinensis', 'Allium', 'Allium cepa', 'Allium porrum', 'Allium sativum', 'Allium schoenoprasum', 'Aloysia triphylla'
$ description                   <str> 'Angelica is a genus of about 60 species of tall biennial and perennial herbs in the family Apiaceae, native to temperate and subarctic regions of the Northern Hemisphere, reaching as far north as Iceland and Lapland. They grow to 1–3 m tall, with large bipinnate leaves and large compound umbels of white or greenish-white flowers. Some species can be found in purple moor and rush pastures.', 'Savoy cabbage (Brassica oleracea convar. capitata var. sabauda L. ) is a variety of the cabbage, a cultivar of the plant species Brassica oleracea. Savoy cabbage is a winter vegetable. A variety of the savoy cabbage is the January King Cabbage. Savoy cabbage can be used in a variety of recipes. It pairs well with red wine, apples, spices, horseradish and meat. It can be used for roulades, in stews and soups, as well as roasted plain and drizzled with olive oil. Cabbage that is heavy for its size with leaves that are unblemished and have a bright, fresh look are signs of desirable quality. Whole cabbages are preferred whenever possible as pre-cut or preshredded cabbage has a greatly diminished vitamin content. Peak season for most cabbages runs from November through April. Fresh whole cabbage will keep in the refrigerator for one to six weeks depending on type and variety. Hard green, white or red cabbages will keep the longest while the looser Savoy and Chinese varieties need to be consumed more quickly. It is necessary to keep the outer leaves intact without washing when storing since moisture hastens decay. Cabbage provides fiber, vitamins A, C, K and B6, folate, potassium, manganese, thiamin, calcium, iron and magnesium.', 'Tilia tomentosa (Silver Lime in the UK and Silver Linden in the US) is a species of Tilia native to southeastern Europe and southwestern Asia, from Hungary and the Balkans east to western Turkey, occurring at moderate altitudes. It is a deciduous tree growing to 20–35 m tall, with a trunk up to 2 m diameter. The leaves are alternately arranged, rounded to triangular-ovate, 4–13\xa0cm long and broad with a 2.5–4\xa0cm petiole, green and mostly hairless above, densely white tomentose with white hairs below, and with a coarsely toothed margin. The flowers are pale yellow, hermaphrodite, produced in cymes of three to ten in mid to late summer with a pale green subtending leafy bract; they have a strong scent and are pollinated by honeybees. The nectar however contains sugars which cannot be digested by other bees, to whom the tree is somewhat toxic. The fruit is a dry nut-like drupe 8–10\xa0mm long, downy, and slightly ribbed.', "The kiwifruit, often shortened to kiwi in many parts of the world, is the edible berry of a woody vine in the genus Actinidia. The most common cultivar group of kiwifruit ('Hayward') is oval, about the size of a large hen's egg (5?8 centimetres in length and 4.5?5.5 centimetres in diameter). It has a fibrous, dull greenish-brown skin and bright green or golden flesh with rows of tiny, black, edible seeds. The fruit has a soft texture and a sweet but unique flavor, and today is a commercial crop in several countries, such as Italy, New Zealand, Chile, Greece and France.", 'Allium haematochiton is a species of wild onion known by the common name redskin onion. It is native to northern Baja California and southern California. It it grows on the slopes of the coastal hills and mountains, such as those of the Peninsular Ranges, Transverse Ranges, and southern California Coast Ranges.', 'The onion (Allium cepa) (Latin \'cepa\' = onion), also known as the bulb onion or common onion, is used as a vegetable and is the most widely cultivated species of the genus Allium. This genus also contains several other species variously referred to as onions and cultivated for food, such as the Japanese bunching onion (A. fistulosum), the Egyptian onion (A. ×proliferum), and the Canada onion (A. canadense). The name "wild onion" is applied to a number of Allium species but A. cepa is exclusively known from cultivation and its ancestral wild original form is not known, although escapes from cultivation have become established in some regions.The onion is most frequently a biennial or a perennial plant, but is usually treated as an annual and harvested in its first growing season.\r\nOnions are cultivated and used around the world. As a foodstuff they are usually served cooked, as a vegetable or part of a prepared savoury dish, but can also be eaten raw or used to make pickles or chutneys. They are pungent when chopped and contain certain chemical substances which irritate the eyes. Onions contain phenolics and flavonoids that have potential anti-inflammatory, anti-cholesterol, anticancer and antioxidant properties.', 'The leek is a vegetable that belongs, along with onion and garlic, to the genus Allium, currently placed in family Amaryllidaceae, subfamily Allioideae. Historically many scientific names were used for leeks, which are now treated as cultivars of Allium ampeloprasum. Two related vegetables, elephant garlic and kurrat, are also cultivars of A. \xa0ampeloprasum, although different in their uses as food. The edible part of the leek plant is a bundle of leaf sheaths that is sometimes erroneously called a stem or stalk.', 'With a history of human use of over 7,000 years, garlic (Allium sativum) is native to central Asia, and has long been a staple in the Mediterranean region, as well as a frequent seasoning in Asia, Africa, and Europe. There are two sub-varieties of allium sativum: Allium sativum var. sativum (soft-necked garlic) and Allium sativum var. ophioscorodon (hard-necked garlic). Soft-necked garlic is the most commonly found. Bulb garlic is available in many forms, including fresh, frozen, dried, fermented (black garlic) and shelf stable products (in tubes or jars). [Wikipedia]', 'Chives is the common name of Allium schoenoprasum, the smallest species of the edible onions. A perennial plant, it is native to Europe, Asia and North America. A. schoenoprasum is the only species of Allium native to both the New and the Old Worlds. The name of the species derives from the Greek skhoínos and práson. Its English name, chives, derives from the French word cive, from cepa, the Latin word for onion. Chives are a commonly used herb and can be found in grocery stores or grown in home gardens. In culinary use, the scapes are diced and used as an ingredient for fish, potatoes, soups, and other dishes. Chives have insect-repelling properties that can be used in gardens to control pests.', 'Aloysia citrodora is a species of flowering plant in the verbena family Verbenaceae, native to northwestern Argentina and southern Bolivia. Common names include lemon verbena and lemon beebrush. It was brought to Europe by the Spanish and the Portuguese in the 17th century.'
$ itis_id                       <str> '', None, '845789', '506775', '42634', '42720', '42659', '42652', '42636', '32135'
$ wikipedia_id                  <str> 'Angelica', 'Savoy cabbage', 'Tilia tomentosa', 'Kiwifruit', 'Allium haematochiton', 'Onion', 'Leek', 'Garlic', 'Chives', 'Aloysia citrodora'
$ picture_file_name             <str> '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg'
$ picture_content_type          <str> 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg', 'image/jpeg'
$ picture_file_size             <i64> 111325, 155178, 56367, 110661, 341911, 138437, 4857, 545294, 1411537, 142723
$ picture_updated_at            <str> '2012-04-20T09:29:57.000Z', '2012-04-20T09:39:54.000Z', '2012-04-20T09:41:25.000Z', '2012-04-20T09:32:21.000Z', '2012-04-20T09:37:44.000Z', '2012-04-20T09:41:21.000Z', '2012-04-20T09:33:40.000Z', '2012-04-20T09:42:05.000Z', '2012-04-20T09:42:09.000Z', '2012-04-20T09:32:16.000Z'
$ legacy_id                     <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ food_group                    <str> 'Herbs and Spices', 'Vegetables', 'Herbs and Spices', 'Fruits', 'Vegetables', 'Vegetables', 'Vegetables', 'Herbs and Spices', 'Herbs and Spices', 'Herbs and Spices'
$ food_subgroup                 <str> 'Herbs', 'Cabbages', 'Herbs', 'Tropical fruits', 'Onion-family vegetables', 'Onion-family vegetables', 'Onion-family vegetables', 'Herbs', 'Herbs', 'Herbs'
$ food_type                     <str> 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1', 'Type 1'
$ created_at           <datetime[μs]> 2011-02-09 00:37:14, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15, 2011-02-09 00:37:15
$ updated_at           <datetime[μs]> 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-17 16:19:45, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13, 2019-05-14 18:04:13
$ creator_id                   <null> None, None, None, None, None, None, None, None, None, None
$ updater_id                    <i64> 2, None, None, None, None, None, None, 2, None, None
$ export_to_afcdb              <bool> False, False, False, False, False, True, False, True, False, False
$ category                      <str> 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific', 'specific'
$ ncbi_taxonomy_id              <i64> 357850, 1216010, None, 3625, 4678, 4679, None, 4682, 74900, 542672
$ export_to_foodb              <bool> True, True, True, True, True, True, True, True, True, True
$ public_id                     <str> 'FOOD00001', 'FOOD00002', 'FOOD00003', 'FOOD00004', 'FOOD00005', 'FOOD00006', 'FOOD00007', 'FOOD00008', 'FOOD00009', 'FOOD00010'

In [ ]:
content_df = pl.read_ndjson(json_path + "Content.json")

content_df = content_df.with_columns(
    cs.by_name(date_columns, require_all=False).cast(pl.Datetime)
)

content_df.head()

shape: (5, 26)
┌─────┬───────────┬─────────────┬─────────┬───┬──────────────┬──────────────┬─────────────┬────────┐
│ id  ┆ source_id ┆ source_type ┆ food_id ┆ … ┆ orig_unit_ex ┆ standard_con ┆ preparation ┆ export │
│ --- ┆ ---       ┆ ---         ┆ ---     ┆   ┆ pression     ┆ tent         ┆ _type       ┆ ---    │
│ i64 ┆ i64       ┆ str         ┆ i64     ┆   ┆ ---          ┆ ---          ┆ ---         ┆ i64    │
│     ┆           ┆             ┆         ┆   ┆ null         ┆ str          ┆ str         ┆        │
╞═════╪═══════════╪═════════════╪═════════╪═══╪══════════════╪══════════════╪═════════════╪════════╡
│ 1   ┆ 1         ┆ Nutrient    ┆ 4       ┆ … ┆ null         ┆ 1955.0       ┆ raw         ┆ 0      │
│ 2   ┆ 1         ┆ Nutrient    ┆ 6       ┆ … ┆ null         ┆ 1853.95      ┆ raw         ┆ 0      │
│ 3   ┆ 1         ┆ Nutrient    ┆ 6       ┆ … ┆ null         ┆ 4150.0       ┆ raw         ┆ 0      │
│ 4   ┆ 1         ┆ Nutrient    ┆ 9       ┆ … ┆ null         ┆ 3900.0       ┆ raw         ┆ 0      │
│ 5   ┆ 1         ┆ Nutrient    ┆ 11      ┆ … ┆ null         ┆ 2500.0       ┆ other       ┆ 0      │
└─────┴───────────┴─────────────┴─────────┴───┴──────────────┴──────────────┴─────────────┴────────┘

In [ ]:
content_df.filter(pl.col("orig_food_common_name") == "Kiwi")

shape: (67, 26)
┌────────┬───────────┬─────────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────┐
│ id     ┆ source_id ┆ source_type ┆ food_id ┆ … ┆ orig_unit_e ┆ standard_co ┆ preparatio ┆ export │
│ ---    ┆ ---       ┆ ---         ┆ ---     ┆   ┆ xpression   ┆ ntent       ┆ n_type     ┆ ---    │
│ i64    ┆ i64       ┆ str         ┆ i64     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ i64    │
│        ┆           ┆             ┆         ┆   ┆ null        ┆ str         ┆ str        ┆        │
╞════════╪═══════════╪═════════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════╡
│ 1      ┆ 1         ┆ Nutrient    ┆ 4       ┆ … ┆ null        ┆ 1955.0      ┆ raw        ┆ 0      │
│ 402    ┆ 2         ┆ Nutrient    ┆ 4       ┆ … ┆ null        ┆ 3536.5      ┆ raw        ┆ 0      │
│ 10771  ┆ 3         ┆ Nutrient    ┆ 4       ┆ … ┆ null        ┆ 51335.0     ┆ raw        ┆ 0      │
│ 682040 ┆ 2576      ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ 0.285384618 ┆ raw        ┆ 1      │
│ 682144 ┆ 17121     ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ 0.0         ┆ raw        ┆ 1      │
│ …      ┆ …         ┆ …           ┆ …       ┆ … ┆ …           ┆ …           ┆ …          ┆ …      │
│ 687922 ┆ 15475     ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ 0.54        ┆ raw        ┆ 1      │
│ 687923 ┆ 15890     ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ null        ┆ raw        ┆ 1      │
│ 687924 ┆ 16258     ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ 1.65        ┆ raw        ┆ 1      │
│ 687925 ┆ 19872     ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ null        ┆ raw        ┆ 1      │
│ 687926 ┆ 21462     ┆ Compound    ┆ 4       ┆ … ┆ null        ┆ 1450.0      ┆ raw        ┆ 1      │
└────────┴───────────┴─────────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────┘

In [ ]:
content_df.filter(pl.col("orig_food_common_name") == "Kiwi").glimpse()

Rows: 67
Columns: 26
$ id                                 <i64> 1, 402, 10771, 682040, 682144, 682237, 682330, 682445, 682545, 682582
$ source_id                          <i64> 1, 2, 3, 2576, 17121, 17707, 17709, 2571, 2572, 17712
$ source_type                        <str> 'Nutrient', 'Nutrient', 'Nutrient', 'Compound', 'Compound', 'Compound', 'Compound', 'Compound', 'Compound', 'Compound'
$ food_id                            <i64> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4
$ orig_food_id                       <str> '29', '29', '29', '156', '156', '156', '156', '156', '156', '156'
$ orig_food_common_name              <str> 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi', 'Kiwi'
$ orig_food_scientific_name          <str> 'Actinidia chinensis PLANCHON [Actinidiaceae]', 'Actinidia chinensis PLANCHON [Actinidiaceae]', 'Actinidia chinensis PLANCHON [Actinidiaceae]', None, None, None, None, None, None, None
$ orig_food_part                     <str> 'Fruit', 'Fruit', 'Fruit', None, None, None, None, None, None, None
$ orig_source_id                     <str> 'FAT', 'PROTEIN', 'CARBOHYDRATES', '125', '128', '127', '129', '124', '139', '126'
$ orig_source_name                   <str> 'FAT', 'PROTEIN', 'CARBOHYDRATES', '(-)-Epicatechin', '(-)-Epicatechin 3-O-gallate', '(-)-Epigallocatechin', '(-)-Epigallocatechin 3-O-gallate', '(+)-Catechin', '(+)-Catechin 3-O-gallate', '(+)-Gallocatechin'
$ orig_content                       <str> '1955.0', '3536.5', '51335.0', '0.285384618', '0.0', '0.0', '0.076923077', '0.0', '0.083333333', '0.0'
$ orig_min                           <str> '70.0', '790.0', '14880.0', None, None, None, None, None, None, None
$ orig_max                           <str> '3840.0', '6283.0', '87790.0', None, None, None, None, None, None, None
$ orig_unit                          <str> 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g', 'mg/100 g'
$ orig_citation                     <null> None, None, None, None, None, None, None, None, None, None
$ citation                           <str> 'DUKE', 'DUKE', 'DUKE', 'PHENOL EXPLORER', 'PHENOL EXPLORER', 'PHENOL EXPLORER', 'PHENOL EXPLORER', 'PHENOL EXPLORER', 'PHENOL EXPLORER', 'PHENOL EXPLORER'
$ citation_type                      <str> 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE', 'DATABASE'
$ creator_id                        <null> None, None, None, None, None, None, None, None, None, None
$ updater_id                        <null> None, None, None, None, None, None, None, None, None, None
$ created_at                <datetime[μs]> 2014-11-05 13:42:11, 2014-11-05 13:42:17, 2014-11-05 13:44:08, 2014-11-05 16:54:27, 2014-11-05 16:54:28, 2014-11-05 16:54:29, 2014-11-05 16:54:30, 2014-11-05 16:54:32, 2014-11-05 16:54:34, 2014-11-05 16:54:34
$ updated_at                <datetime[μs]> 2020-04-27 16:20:52, 2020-04-27 16:20:52, 2020-04-27 16:21:06, 2020-04-27 16:37:06, 2020-04-27 16:37:06, 2020-04-27 16:37:06, 2020-04-27 16:37:06, 2020-04-27 16:37:06, 2020-04-27 16:37:06, 2020-04-27 16:37:07
$ orig_method                       <null> None, None, None, None, None, None, None, None, None, None
$ orig_unit_expression              <null> None, None, None, None, None, None, None, None, None, None
$ standard_content                   <str> '1955.0', '3536.5', '51335.0', '0.285384618', '0.0', '0.0', '0.076923077', '0.0', '0.083333333', '0.0'
$ preparation_type                   <str> 'raw', 'raw', 'raw', 'raw', 'raw', 'raw', 'raw', 'raw', 'raw', 'raw'
$ export                             <i64> 0, 0, 0, 1, 1, 1, 1, 1, 1, 1

In [ ]:
content_df.select(pl.col("orig_unit").value_counts(sort=True))

shape: (14, 1)
┌──────────────────────┐
│ orig_unit            │
│ ---                  │
│ struct[2]            │
╞══════════════════════╡
│ {null,4844705}       │
│ {"mg/100 g",792002}  │
│ {"uM",16441}         │
│ {"kcal/100 g",15658} │
│ {"IU",11729}         │
│ …                    │
│ {"IU/100 g",80}      │
│ {"umol/g ",28}       │
│ {"umol/g",16}        │
│ {"g/kg",8}           │
│ {"mg/g",2}           │
└──────────────────────┘

In [ ]:
content_df

shape: (5_691_011, 26)
┌─────────┬───────────┬─────────────┬─────────┬───┬─────────────┬────────────┬────────────┬────────┐
│ id      ┆ source_id ┆ source_type ┆ food_id ┆ … ┆ orig_unit_e ┆ standard_c ┆ preparatio ┆ export │
│ ---     ┆ ---       ┆ ---         ┆ ---     ┆   ┆ xpression   ┆ ontent     ┆ n_type     ┆ ---    │
│ i64     ┆ i64       ┆ str         ┆ i64     ┆   ┆ ---         ┆ ---        ┆ ---        ┆ i64    │
│         ┆           ┆             ┆         ┆   ┆ null        ┆ str        ┆ str        ┆        │
╞═════════╪═══════════╪═════════════╪═════════╪═══╪═════════════╪════════════╪════════════╪════════╡
│ 1       ┆ 1         ┆ Nutrient    ┆ 4       ┆ … ┆ null        ┆ 1955.0     ┆ raw        ┆ 0      │
│ 2       ┆ 1         ┆ Nutrient    ┆ 6       ┆ … ┆ null        ┆ 1853.95    ┆ raw        ┆ 0      │
│ 3       ┆ 1         ┆ Nutrient    ┆ 6       ┆ … ┆ null        ┆ 4150.0     ┆ raw        ┆ 0      │
│ 4       ┆ 1         ┆ Nutrient    ┆ 9       ┆ … ┆ null        ┆ 3900.0     ┆ raw        ┆ 0      │
│ 5       ┆ 1         ┆ Nutrient    ┆ 11      ┆ … ┆ null        ┆ 2500.0     ┆ other      ┆ 0      │
│ …       ┆ …         ┆ …           ┆ …       ┆ … ┆ …           ┆ …          ┆ …          ┆ …      │
│ 6180503 ┆ 30807     ┆ Compound    ┆ 268     ┆ … ┆ null        ┆ 1.08       ┆ beverage,  ┆ 1      │
│         ┆           ┆             ┆         ┆   ┆             ┆            ┆ alcoholic  ┆        │
│ 6180504 ┆ 31057     ┆ Compound    ┆ 268     ┆ … ┆ null        ┆ 0.27       ┆ beverage,  ┆ 1      │
│         ┆           ┆             ┆         ┆   ┆             ┆            ┆ alcoholic  ┆        │
│ 6180505 ┆ 31057     ┆ Compound    ┆ 268     ┆ … ┆ null        ┆ 0.54       ┆ beverage,  ┆ 1      │
│         ┆           ┆             ┆         ┆   ┆             ┆            ┆ alcoholic  ┆        │
│ 6180506 ┆ 31026     ┆ Compound    ┆ 268     ┆ … ┆ null        ┆ 0.05       ┆ beverage,  ┆ 1      │
│         ┆           ┆             ┆         ┆   ┆             ┆            ┆ alcoholic  ┆        │
│ 6180507 ┆ 31026     ┆ Compound    ┆ 268     ┆ … ┆ null        ┆ 0.03       ┆ beverage,  ┆ 1      │
│         ┆           ┆             ┆         ┆   ┆             ┆            ┆ alcoholic  ┆        │
└─────────┴───────────┴─────────────┴─────────┴───┴─────────────┴────────────┴────────────┴────────┘

In [ ]:
content_df.filter(
    pl.col("orig_source_id").is_not_null() & pl.col("orig_source_name").is_not_null()
).group_by("orig_food_common_name", maintain_order=True).agg(
    components=pl.struct(
        component_id="orig_source_id",
        component="orig_source_name",
        amount="orig_content",
        unit="orig_unit",
    )
)

shape: (8_701, 2)
┌───────────────────────┬─────────────────────────────────┐
│ orig_food_common_name ┆ components                      │
│ ---                   ┆ ---                             │
│ str                   ┆ list[struct[4]]                 │
╞═══════════════════════╪═════════════════════════════════╡
│ Kiwi                  ┆ [{"FAT","FAT","1955.0","mg/100… │
│ Onion                 ┆ [{"FAT","FAT","1853.95","mg/10… │
│ Chives                ┆ [{"FAT","FAT","3900.0","mg/100… │
│ Cashew                ┆ [{"FAT","FAT","2500.0","mg/100… │
│ Pineapple             ┆ [{"FAT","FAT","2188.6","mg/100… │
│ …                     ┆ …                               │
│ Rose Hips             ┆ [{"SUCROSE","SUCROSE",null,nul… │
│ Salmonberry           ┆ [{"VANILLIC-ACID","VANILLIC-AC… │
│ Japanese Horseradish  ┆ [{"GLUCOPUTRANJIVIN","GLUCOPUT… │
│ Shiitake              ┆ [{"TYROSINE","TYROSINE",null,n… │
│ Cornmint              ┆ [{"RAFFINOSE","RAFFINOSE",null… │
└───────────────────────┴─────────────────────────────────┘

It's cool to get the struct out with the id name, common name, amount/concentration, and units, but these seem incomplete.

Go back to only using the lists of common names

In [ ]:
content_df.filter(
    pl.col("orig_source_id").is_not_null() & pl.col("orig_source_name").is_not_null()
).select(pl.col("orig_unit").value_counts(sort=True))

shape: (7, 1)
┌──────────────────────┐
│ orig_unit            │
│ ---                  │
│ struct[2]            │
╞══════════════════════╡
│ {"mg/100 g",630090}  │
│ {null,30091}         │
│ {"kcal/100 g",15658} │
│ {"IU",11725}         │
│ {"RE",7307}          │
│ {"α-TE",1055}        │
│ {"NE",1055}          │
└──────────────────────┘

In [ ]:
content_df.filter(
    pl.col("orig_source_id").is_not_null() & pl.col("orig_source_name").is_not_null()
).group_by("orig_food_common_name", maintain_order=True).agg(
    pl.col("orig_source_name")
).with_columns(
    pl.col("orig_source_name").list.join("||")
).with_columns(
    pl.col("orig_source_name").str.split("||").alias("components")
)

shape: (8_701, 3)
┌───────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ orig_food_common_name ┆ orig_source_name                ┆ components                      │
│ ---                   ┆ ---                             ┆ ---                             │
│ str                   ┆ str                             ┆ list[str]                       │
╞═══════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ Kiwi                  ┆ FAT||PROTEIN||CARBOHYDRATES||(… ┆ ["FAT", "PROTEIN", … "PECTIN"]  │
│ Onion                 ┆ FAT||FAT||PROTEIN||PROTEIN||CA… ┆ ["FAT", "FAT", … "9,10,13-TRIH… │
│ Chives                ┆ FAT||PROTEIN||CARBOHYDRATES||T… ┆ ["FAT", "PROTEIN", … "ISORHAMN… │
│ Cashew                ┆ FAT||FAT||FAT||PROTEIN||PROTEI… ┆ ["FAT", "FAT", … "GLUCURONIC-A… │
│ Pineapple             ┆ FAT||PROTEIN||CARBOHYDRATES||(… ┆ ["FAT", "PROTEIN", … "PECTIN"]  │
│ …                     ┆ …                               ┆ …                               │
│ Rose Hips             ┆ SUCROSE||ASCORBIC-ACID||TILIRO… ┆ ["SUCROSE", "ASCORBIC-ACID", …… │
│ Salmonberry           ┆ VANILLIC-ACID||PROTOCATECHUIC-… ┆ ["VANILLIC-ACID", "PROTOCATECH… │
│ Japanese Horseradish  ┆ GLUCOPUTRANJIVIN||SINIGRIN||AL… ┆ ["GLUCOPUTRANJIVIN", "SINIGRIN… │
│ Shiitake              ┆ TYROSINE||SACCHAROPINE||VALINE… ┆ ["TYROSINE", "SACCHAROPINE", …… │
│ Cornmint              ┆ RAFFINOSE||ANISALDEHYDE||TANNI… ┆ ["RAFFINOSE", "ANISALDEHYDE", … │
└───────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [ ]:
import

In [ ]:
epic_df = pl.read_parquet("../data/processed/cleaned_df.parquet.gzip")

epic_df.head(3)

In [ ]:
# connect to MySQL

mariadb_key_path = "../../../../secrets/pw.json"

with open(mariadb_key_path, "r") as fo:
    mariadb_key = json.loads(fo.read())
user = mariadb_key["user"]
password = mariadb_key["password"]
host = "192.168.1.24"

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}/scraped_recipes?charset=utf8"
)

In [ ]:
with engine.begin() as connection:
    df = pd.read_sql_table(
        table_name="all_recipes_world_cuisines",
        con=connection,
        columns=[
            "id",
            "recipe_title",
            "recipe_url",
            "recipe_photo",
            "description",
            "ingredients",
            "steps",
            "cuisine",
        ],
    )

df