---
{}

---

In [ ]:
# import libraries
import json

# import os
import polars as pl

# import polars.selectors as cs
import requests

# from sqlalchemy import create_engine

In [ ]:
# what dish are we looking for?
dish_name = "lasagna"
cuisine_type = "italian"

In [ ]:
# load credentials

f = open("../secrets/edamam.json", "r")
cred = json.load(f)
f.close()

cred_appid = cred["id"]
cred_appkey = cred["key"]

In [ ]:
# make request to Edamam API
query_base = "https://api.edamam.com/api/recipes/v2?type=public&"

api_call = f"{query_base}q={dish_name}&app_id={cred_appid}&app_key={cred_appkey}"

resp = requests.get(api_call)

In [ ]:
resp

In [ ]:
resp.json()

{'from': 1,
 'to': 20,
 'count': 6324,
 '_links': {'next': {'href': 'https://api.edamam.com/api/recipes/v2?q=lasagna&app_key=251fdd6b808c90fa3b5863d9943692e5&_cont=CHcVQBtNNQphDmgVQntAEX4BYUtxDQEBQ2ZGAGcbZlZxBQQVX3dFVWQSa1IiVwYBEGNEAzQXa1MgBQAHRjRHBjFAMVAhBhFqX3cWQT1OcV9xBE4%3D&type=public&app_id=abaa034e',
   'title': 'Next page'}},
 'hits': [{'recipe': {'uri': 'http://www.edamam.com/ontologies/edamam.owl#recipe_1719e115491b4f6aa346b680b91f26db',
    'label': 'Pizza Lasagna',
    'image': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7fdcb728561acde968b9d3908fb7c71850adfc0facd4798d6498b764510ff61d',
    'images': {'THUMBNAIL': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a-s.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e08f23d848f5e5921fc7991a85a3114cc84a8582be73eea788ed05e37cdc1629',
      'width': 100,
      'height': 100},
     'SMALL': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=a2be9297b777cb8ab8e97877122b4347315dfb1bcbcfc8c5cf3b775a9fd7395d',
      'width': 200,
      'height': 200},
     'REGULAR': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7fdcb728561acde968b9d3908fb7c71850adfc0facd4798d6498b764510ff61d',
      'width': 300,
      'height': 300},
     'LARGE': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a-l.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6c232846eb81d79e1a2fec516272a42cc900483e6765378da58e79555193e786',
      'width': 600,
      'height': 600}},
    'source': 'Simply Recipes',
    'url': 'https://www.simplyrecipes.com/pizza-lasagna-recipe-7503569',
    'shareAs': 'http://www.edamam.com/recipe/pizza-lasagna-1719e115491b4f6aa346b680b91f26db/lasagna',
    'yield': 6.0,
    'dietLabels': ['Balanced', 'High-Fiber'],
    'healthLabels': ['Egg-Free',
     'Peanut-Free',
     'Tree-Nut-Free',
     'Soy-Free',
     'Fish-Free',
     'Shellfish-Free',
     'Crustacean-Free',
     'Celery-Free',
     'Mustard-Free',
     'Sesame-Free',
     'Lupine-Free',
     'Mollusk-Free',
     'Alcohol-Free',
     'Sulfite-Free'],
    'cautions': ['Sulfites'],
    'ingredientLines': ['9 ounces oven-ready lasagna noodles (about 15 sheets)',
     '1 ( 48 - ounce ) jar marinara sauce (about 6 cups), or homemade',
     '1 1/2 pounds low-moisture mozzarella , shredded (about 5 cups)',
     '5 ounces sliced pepperoni , preferably small diameter (see recipe note)'],
    'ingredients': [{'text': '9 ounces oven-ready lasagna noodles (about 15 sheets)',
      'quantity': 15.0,
      'measure': 'sheet',
      'food': 'lasagna noodles',
      'weight': 375.0,
      'foodCategory': 'grains',
      'foodId': 'food_a8hs60uayl5icia1qe8qoba1kwp8',
      'image': 'https://www.edamam.com/food-img/296/296ff2b02ef3822928c3c923e22c7d19.jpg'},
     {'text': '1 ( 48 - ounce ) jar marinara sauce (about 6 cups), or homemade',
      'quantity': 6.0,
      'measure': 'cup',
      'food': 'marinara sauce',
      'weight': 1584.0,
      'foodCategory': 'canned soup',
      'foodId': 'food_a7hv5mybkkrs3ub78yhtxafs67bu',
      'image': 'https://www.edamam.com/food-img/08b/08b3bb49c006689a458a8b9c4a4e0057.jpg'},
     {'text': '1 1/2 pounds low-moisture mozzarella , shredded (about 5 cups)',
      'quantity': 5.0,
      'measure': 'cup',
      'food': 'mozzarella',
      'weight': 560.0,
      'foodCategory': 'Cheese',
      'foodId': 'food_am27cpgbcz7639bm3uvx0ai1xhrs',
      'image': 'https://www.edamam.com/food-img/03e/03ec3a4d46bec5634dc8a352804e4e68.jpg'},
     {'text': '5 ounces sliced pepperoni , preferably small diameter (see recipe note)',
      'quantity': 5.0,
      'measure': 'ounce',
      'food': 'pepperoni',
      'weight': 141.747615625,
      'foodCategory': 'Cured meats',
      'foodId': 'food_al5qjzna5bpefha4cy7odah0wwt2',
      'image': 'https://www.edamam.com/food-img/10b/10b28aa71cbe520aef944186f2b365b9.jpg'}],
    'calories': 4572.0579827500005,
    'totalCO2Emissions': 19017.02314834375,
    'co2EmissionsClass': 'G',
    'totalWeight': 2660.747615625,
    'totalTime': 40.0,
    'cuisineType': ['italian'],
    'mealType': ['lunch/dinner'],
    'dishType': ['main course'],
    'totalNutrients': {'ENERC_KCAL': {'label': 'Energy',
      'quantity': 4572.0579827500005,
      'unit': 'kcal'},
     'FAT': {'label': 'Fat', 'quantity': 220.55404603437503, 'unit': 'g'},
     'FASAT': {'label': 'Saturated',
      'quantity': 107.42119796562503,
      'unit': 'g'},
     'FATRN': {'label': 'Trans', 'quantity': 2.2796185190625, 'unit': 'g'},
     'FAMS': {'label': 'Monounsaturated',
      'quantity': 71.63707405,
      'unit': 'g'},
     'FAPU': {'label': 'Polyunsaturated',
      'quantity': 23.381263656875,
      'unit': 'g'},
     'CHOCDF': {'label': 'Carbs', 'quantity': 412.928821864375, 'unit': 'g'},
     'CHOCDF.net': {'label': 'Carbohydrates (net)',
      'quantity': 372.416821864375,
      'unit': 'g'},
     'FIBTG': {'label': 'Fiber', 'quantity': 40.512, 'unit': 'g'},
     'SUGAR': {'label': 'Sugars', 'quantity': 87.7869, 'unit': 'g'},
     'PROCNT': {'label': 'Protein', 'quantity': 222.3031422, 'unit': 'g'},
     'CHOLE': {'label': 'Cholesterol',
      'quantity': 611.5751871562501,
      'unit': 'mg'},
     'NA': {'label': 'Sodium', 'quantity': 11905.792326875, 'unit': 'mg'},
     'CA': {'label': 'Calcium', 'quantity': 3345.522046968751, 'unit': 'mg'},
     'MG': {'label': 'Magnesium', 'quantity': 621.3845708125, 'unit': 'mg'},
     'K': {'label': 'Potassium', 'quantity': 6719.038466812501, 'unit': 'mg'},
     'FE': {'label': 'Iron', 'quantity': 20.7874432878125, 'unit': 'mg'},
     'ZN': {'label': 'Zinc', 'quantity': 28.266141821250002, 'unit': 'mg'},
     'P': {'label': 'Phosphorus', 'quantity': 3453.6712326875, 'unit': 'mg'},
     'VITA_RAE': {'label': 'Vitamin A', 'quantity': 1493.44, 'unit': 'µg'},
     'VITC': {'label': 'Vitamin C', 'quantity': 31.68, 'unit': 'mg'},
     'THIA': {'label': 'Thiamin (B1)',
      'quantity': 1.26979603834375,
      'unit': 'mg'},
     'RIBF': {'label': 'Riboflavin (B2)',
      'quantity': 3.14033137215625,
      'unit': 'mg'},
     'NIA': {'label': 'Niacin (B3)',
      'quantity': 76.12340601968751,
      'unit': 'mg'},
     'VITB6A': {'label': 'Vitamin B6',
      'quantity': 3.993146368562499,
      'unit': 'mg'},
     'FOLDFE': {'label': 'Folate equivalent (total)',
      'quantity': 319.7073807812499,
      'unit': 'µg'},
     'FOLFD': {'label': 'Folate (food)',
      'quantity': 319.7073807812499,
      'unit': 'µg'},
     'FOLAC': {'label': 'Folic acid', 'quantity': 0.0, 'unit': 'µg'},
     'VITB12': {'label': 'Vitamin B12',
      'quantity': 14.610719003125002,
      'unit': 'µg'},
     'VITD': {'label': 'Vitamin D', 'quantity': 4.082719003125, 'unit': 'µg'},
     'TOCPHA': {'label': 'Vitamin E',
      'quantity': 40.9525004409375,
      'unit': 'mg'},
     'VITK1': {'label': 'Vitamin K',
      'quantity': 241.65236170625002,
      'unit': 'µg'},
     'WATER': {'label': 'Water', 'quantity': 1750.00081806875, 'unit': 'g'}},
    'totalDaily': {'ENERC_KCAL': {'label': 'Energy',
      'quantity': 228.60289913750003,
      'unit': '%'},
     'FAT': {'label': 'Fat', 'quantity': 339.31391697596155, 'unit': '%'},
     'FASAT': {'label': 'Saturated',
      'quantity': 537.1059898281252,
      'unit': '%'},
     'CHOCDF': {'label': 'Carbs', 'quantity': 137.64294062145834, 'unit': '%'},
     'FIBTG': {'label': 'Fiber', 'quantity': 162.048, 'unit': '%'},
     'PROCNT': {'label': 'Protein', 'quantity': 444.6062844, 'unit': '%'},
     'CHOLE': {'label': 'Cholesterol',
      'quantity': 203.85839571875005,
      'unit': '%'},
     'NA': {'label': 'Sodium', 'quantity': 496.0746802864584, 'unit': '%'},
     'CA': {'label': 'Calcium', 'quantity': 334.55220469687515, 'unit': '%'},
     'MG': {'label': 'Magnesium', 'quantity': 147.94870733630952, 'unit': '%'},
     'K': {'label': 'Potassium', 'quantity': 142.9582652513298, 'unit': '%'},
     'FE': {'label': 'Iron', 'quantity': 115.48579604340279, 'unit': '%'},
     'ZN': {'label': 'Zinc', 'quantity': 256.9649256477273, 'unit': '%'},
     'P': {'label': 'Phosphorus', 'quantity': 493.3816046696428, 'unit': '%'},
     'VITA_RAE': {'label': 'Vitamin A',
      'quantity': 165.93777777777777,
      'unit': '%'},
     'VITC': {'label': 'Vitamin C', 'quantity': 35.2, 'unit': '%'},
     'THIA': {'label': 'Thiamin (B1)',
      'quantity': 105.81633652864585,
      'unit': '%'},
     'RIBF': {'label': 'Riboflavin (B2)',
      'quantity': 241.5639517043269,
      'unit': '%'},
     'NIA': {'label': 'Niacin (B3)',
      'quantity': 475.77128762304693,
      'unit': '%'},
     'VITB6A': {'label': 'Vitamin B6',
      'quantity': 307.16510527403835,
      'unit': '%'},
     'FOLDFE': {'label': 'Folate equivalent (total)',
      'quantity': 79.92684519531248,
      'unit': '%'},
     'VITB12': {'label': 'Vitamin B12',
      'quantity': 608.7799584635418,
      'unit': '%'},
     'VITD': {'label': 'Vitamin D',
      'quantity': 27.218126687499996,
      'unit': '%'},
     'TOCPHA': {'label': 'Vitamin E',
      'quantity': 273.01666960625,
      'unit': '%'},
     'VITK1': {'label': 'Vitamin K',
      'quantity': 201.37696808854167,
      'unit': '%'}},
    'digest': [{'label': 'Fat',
      'tag': 'FAT',
      'schemaOrgTag': 'fatContent',
      'total': 220.55404603437503,
      'hasRDI': True,
      'daily': 339.31391697596155,
      'unit': 'g',
      'sub': [{'label': 'Saturated',
        'tag': 'FASAT',
        'schemaOrgTag': 'saturatedFatContent',
        'total': 107.42119796562503,
        'hasRDI': True,
        'daily': 537.1059898281252,
        'unit': 'g'},
       {'label': 'Trans',
        'tag': 'FATRN',
        'schemaOrgTag': 'transFatContent',
        'total': 2.2796185190625,
        'hasRDI': False,
        'daily': 0.0,
        'unit': 'g'},
       {'label': 'Monounsaturated',
        'tag': 'FAMS',
        'schemaOrgTag': None,
        'total': 71.63707405,
        'hasRDI': False,
        'daily': 0.0,
        'unit': 'g'},
       {'label': 'Polyunsaturated',
        'tag': 'FAPU',
        'schemaOrgTag': None,
        'total': 23.381263656875,
        'hasRDI': False,
        'daily': 0.0,
        'unit': 'g'}]},
     {'label': 'Carbs',
      'tag': 'CHOCDF',
      'schemaOrgTag': 'carbohydrateContent',
      'total': 412.928821864375,
      'hasRDI': True,
      'daily': 137.64294062145834,
      'unit': 'g',
      'sub': [{'label': 'Carbs (net)',
        'tag': 'CHOCDF.net',
        'schemaOrgTag': None,
        'total': 372.416821864375,
        'hasRDI': False,
        'daily': 0.0,
        'unit': 'g'},
       {'label': 'Fiber',
        'tag': 'FIBTG',
        'schemaOrgTag': 'fiberContent',
        'total': 40.512,
        'hasRDI': True,
        'daily': 162.048,
        'unit': 'g'},
       {'label': 'Sugars',
        'tag': 'SUGAR',
        'schemaOrgTag': 'sugarContent',
        'total': 87.7869,
        'hasRDI': False,
        'daily': 0.0,
        'unit': 'g'},
       {'label': 'Sugars, added',
        'tag': 'SUGAR.added',
        'schemaOrgTag': None,
        'total': 0.0,
        'hasRDI': False,
        'daily': 0.0,
        'unit': 'g'}]},
     {'label': 'Protein',
      'tag': 'PROCNT',
      'schemaOrgTag': 'proteinContent',
      'total': 222.3031422,
      'hasRDI': True,
      'daily': 444.6062844,
      'unit': 'g'},
     {'label': 'Cholesterol',
      'tag': 'CHOLE',
      'schemaOrgTag': 'cholesterolContent',
      'total': 611.5751871562501,
      'hasRDI': True,
      'daily': 203.85839571875005,
      'unit': 'mg'},
     {'label': 'Sodium',
      'tag': 'NA',

In [ ]:
resp_dict_hits = resp.json()["hits"]
resp_dict_hits

[{'recipe': {'uri': 'http://www.edamam.com/ontologies/edamam.owl#recipe_1719e115491b4f6aa346b680b91f26db',
   'label': 'Pizza Lasagna',
   'image': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7fdcb728561acde968b9d3908fb7c71850adfc0facd4798d6498b764510ff61d',
   'images': {'THUMBNAIL': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a-s.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e08f23d848f5e5921fc7991a85a3114cc84a8582be73eea788ed05e37cdc1629',
     'width': 100,
     'height': 100},
    'SMALL': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=a2be9297b777cb8ab8e97877122b4347315dfb1bcbcfc8c5cf3b775a9fd7395d',
     'width': 200,
     'height': 200},
    'REGULAR': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7fdcb728561acde968b9d3908fb7c71850adfc0facd4798d6498b764510ff61d',
     'width': 300,
     'height': 300},
    'LARGE': {'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/146/1465a71f79666d12bc0f72fd16e7824a-l.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCzEBnMmR5NX%2BPjFYdTxY8Rl5wemwB3zM8WweSAw0i6XQIgPUISYtLyYRxf7Z%2F5JtUDpx%2BlO38GazVW%2BUBvE2Kx%2B18qwgUInf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDy2yGnM8keP4q3YdSqWBdgX4O9OBVljT1VzwNO%2BFEIDa5fBeSMFtFH5q%2FMOO7MFDbfRdt5MMowws6Z87hc35B5IIXmJho5Pyetakys6vi%2BX2WuyWKBc%2F6uwq5uSonL4Odrd08NAji2fpM8z7k6FnulGDrRwpzc4oEWr1TFcaC8bIU6I20veO7qga7WYXRfl6gd7ZG%2FAGLqRWl8OAWqb2DQxTlywu7uLEx1Zo9U8niqiTMIqA3SCIQGLVm4W1%2BwLDYg80tHjexUcy5wb6jf4RZNrjVOS3ByVhIWY98Syaot27Sw9%2BQ70xgq9WppEkRcv%2BN62PEy7Qtmoh6PzxGEsKk%2FzD9MJY3kfkjQf19RvZrD44L1j40dgUr2h%2Bxs2q3m9SYyVxwxN%2FST5QtGmGeacU6GsYNO55IJv58msL3iTVD1qbGyUFqmF4KAysormQj%2B2SMk8i6fNyhfzPTy%2FfW90VwKusvuhioxdX2UG9JP0uqtuKY9lzi0AEN3UfdR7uKWCGOsVNJPcXs3Bf%2BTjulMPUO5W7TIJE4TBMKprYliKoYF%2BzaLiS8XYBgZY8UODrvTfZ5tDLJxl7rjKzA8KzIDRIfjvCOGj3h9DQxfX3nH3mLjDCjaxNixSZohbYZiZzjflZdfisMlh2HfsxqT163GwrcqJqc3ldw8o80XJH9XGyDDHHyPxNVQoVufY4ZhkJORLTupmuBWnG%2F3UTbFXS2MoaQC8V94T5gHeDdhSEKIuZ0Oz7DYEe30j%2BQok1qpChchiVyoR7OfcODjxkrYEeJ6iiQHx1Q4w20B4RRuBf7TMCg2bTyD270VI%2FL2XOXCMHtyrb9m1yDLOCa1bwsit2pApgmPrtKfwTgZuNSU14%2F0CBMqh8%2B148X2UKQuYAkoXfNhcBFUKM2uJMLuEsMEGOrEB31Qb317sKXaFVNSs5iZ4JLIZy67wx%2BEFhUzKehq8QMg7W5yhOAvg4OioV%2BNbzsWTAmoOx%2F%2BRMGK7qogWFSRcDMHL0iKzWht3N1dl95YZgBCmyF4YieMQ6eNr0rhfPUMeNqiMQjeT3zPqrTgxF1DWfjLAw0stNtM7yceD5Tu%2B9%2Fbv3hC0ZoGeFa2GvETZKNd9kHI%2F9Y7E0WFnG7BP29a5Q6ikXgxdPBygca5mTFGrF7oZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250520T043846Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFDOE7CXLD%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6c232846eb81d79e1a2fec516272a42cc900483e6765378da58e79555193e786',
     'width': 600,
     'height': 600}},
   'source': 'Simply Recipes',
   'url': 'https://www.simplyrecipes.com/pizza-lasagna-recipe-7503569',
   'shareAs': 'http://www.edamam.com/recipe/pizza-lasagna-1719e115491b4f6aa346b680b91f26db/lasagna',
   'yield': 6.0,
   'dietLabels': ['Balanced', 'High-Fiber'],
   'healthLabels': ['Egg-Free',
    'Peanut-Free',
    'Tree-Nut-Free',
    'Soy-Free',
    'Fish-Free',
    'Shellfish-Free',
    'Crustacean-Free',
    'Celery-Free',
    'Mustard-Free',
    'Sesame-Free',
    'Lupine-Free',
    'Mollusk-Free',
    'Alcohol-Free',
    'Sulfite-Free'],
   'cautions': ['Sulfites'],
   'ingredientLines': ['9 ounces oven-ready lasagna noodles (about 15 sheets)',
    '1 ( 48 - ounce ) jar marinara sauce (about 6 cups), or homemade',
    '1 1/2 pounds low-moisture mozzarella , shredded (about 5 cups)',
    '5 ounces sliced pepperoni , preferably small diameter (see recipe note)'],
   'ingredients': [{'text': '9 ounces oven-ready lasagna noodles (about 15 sheets)',
     'quantity': 15.0,
     'measure': 'sheet',
     'food': 'lasagna noodles',
     'weight': 375.0,
     'foodCategory': 'grains',
     'foodId': 'food_a8hs60uayl5icia1qe8qoba1kwp8',
     'image': 'https://www.edamam.com/food-img/296/296ff2b02ef3822928c3c923e22c7d19.jpg'},
    {'text': '1 ( 48 - ounce ) jar marinara sauce (about 6 cups), or homemade',
     'quantity': 6.0,
     'measure': 'cup',
     'food': 'marinara sauce',
     'weight': 1584.0,
     'foodCategory': 'canned soup',
     'foodId': 'food_a7hv5mybkkrs3ub78yhtxafs67bu',
     'image': 'https://www.edamam.com/food-img/08b/08b3bb49c006689a458a8b9c4a4e0057.jpg'},
    {'text': '1 1/2 pounds low-moisture mozzarella , shredded (about 5 cups)',
     'quantity': 5.0,
     'measure': 'cup',
     'food': 'mozzarella',
     'weight': 560.0,
     'foodCategory': 'Cheese',
     'foodId': 'food_am27cpgbcz7639bm3uvx0ai1xhrs',
     'image': 'https://www.edamam.com/food-img/03e/03ec3a4d46bec5634dc8a352804e4e68.jpg'},
    {'text': '5 ounces sliced pepperoni , preferably small diameter (see recipe note)',
     'quantity': 5.0,
     'measure': 'ounce',
     'food': 'pepperoni',
     'weight': 141.747615625,
     'foodCategory': 'Cured meats',
     'foodId': 'food_al5qjzna5bpefha4cy7odah0wwt2',
     'image': 'https://www.edamam.com/food-img/10b/10b28aa71cbe520aef944186f2b365b9.jpg'}],
   'calories': 4572.0579827500005,
   'totalCO2Emissions': 19017.02314834375,
   'co2EmissionsClass': 'G',
   'totalWeight': 2660.747615625,
   'totalTime': 40.0,
   'cuisineType': ['italian'],
   'mealType': ['lunch/dinner'],
   'dishType': ['main course'],
   'totalNutrients': {'ENERC_KCAL': {'label': 'Energy',
     'quantity': 4572.0579827500005,
     'unit': 'kcal'},
    'FAT': {'label': 'Fat', 'quantity': 220.55404603437503, 'unit': 'g'},
    'FASAT': {'label': 'Saturated',
     'quantity': 107.42119796562503,
     'unit': 'g'},
    'FATRN': {'label': 'Trans', 'quantity': 2.2796185190625, 'unit': 'g'},
    'FAMS': {'label': 'Monounsaturated', 'quantity': 71.63707405, 'unit': 'g'},
    'FAPU': {'label': 'Polyunsaturated',
     'quantity': 23.381263656875,
     'unit': 'g'},
    'CHOCDF': {'label': 'Carbs', 'quantity': 412.928821864375, 'unit': 'g'},
    'CHOCDF.net': {'label': 'Carbohydrates (net)',
     'quantity': 372.416821864375,
     'unit': 'g'},
    'FIBTG': {'label': 'Fiber', 'quantity': 40.512, 'unit': 'g'},
    'SUGAR': {'label': 'Sugars', 'quantity': 87.7869, 'unit': 'g'},
    'PROCNT': {'label': 'Protein', 'quantity': 222.3031422, 'unit': 'g'},
    'CHOLE': {'label': 'Cholesterol',
     'quantity': 611.5751871562501,
     'unit': 'mg'},
    'NA': {'label': 'Sodium', 'quantity': 11905.792326875, 'unit': 'mg'},
    'CA': {'label': 'Calcium', 'quantity': 3345.522046968751, 'unit': 'mg'},
    'MG': {'label': 'Magnesium', 'quantity': 621.3845708125, 'unit': 'mg'},
    'K': {'label': 'Potassium', 'quantity': 6719.038466812501, 'unit': 'mg'},
    'FE': {'label': 'Iron', 'quantity': 20.7874432878125, 'unit': 'mg'},
    'ZN': {'label': 'Zinc', 'quantity': 28.266141821250002, 'unit': 'mg'},
    'P': {'label': 'Phosphorus', 'quantity': 3453.6712326875, 'unit': 'mg'},
    'VITA_RAE': {'label': 'Vitamin A', 'quantity': 1493.44, 'unit': 'µg'},
    'VITC': {'label': 'Vitamin C', 'quantity': 31.68, 'unit': 'mg'},
    'THIA': {'label': 'Thiamin (B1)',
     'quantity': 1.26979603834375,
     'unit': 'mg'},
    'RIBF': {'label': 'Riboflavin (B2)',
     'quantity': 3.14033137215625,
     'unit': 'mg'},
    'NIA': {'label': 'Niacin (B3)',
     'quantity': 76.12340601968751,
     'unit': 'mg'},
    'VITB6A': {'label': 'Vitamin B6',
     'quantity': 3.993146368562499,
     'unit': 'mg'},
    'FOLDFE': {'label': 'Folate equivalent (total)',
     'quantity': 319.7073807812499,
     'unit': 'µg'},
    'FOLFD': {'label': 'Folate (food)',
     'quantity': 319.7073807812499,
     'unit': 'µg'},
    'FOLAC': {'label': 'Folic acid', 'quantity': 0.0, 'unit': 'µg'},
    'VITB12': {'label': 'Vitamin B12',
     'quantity': 14.610719003125002,
     'unit': 'µg'},
    'VITD': {'label': 'Vitamin D', 'quantity': 4.082719003125, 'unit': 'µg'},
    'TOCPHA': {'label': 'Vitamin E',
     'quantity': 40.9525004409375,
     'unit': 'mg'},
    'VITK1': {'label': 'Vitamin K',
     'quantity': 241.65236170625002,
     'unit': 'µg'},
    'WATER': {'label': 'Water', 'quantity': 1750.00081806875, 'unit': 'g'}},
   'totalDaily': {'ENERC_KCAL': {'label': 'Energy',
     'quantity': 228.60289913750003,
     'unit': '%'},
    'FAT': {'label': 'Fat', 'quantity': 339.31391697596155, 'unit': '%'},
    'FASAT': {'label': 'Saturated',
     'quantity': 537.1059898281252,
     'unit': '%'},
    'CHOCDF': {'label': 'Carbs', 'quantity': 137.64294062145834, 'unit': '%'},
    'FIBTG': {'label': 'Fiber', 'quantity': 162.048, 'unit': '%'},
    'PROCNT': {'label': 'Protein', 'quantity': 444.6062844, 'unit': '%'},
    'CHOLE': {'label': 'Cholesterol',
     'quantity': 203.85839571875005,
     'unit': '%'},
    'NA': {'label': 'Sodium', 'quantity': 496.0746802864584, 'unit': '%'},
    'CA': {'label': 'Calcium', 'quantity': 334.55220469687515, 'unit': '%'},
    'MG': {'label': 'Magnesium', 'quantity': 147.94870733630952, 'unit': '%'},
    'K': {'label': 'Potassium', 'quantity': 142.9582652513298, 'unit': '%'},
    'FE': {'label': 'Iron', 'quantity': 115.48579604340279, 'unit': '%'},
    'ZN': {'label': 'Zinc', 'quantity': 256.9649256477273, 'unit': '%'},
    'P': {'label': 'Phosphorus', 'quantity': 493.3816046696428, 'unit': '%'},
    'VITA_RAE': {'label': 'Vitamin A',
     'quantity': 165.93777777777777,
     'unit': '%'},
    'VITC': {'label': 'Vitamin C', 'quantity': 35.2, 'unit': '%'},
    'THIA': {'label': 'Thiamin (B1)',
     'quantity': 105.81633652864585,
     'unit': '%'},
    'RIBF': {'label': 'Riboflavin (B2)',
     'quantity': 241.5639517043269,
     'unit': '%'},
    'NIA': {'label': 'Niacin (B3)',
     'quantity': 475.77128762304693,
     'unit': '%'},
    'VITB6A': {'label': 'Vitamin B6',
     'quantity': 307.16510527403835,
     'unit': '%'},
    'FOLDFE': {'label': 'Folate equivalent (total)',
     'quantity': 79.92684519531248,
     'unit': '%'},
    'VITB12': {'label': 'Vitamin B12',
     'quantity': 608.7799584635418,
     'unit': '%'},
    'VITD': {'label': 'Vitamin D',
     'quantity': 27.218126687499996,
     'unit': '%'},
    'TOCPHA': {'label': 'Vitamin E', 'quantity': 273.01666960625, 'unit': '%'},
    'VITK1': {'label': 'Vitamin K',
     'quantity': 201.37696808854167,
     'unit': '%'}},
   'digest': [{'label': 'Fat',
     'tag': 'FAT',
     'schemaOrgTag': 'fatContent',
     'total': 220.55404603437503,
     'hasRDI': True,
     'daily': 339.31391697596155,
     'unit': 'g',
     'sub': [{'label': 'Saturated',
       'tag': 'FASAT',
       'schemaOrgTag': 'saturatedFatContent',
       'total': 107.42119796562503,
       'hasRDI': True,
       'daily': 537.1059898281252,
       'unit': 'g'},
      {'label': 'Trans',
       'tag': 'FATRN',
       'schemaOrgTag': 'transFatContent',
       'total': 2.2796185190625,
       'hasRDI': False,
       'daily': 0.0,
       'unit': 'g'},
      {'label': 'Monounsaturated',
       'tag': 'FAMS',
       'schemaOrgTag': None,
       'total': 71.63707405,
       'hasRDI': False,
       'daily': 0.0,
       'unit': 'g'},
      {'label': 'Polyunsaturated',
       'tag': 'FAPU',
       'schemaOrgTag': None,
       'total': 23.381263656875,
       'hasRDI': False,
       'daily': 0.0,
       'unit': 'g'}]},
    {'label': 'Carbs',
     'tag': 'CHOCDF',
     'schemaOrgTag': 'carbohydrateContent',
     'total': 412.928821864375,
     'hasRDI': True,
     'daily': 137.64294062145834,
     'unit': 'g',
     'sub': [{'label': 'Carbs (net)',
       'tag': 'CHOCDF.net',
       'schemaOrgTag': None,
       'total': 372.416821864375,
       'hasRDI': False,
       'daily': 0.0,
       'unit': 'g'},
      {'label': 'Fiber',
       'tag': 'FIBTG',
       'schemaOrgTag': 'fiberContent',
       'total': 40.512,
       'hasRDI': True,
       'daily': 162.048,
       'unit': 'g'},
      {'label': 'Sugars',
       'tag': 'SUGAR',
       'schemaOrgTag': 'sugarContent',
       'total': 87.7869,
       'hasRDI': False,
       'daily': 0.0,
       'unit': 'g'},
      {'label': 'Sugars, added',
       'tag': 'SUGAR.added',
       'schemaOrgTag': None,
       'total': 0.0,
       'hasRDI': False,
       'daily': 0.0,
       'unit': 'g'}]},
    {'label': 'Protein',
     'tag': 'PROCNT',
     'schemaOrgTag': 'proteinContent',
     'total': 222.3031422,
     'hasRDI': True,
     'daily': 444.6062844,
     'unit': 'g'},
    {'label': 'Cholesterol',
     'tag': 'CHOLE',
     'schemaOrgTag': 'cholesterolContent',
     'total': 611.5751871562501,
     'hasRDI': True,
     'daily': 203.85839571875005,
     'unit': 'mg'},
    {'label': 'Sodium',
     'tag': 'NA',
     'schemaOrgTag': 'sodiumContent',
     'total': 11905.792326875,
     'hasRDI': True,
     'daily': 496.0746802864584,
     'unit': 'mg'},
    {'label': 'Calcium',
     'tag': 'CA',
     'schemaOrgTag': None,
     'total': 3345.522046968751,
     'hasRDI': True,
     'daily': 334.55220469687515,
     'unit': 'mg'},
    {'label': 'Magnesium',
     'tag': 'MG',
     'schemaOrgTag': None,
     'total': 621.3845708125,
     'hasRDI': True,
     'daily': 147.94870733630952,
     'unit': 'mg'},
    {'label': 'Potassium',
     'tag': 'K',
     'schemaOrgTag': None,
     'total': 6719.038466812501,
     'hasRDI': True,

In [ ]:
urls = []
labels = []
sources = []
ingreds = []
cuisines = []

for recipe in resp_dict_hits:
    recipe_path = recipe["recipe"]
    urls.append(recipe_path["url"])
    labels.append(recipe_path["label"])
    sources.append(recipe_path["source"])
    ingreds.append(recipe_path["ingredientLines"])
    cuisines.append(recipe_path["cuisineType"])

all_recipes = {
    "url": urls,
    "label": labels,
    "source": sources,
    "ingredients": ingreds,
    "cuisines": cuisines,
}

recipe_df = pl.DataFrame(all_recipes)

In [ ]:
recipe_df

shape: (20, 5)
┌──────────────────────┬─────────────────────┬─────────────────┬─────────────────────┬─────────────┐
│ url                  ┆ label               ┆ source          ┆ ingredients         ┆ cuisines    │
│ ---                  ┆ ---                 ┆ ---             ┆ ---                 ┆ ---         │
│ str                  ┆ str                 ┆ str             ┆ list[str]           ┆ list[str]   │
╞══════════════════════╪═════════════════════╪═════════════════╪═════════════════════╪═════════════╡
│ https://www.simplyre ┆ Pizza Lasagna       ┆ Simply Recipes  ┆ ["9 ounces          ┆ ["italian"] │
│ cipes.com/…          ┆                     ┆                 ┆ oven-ready lasagna  ┆             │
│                      ┆                     ┆                 ┆ …                   ┆             │
│ https://www.marthast ┆ Lasagna             ┆ Martha Stewart  ┆ ["1 pound lasagna   ┆ ["italian"] │
│ ewart.com/…          ┆                     ┆                 ┆ noodles or p…       ┆             │
│ https://food52.com/r ┆ Lasagna a la Maison ┆ Food52          ┆ ["1 packet          ┆ ["italian"] │
│ ecipes/839…          ┆                     ┆                 ┆ Lasagna", "3        ┆             │
│                      ┆                     ┆                 ┆ pieces…             ┆             │
│ http://smittenkitche ┆ Mushroom Lasagna    ┆ Smitten Kitchen ┆ ["Salt", "Olive     ┆ ["italian"] │
│ n.com/2010…          ┆                     ┆                 ┆ oil", … "1 cup…     ┆             │
│ http://www.seriousea ┆ Mushroom Lasagna    ┆ Serious Eats    ┆ ["3/4 pound dried   ┆ ["italian"] │
│ ts.com/rec…          ┆ Recipe              ┆                 ┆ lasagna nood…       ┆             │
│ …                    ┆ …                   ┆ …               ┆ …                   ┆ …           │
│ https://honestcookin ┆ Zucchini Lasagna    ┆ Honest Cooking  ┆ ["1 package 12 oz   ┆ ["italian"] │
│ g.com/zucc…          ┆                     ┆                 ┆ fresh lasagn…       ┆             │
│ https://www.marthast ┆ 8-Layer Lasagna     ┆ Martha Stewart  ┆ ["3/4 cup dried     ┆ ["italian"] │
│ ewart.com/…          ┆                     ┆                 ┆ porcini mushro…     ┆             │
│ https://food52.com/r ┆ Vegetarian Lasagna  ┆ Food52          ┆ ["For the sauce",   ┆ ["italian"] │
│ ecipes/277…          ┆                     ┆                 ┆ "2 tablespoo…       ┆             │
│ https://www.marthast ┆ Zucchini Lasagna    ┆ Martha Stewart  ┆ ["Olive oil, for    ┆ ["italian"] │
│ ewart.com/…          ┆                     ┆                 ┆ baking dish",…      ┆             │
│ https://food52.com/r ┆ Lasagna Bolognese   ┆ Food52          ┆ ["To make the       ┆ ["italian"] │
│ ecipes/777…          ┆                     ┆                 ┆ bolognese sauce:…   ┆             │
└──────────────────────┴─────────────────────┴─────────────────┴─────────────────────┴─────────────┘

In [ ]:
one_recipe = []

for listing in recipe_df["ingredients"]:
    for ingred in listing:
        one_recipe.append(ingred.lower())

one_recipe = list(set(one_recipe))

query_df = pl.DataFrame(
    data={
        "name": dish_name,
        "ingredients": [one_recipe],
        "cuisine": cuisine_type,
    }
)

query_df

shape: (1, 3)
┌─────────┬─────────────────────────────────┬─────────┐
│ name    ┆ ingredients                     ┆ cuisine │
│ ---     ┆ ---                             ┆ ---     │
│ str     ┆ list[str]                       ┆ str     │
╞═════════╪═════════════════════════════════╪═════════╡
│ lasagna ┆ ["6 no-boil lasagna noodles", … ┆ italian │
└─────────┴─────────────────────────────────┴─────────┘

In [ ]:
all_recipes["ingredients"]

[['9 ounces oven-ready lasagna noodles (about 15 sheets)',
  '1 ( 48 - ounce ) jar marinara sauce (about 6 cups), or homemade',
  '1 1/2 pounds low-moisture mozzarella , shredded (about 5 cups)',
  '5 ounces sliced pepperoni , preferably small diameter (see recipe note)'],
 ['1 pound lasagna noodles or packaged precooked lasagna noodles',
  'coarse salt',
  '5 links sweet Italian sausage, or a mixture of hot and sweet, pierced with a fork',
  '1 large egg',
  '1 pound ricotta cheese',
  '3/4 cup freshly grated pecorino Romano or Parmesan cheese, plus more for serving',
  '5 cups Basic Italian Tomato Sauce, (double the recipe and cook for 30 minutes longer to thicken)',
  '1 pound fresh or prepackaged mozzarella cheese, cut crosswise into 1/3-inch-thick slices',
  'extra virgin olive oil, for drizzling'],
 ['1 packet Lasagna', '3 pieces tomatoes', 'olives pieces 12'],
 ['Salt',
  'Olive oil',
  '3/4 pound dried lasagna noodles',
  '1 large clove garlic, minced',
  '4 cups whole milk',
  '3/4 cup (12 tablespoons or 1 1/2 sticks) unsalted butter, divided',
  '1/2 cup all-purpose flour',
  '1 teaspoon freshly ground black pepper',
  '1 teaspoon ground nutmeg (I used less, because this seemed like a lot)',
  '1 1/2 pounds cremini or portobello mushrooms',
  '1 cup freshly grated parmesan'],
 ['3/4 pound dried lasagna noodles',
  '4 tablespoons olive oil, divided',
  '4 cups whole milk',
  '1 large garlic clove, minced',
  '3/4 cup unsalted butter (1 1/2 sticks), divided',
  '1/2 cup all-purpose flour',
  '1 teaspoon ground black pepper',
  '1/2 teaspoon ground nutmeg',
  '1 1/2 pounds cremini or portobello mushrooms, stems removed, sliced 1/4-inch thick',
  '1 cup grated Parmesan'],
 ['9 Colavita lasagna noodles',
  '3 cups grated Mozzarella cheese',
  '⅓ cup grated Parmesan cheese'],
 ['1 pound lasagna noodles (not no-boil)',
  '1 (16-ounce) container ricotta',
  '2 cups shredded mozzarella',
  '1/2 cup grated Parmesan',
  '1 tablespoon Italian seasoning',
  '2 large eggs',
  '1 (10-ounce) package frozen chopped spinach, thawed and excess water squeezed out',
  '2 (24-ounce) jars marinara sauce, divided'],
 ['1 10-ounce package frozen peas',
  '1 16-ounce container ricotta',
  'Kosher salt and black pepper',
  'Kosher salt and black pepper',
  '1 16-ounce jar marinara sauce',
  '1 9-ounce package no-boil lasagna noodles',
  '1/4 cup shredded mozzarella'],
 ['6 tablespoons extra-virgin olive oil',
  '1 medium onion, chopped',
  '5 garlic cloves, minced',
  'Kosher salt',
  'Freshly ground black pepper',
  '6 tablespoons all-purpose flour',
  '6 cups whole milk',
  '12 ounces baby spinach',
  '12 no-boil lasagna noodles',
  '1 cup ricotta cheese'],
 ['1 pound ground beef',
  '1 pound mild italian sausage',
  'salt and pepper to taste',
  'salt and pepper to taste',
  '1 teaspoon red pepper flakes (optional)',
  '4 cups sausage marinara',
  '1 box of about 20 or more lasagna noodles, cooked',
  '1 cup Parmesan cheese, grated',
  '30 ounces ricotta cheese',
  '4 cups Mozzarella cheese, shredded'],
 ['4 cups (32 ounces) whole-milk ricotta cheese',
  '2 large eggs',
  'Salt and fresh ground pepper',
  'Salt and fresh ground pepper',
  '2 packages (10 ounces each) frozen chopped spinach, thawed and squeezed to remove excess moisture',
  '6 cups store-bought or homemade Easy Chunky Tomato Sauce',
  '12 no-boil lasagna noodles (8 ounces)',
  '1 pound fontina cheese (4 cups), shredded'],
 ['18 oz lasagna',
  '7 oz Parmigiano Reggiano cheese',
  '35 oz béchamel sauce',
  '½ lb ground beef',
  '½ lb ground veal',
  '3 oz onion',
  '1 oz carrots',
  '2 oz celery',
  '1 cup red wine',
  '4 tablespoons extra virgin olive oil',
  '1 tablespoon of mixed herbs sage, parsley, thyme, rosemary',
  '1 can peeled tomatoes',
  'salt and pepper to taste',
  'salt and pepper to taste'],
 ['1 stick unsalted butter',
  '6 tablespoons all-purpose flour',
  '6 cups whole milk',
  '3 cups grated parmesan cheese',
  'Kosher salt',
  'Freshly ground black pepper',
  '12 no-boil lasagna noodles'],
 ['1 tablespoon unsalted butter',
  '1 pound dried or Fresh Lasagna Sheets',
  '8 cups Bechamel Sauce',
  '6 cups Roasted Roma Tomatoes, and their juices',
  '2 cups ricotta cheese',
  '4 cups grated pecorino cheese',
  '2 cups fresh basil',
  '2 cups dried breadcrumbs',
  '2 tablespoons olive oil'],
 ['1 tablespoon Extra virgin olive oil',
  '1/4 cup chopped yellow onion',
  '3/4 pound loose sweet Italian sausage',
  '25 ounces Pomodoro Fresco Tomato Basil Sauce',
  '6 cups vegetable stock',
  '9 ounces No-boil lasagna',
  '1/4 cup chopped fresh basil leaves',
  '1/4 cup heavy cream',
  '1 clove garlic, chopped'],
 ['1 package 12 oz fresh lasagna sheets',
  '3 tbsp Extra Virgin Olive Oil',
  '1 garlic clove',
  '2 large zucchini',
  '2 medium potatoes',
  '1 cup water warm',
  '2 cups whole milk warm',
  '4 tbsp unsalted butter',
  '4 tbsp flour',
  '1 pinch ground nutmeg',
  'salt and pepper to taste',
  'salt and pepper to taste',
  '1 cup Parmigiano Reggiano grated'],
 ['3/4 cup dried porcini mushrooms (about 3/4 ounce)',
  '1 bay leaf, preferably fresh',
  '1 sprig fresh rosemary',
  '1 sprig fresh thyme',
  '2 whole cloves',
  '3/4 cup (1 1/2 sticks) plus 2 tablespoons unsalted butter, divided',
  '3/4 cup (1 1/2 sticks) plus 2 tablespoons unsalted butter, divided',
  '4 1/2 ounces prosciutto, cut into 1/4-inch pieces',
  '2 1/4 cups very finely chopped onions',
  '3/4 cup very finely chopped celery',
  '3/4 cup very finely chopped carrots',
  '2 tablespoons extra-virgin olive oil, divided',
  '2 pounds boneless pork shoulder, trimmed and coarsely ground',
  '2 teaspoons tomato paste',
  '3 cups dry Marsala wine',
  '3 cups Homemade Brown Chicken Stock',
  'Coarse salt and freshly ground black pepper',
  'Coarse salt and freshly ground black pepper',
  '10 ounces cremini mushrooms, finely chopped (about 3 1/4 cups)',
  '2 pounds Lasagna Noodles for 8-Layer Lasagna',
  '2 cups freshly grated Parmigiano-Reggiano cheese, plus more for topping',
  "4 cups Martha's Bechamel Sauce for Lasagna"],
 ['2 tablespoons olive oil',
  '1 yellow onion, diced',
  '1 large carrot, diced',
  '1/4 cup white wine',
  '28 ounces canned whole tomatoes',
  '28 ounces canned tomato purée',
  '1 teaspoon dried thyme',
  '1 tablespoon salt',
  'Freshly ground pepper',
  '4 to 6 tablespoons olive oil',
  '3 to 4 medium zucchini, sliced 1/3 inch thick (they’ll shrink when cooked)',
  '2 Italian eggplants, sliced 1/3 inch thick',
  '1 egg',
  '15 ounces ricotta cheese',
  '9 ounces no-boil or oven-ready lasagna noodles',
  '4 ounces goat cheese (I love the Vermont Creamery brand)',
  '1 pound fresh mozzarella, sliced (you should have enough slices to cover the whole top of the lasagna)',
  '4 tablespoons grated Parmesan cheese',
  'Salt and pepper',
  'Salt and pepper'],
 ['Olive oil, for baking dish',
  '8 ounces reduced-fat cream cheese, room temperature',
  '1 container (15 ounces) part-skim ricotta cheese',
  'Coarse salt and ground pepper',
  'Coarse salt and ground pepper',
  '2 medium zucchini (8 ounces each), halved lengthwise, then sliced thinly crosswise',
  '1 garlic clove, minced',
  '2 teaspoons dried oregano',
  '6 no-boil lasagna noodles',
  '2 ounces shredded (1/2 cup) part-skim mozzarella cheese'],
 ['1/2 cup Italian extra virgin olive oil, plus 3 tablespoons',
  '1/2 cup Italian extra virgin olive oil, plus 3 tablespoons',
  '4-5 fresh basil leaves',
  '2 cloves garlic, peeled and smashed (plus 1 clove finely chopped)',
  '2 teaspoons crushed red pepper (optional, and more to taste)',
  '8 cups crushed tomatoes',
  '2 cups water, as needed',
  '2 tablespoons tomato paste',
  '1 teaspoon kosher salt',
  '1 teaspoon freshly ground black pepper',
  '1 tablespoon chopped basil',
  '1 small onion, finely chopped',
  '1/4 pound pancetta, finely chopped',
  '1 pound organic ground beef (93% lean)',
  '1/2 cup good red wine',
  '1 bay leaf',
  '1/2 cup mascarpone cheese',
  '1/4 cup butter',
  '1/4 cup flour',
  '3 cups organic dairy milk, warmed',
  '9 lasagna sheets (or 1 package fresh lasagna sheets)',
  '1 cup grated parmigiano cheese, plus 1 cup',
  '1 cup grated parmigiano cheese, plus 1 cup',
  'Sliced fresh mozzarella (optional)']]

In [ ]:
no_dataframe_recipe = []

for listing in all_recipes["ingredients"]:
    for ingred in listing:
        no_dataframe_recipe.append(ingred.lower())

no_dataframe_recipe = list(set(no_dataframe_recipe))
no_dataframe_recipe

['6 no-boil lasagna noodles',
 '1 small onion, finely chopped',
 '3/4 cup dried porcini mushrooms (about 3/4 ounce)',
 '3/4 cup (12 tablespoons or 1 1/2 sticks) unsalted butter, divided',
 '1 large garlic clove, minced',
 '9 colavita lasagna noodles',
 '1 teaspoon ground black pepper',
 '7 oz parmigiano reggiano cheese',
 '2 tablespoons extra-virgin olive oil, divided',
 '1/2 cup grated parmesan',
 '1 pinch ground nutmeg',
 '1 stick unsalted butter',
 '2 ounces shredded (1/2 cup) part-skim mozzarella cheese',
 '1 medium onion, chopped',
 '1 large clove garlic, minced',
 '1 pound mild italian sausage',
 '1 cup grated parmesan',
 '6 cups whole milk',
 'extra virgin olive oil, for drizzling',
 '1 pound ground beef',
 '1/4 cup shredded mozzarella',
 '1 can peeled tomatoes',
 '2 1/4 cups very finely chopped onions',
 '1 teaspoon red pepper flakes (optional)',
 '1 cup freshly grated parmesan',
 '2 cups ricotta cheese',
 '4 tablespoons extra virgin olive oil',
 'coarse salt',
 '1 garlic clove',
 '12 no-boil lasagna noodles (8 ounces)',
 '5 cups basic italian tomato sauce, (double the recipe and cook for 30 minutes longer to thicken)',
 '5 ounces sliced pepperoni , preferably small diameter (see recipe note)',
 '1 package 12 oz fresh lasagna sheets',
 '2 tablespoons olive oil',
 '1 (10-ounce) package frozen chopped spinach, thawed and excess water squeezed out',
 'kosher salt and black pepper',
 '3/4 cup very finely chopped celery',
 '1 cup parmigiano reggiano grated',
 '3 pieces tomatoes',
 '1 1/2 pounds cremini or portobello mushrooms',
 'sliced fresh mozzarella (optional)',
 '3/4 cup freshly grated pecorino romano or parmesan cheese, plus more for serving',
 '1 tablespoon salt',
 '⅓ cup grated parmesan cheese',
 '1 sprig fresh rosemary',
 '4 tbsp flour',
 '1 9-ounce package no-boil lasagna noodles',
 '6 cups roasted roma tomatoes, and their juices',
 '1 cup ricotta cheese',
 '1 large carrot, diced',
 '1 pound lasagna noodles (not no-boil)',
 '25 ounces pomodoro fresco tomato basil sauce',
 '1 pound ricotta cheese',
 '6 cups store-bought or homemade easy chunky tomato sauce',
 '1 bay leaf, preferably fresh',
 '1 garlic clove, minced',
 '4 tbsp unsalted butter',
 '1 cup parmesan cheese, grated',
 '2 pounds lasagna noodles for 8-layer lasagna',
 'salt',
 '1 pound fontina cheese (4 cups), shredded',
 '4 cups mozzarella cheese, shredded',
 '4 ounces goat cheese (i love the vermont creamery brand)',
 '1/2 cup mascarpone cheese',
 '1 tablespoon extra virgin olive oil',
 '1/4 cup flour',
 'salt and pepper to taste',
 '1 cup grated parmigiano cheese, plus 1 cup',
 '4 cups sausage marinara',
 '1 oz carrots',
 '6 cups vegetable stock',
 '8 cups crushed tomatoes',
 '4 cups grated pecorino cheese',
 '3 cups dry marsala wine',
 '2 italian eggplants, sliced 1/3 inch thick',
 '1 pound fresh mozzarella, sliced (you should have enough slices to cover the whole top of the lasagna)',
 '4-5 fresh basil leaves',
 '35 oz béchamel sauce',
 '8 ounces reduced-fat cream cheese, room temperature',
 '1 10-ounce package frozen peas',
 '2 large eggs',
 '1/2 cup italian extra virgin olive oil, plus 3 tablespoons',
 '1/4 cup chopped fresh basil leaves',
 '3 tbsp extra virgin olive oil',
 '1 tablespoon italian seasoning',
 '1 pound dried or fresh lasagna sheets',
 '8 cups bechamel sauce',
 'coarse salt and ground pepper',
 '2 tablespoons tomato paste',
 '2 medium potatoes',
 '1 teaspoon kosher salt',
 '2 cups fresh basil',
 '5 garlic cloves, minced',
 '1 tablespoon chopped basil',
 '1/2 cup all-purpose flour',
 '½ lb ground veal',
 '2 (24-ounce) jars marinara sauce, divided',
 '9 ounces no-boil lasagna',
 '28 ounces canned whole tomatoes',
 '1 teaspoon ground nutmeg (i used less, because this seemed like a lot)',
 '1 pound fresh or prepackaged mozzarella cheese, cut crosswise into 1/3-inch-thick slices',
 '2 cups freshly grated parmigiano-reggiano cheese, plus more for topping',
 '3 cups organic dairy milk, warmed',
 '3 to 4 medium zucchini, sliced 1/3 inch thick (they’ll shrink when cooked)',
 '1 sprig fresh thyme',
 '1 cup water warm',
 '1/4 cup heavy cream',
 '1/4 cup chopped yellow onion',
 '½ lb ground beef',
 '1 clove garlic, chopped',
 '9 ounces no-boil or oven-ready lasagna noodles',
 '1 pound lasagna noodles or packaged precooked lasagna noodles',
 '2 pounds boneless pork shoulder, trimmed and coarsely ground',
 '4 1/2 ounces prosciutto, cut into 1/4-inch pieces',
 '2 teaspoons dried oregano',
 '1 cup red wine',
 '3/4 cup very finely chopped carrots',
 '1 large egg',
 '6 tablespoons all-purpose flour',
 '12 no-boil lasagna noodles',
 '2 packages (10 ounces each) frozen chopped spinach, thawed and squeezed to remove excess moisture',
 '30 ounces ricotta cheese',
 'salt and pepper',
 '10 ounces cremini mushrooms, finely chopped (about 3 1/4 cups)',
 '3 cups grated mozzarella cheese',
 '3/4 pound dried lasagna noodles',
 '28 ounces canned tomato purée',
 '1 tablespoon of mixed herbs sage, parsley, thyme, rosemary',
 '18 oz lasagna',
 '2 teaspoons tomato paste',
 '2 oz celery',
 '1 egg',
 '3 cups grated parmesan cheese',
 '1/4 cup butter',
 '1/4 cup white wine',
 '1 box of about 20 or more lasagna noodles, cooked',
 '1 ( 48 - ounce ) jar marinara sauce (about 6 cups), or homemade',
 '1 packet lasagna',
 '1 teaspoon freshly ground black pepper',
 '3 oz onion',
 '3/4 cup (1 1/2 sticks) plus 2 tablespoons unsalted butter, divided',
 'coarse salt and freshly ground black pepper',
 '2 cups water, as needed',
 '1 1/2 pounds cremini or portobello mushrooms, stems removed, sliced 1/4-inch thick',
 'olives pieces 12',
 'salt and fresh ground pepper',
 '4 cups (32 ounces) whole-milk ricotta cheese',
 '1 tablespoon unsalted butter',
 '2 teaspoons crushed red pepper (optional, and more to taste)',
 '1 container (15 ounces) part-skim ricotta cheese',
 '2 cups shredded mozzarella',
 '15 ounces ricotta cheese',
 'freshly ground pepper',
 '2 medium zucchini (8 ounces each), halved lengthwise, then sliced thinly crosswise',
 '5 links sweet italian sausage, or a mixture of hot and sweet, pierced with a fork',
 '9 lasagna sheets (or 1 package fresh lasagna sheets)',
 '1 pound organic ground beef (93% lean)',
 '1 16-ounce jar marinara sauce',
 '6 tablespoons extra-virgin olive oil',
 '2 large zucchini',
 '4 tablespoons olive oil, divided',
 "4 cups martha's bechamel sauce for lasagna",
 '1 yellow onion, diced',
 '4 tablespoons grated parmesan cheese',
 '3/4 cup unsalted butter (1 1/2 sticks), divided',
 'freshly ground black pepper',
 '4 to 6 tablespoons olive oil',
 '1 (16-ounce) container ricotta',
 '1/4 pound pancetta, finely chopped',
 'olive oil',
 '9 ounces oven-ready lasagna noodles (about 15 sheets)',
 '3/4 pound loose sweet italian sausage',
 '1/2 teaspoon ground nutmeg',
 'kosher salt',
 '4 cups whole milk',
 '12 ounces baby spinach',
 '2 cups dried breadcrumbs',
 '1/2 cup good red wine',
 '2 whole cloves',
 'olive oil, for baking dish',
 '1 teaspoon dried thyme',
 '2 cups whole milk warm',
 '1 16-ounce container ricotta',
 '2 cloves garlic, peeled and smashed (plus 1 clove finely chopped)',
 '1 bay leaf',
 '1 1/2 pounds low-moisture mozzarella , shredded (about 5 cups)',
 '3 cups homemade brown chicken stock']